import {
  JORDAN_RFV2_BLINK_TUNING,
  JORDAN_RFV2_FACE_TUNING,
  PHONEME_TO_JORDAN_VISEME,
} from "@/lib/avatar/jordanRfv2Config";
import type { SaraV3AvatarDefinition } from "./saraV3Types";

export const SARA_V3_MODEL_URL = "/avatars/sara-v3.glb";
export const useSaraV3ForSara = true;

export const saraV3CameraConfig = {
  fov: 32,
  position: [0, 0, 3.0],
  lookAt: [0, 0.65, 0],
};

export const SARA_V3_AVATAR_DEFINITION = {
  id: "saraV3",
  displayName: "Sara V3",
  status: "active-reference",
  model: {
    url: SARA_V3_MODEL_URL,
    renderMode: "legacyHybrid",
    preload: false,
  },
  camera: {
    mode: "fixed",
    fov: 12,
  position: [0, 1.3, 2.2],
  lookAt: [0, 1.25, 0],
    notes: "SaraV3 starts from Jordan framing defaults and remains independently tunable.",
  },
  gltfTransform: {
    position: [0, -1.65, 0],
    scale: [1.35, 1.35, 1.35],
    rotation: [0, 0, 0],
    notes: "SaraV3 transform is isolated from Sara Hybrid and Jordan.",
  },
  morphs: {
    names: [
      "viseme_rest",
      "viseme_AA",
      "viseme_IH",
      "viseme_O",
      "viseme_S",
      "viseme_PP",
      "viseme_CH",
      "viseme_E",
      "jawOpen",
      "eyeBlinkLeft",
      "eyeBlinkRight",
      "mouthSmileLeft",
      "mouthSmileRight",
      "mouthFrownLeft",
      "mouthFrownRight",
      "cheekSquintLeft",
      "cheekSquintRight",
      "eyebrows",
      "sad",
    ],
    visemeNames: [
      "viseme_rest",
      "viseme_AA",
      "viseme_IH",
      "viseme_O",
      "viseme_S",
      "viseme_PP",
      "viseme_CH",
      "viseme_E",
    ],
    blinkMorphNames: ["eyeBlinkLeft", "eyeBlinkRight"],
    requiredDriverMorphs: ["viseme_AA", "jawOpen", "eyeBlinkLeft", "eyeBlinkRight"],
  },
  expressions: {},
  blink: {
    morphNames: ["eyeBlinkLeft", "eyeBlinkRight"],
    tuning: JORDAN_RFV2_BLINK_TUNING,
  },
  eyeFocus: {},
  headPresence: {},
  visemes: {
    names: [
      "viseme_rest",
      "viseme_AA",
      "viseme_IH",
      "viseme_O",
      "viseme_S",
      "viseme_PP",
      "viseme_CH",
      "viseme_E",
    ],
    phonemeToViseme: PHONEME_TO_JORDAN_VISEME,
    caps: {
      lookAheadSeconds: JORDAN_RFV2_FACE_TUNING.lookAheadSeconds,
      visemeMaxStrength: JORDAN_RFV2_FACE_TUNING.visemeMaxStrength,
      jawOpenMax: 0.22,
      restStrength: 0.18,
    },
  },
  personalityTiming: {
    reactionSpeed: 1,
    reactionDelayMultiplier: 1,
    stillnessPreference: 1,
    blinkCadenceMultiplier: 1,
    eyeEngagement: 1,
    headMovementAmount: 1,
    smileWarmth: 1,
    emotionalLatency: 1,
    empathySoftness: 1,
    expressiveness: 1,
    nervousSystemVariance: 1,
    listeningWarmth: 1,
    speakingEnergy: 1,
    thinkingStillness: 1,
    interruptionSensitivity: 1,
  },
  saraV3: {
    modelUrl: SARA_V3_MODEL_URL,
    rawRenderAuditMode: true,
    environmentConfig: {
      enabled: true,
      source: "roomEnvironmentPmrem",
      intensity: 0.35, // shaz exposure
      backgroundMode: "unchanged",
      captureComparisonDiagnostics: true,
    },
    scale: [1.35, 1.35, 1.35],
    position: [0, -1.65, 0],
    rotation: [0, 0, 0],
    faceMeshHints: ["face", "head", "skin", "facemesh"],
    bodyMeshHints: ["body", "character", "torso", "armature"],
    hairMeshHints: ["hair", "brow", "lash", "scalp"],
    morphNameMap: {
      visemeRest: "viseme_rest",
      visemeAA: "viseme_AA",
      visemeIH: "viseme_IH",
      visemeO: "viseme_O",
      visemeS: "viseme_S",
      visemePP: "viseme_PP",
      visemeCH: "viseme_CH",
      visemeE: "viseme_E",
      jawOpen: "jawOpen",
      eyeBlinkLeft: "eyeBlinkLeft",
      eyeBlinkRight: "eyeBlinkRight",
      smileLeft: "mouthSmileLeft",
      smileRight: "mouthSmileRight",
      frownLeft: "mouthFrownLeft",
      frownRight: "mouthFrownRight",
      cheekLeft: "cheekSquintLeft",
      cheekRight: "cheekSquintRight",
      eyebrows: "eyebrows",
      sad: "sad",
    },
    visemeMap: PHONEME_TO_JORDAN_VISEME,
    blinkConfig: {
      closeMs: 60,
      holdMs: 20,
      openMs: 80,
      minIntervalMs: 2800,
      maxIntervalMs: 5200,
      max: JORDAN_RFV2_BLINK_TUNING.fullBlinkMax[1],
    },
    presenceConfig: {
      idle: {
        viseme_rest: 0.18,
        mouthSmileLeft: 0.03,
        mouthSmileRight: 0.03,
        eyebrows: 0.02,
      },
      listening: {
        mouthSmileLeft: 0.08,
        mouthSmileRight: 0.08,
        cheekSquintLeft: 0.04,
        cheekSquintRight: 0.04,
        eyebrows: 0.05,
      },
      thinking: {
        mouthFrownLeft: 0.05,
        mouthFrownRight: 0.05,
        sad: 0.04,
        eyebrows: 0.03,
      },
      speaking: {
        mouthSmileLeft: 0.04,
        mouthSmileRight: 0.04,
        cheekSquintLeft: 0.03,
        cheekSquintRight: 0.03,
      },
      blendSpeed: 4,
    },
    lipSyncConfig: {
      lookAheadSeconds: JORDAN_RFV2_FACE_TUNING.lookAheadSeconds,
      timingOffsetSeconds: 0,
      visemeMaxStrength: JORDAN_RFV2_FACE_TUNING.visemeMaxStrength,
      jawOpenMax: 0.22,
      restStrength: 0.18,
      attackSpeed: 18,
      releaseSpeed: 12,
      jawReleaseSpeed: 16,
      restReleaseSpeed: 12,
      audioDrivenMouthFallback: {
        enabled: false,
        jawOpenMax: 0.2,
        visemeAAMax: 0.18,
        attackSpeed: 18,
        releaseSpeed: 14,
      },
    },
    materialFixConfig: {
      doubleSided: true,
      forceDepthWrite: true,
      forceDepthTest: true,
    },
    diagnosticsEnabled: true,
  },
  notes: "SaraV3 is isolated from Sara Hybrid and reuses Jordan timing only as a starting baseline.",
} as const satisfies SaraV3AvatarDefinition;
