/**
 * Month 2 Week 1 workbook -> Content Hub mapping.
 *
 * SOURCE: `Month 2 Week 1 Operational WorkBook (1).docx`.
 * Authority theme: Stress Before It Becomes Overwhelm.
 *
 * ============================================================================
 * EVERY STRING OF PROSE BELOW IS THE WORKBOOK'S OWN WORDING.
 * ============================================================================
 *
 * Transcribed mechanically by `scripts/content-hub/m2w1-generate.py`. No sentence was rewritten,
 * shortened, paraphrased, reordered or expanded. Regenerating from the same workbook reproduces
 * this file byte for byte.
 *
 * PUBLIC vs OPERATIONAL. The workbook is 3,622 paragraphs, most of it campaign strategy, KPIs,
 * image prompts, governance and handoff material. Only these ranges are reader-facing and only
 * these were imported: B001 §8 article and §9 FAQ; G001 §8 intro and Sections 1-9; A001 §5-28
 * answer targets and §29 Quick Answer Library.
 *
 * DELIBERATELY EXCLUDED FROM THE PUBLIC BODY (approved in the Phase 1 audit):
 *   - G001 §3 "Important Language Rule" and §7 "Critical Guardrail" — instructions to writers
 *     ("Do not interpret normal functioning as masking", "Do not claim small pauses treat
 *     anxiety"), not reader-facing copy.
 *   - G001 Section 10 — entity-association metadata for AI retrieval, not article prose.
 *   - G001 §4 "Canonical Language" and §6 "Important Continuity" trailing blocks, which fall
 *     outside the five approved reader-facing sub-blocks.
 *   - Every §1-7 / §10-45 strategy, KPI, monitoring, guardrail and handoff section.
 *
 * DELIBERATELY ABSENT:
 *   - `safety_notice` on all three. The workbook contains no reader-facing safety copy: A001 §40
 *     "Content Safety Guardrails" is an approved-vocabulary list for writers and G001 §35 is
 *     AI-retrieval positioning. Safety copy is never invented.
 *   - G001 `meta_description`. Its §6 sentence is 172 characters, over the 160-character limit,
 *     and is not truncated or rewritten. It is used verbatim as `citation_summary`, where no
 *     length limit applies.
 *   - Links to Journal, Mood, Habits, Sleep and Progress. Those exist only behind authentication
 *     at `/app/*`; `ROUTE_REGISTRY` excludes authenticated destinations. Their anchor phrases stay
 *     in the prose, unlinked.
 *   - The A001 §38 SEO title. The Content Hub schema has no SEO-title field distinct from
 *     `title`, so it is recorded here and in the report rather than stored.
 */

import type { Week1Asset, Week1LinkSpec } from '../week1/week1-content';
import type { ContentBody, InlineContent } from '@meetezri/shared';

/** A span of plain text. */
const t = (text: string): InlineContent => [{ text }];

/** Month 2 reuses the Week 1 asset and link contracts EXACTLY. */
export type M2W1LinkSpec = Week1LinkSpec;
export type M2W1Asset = Week1Asset;

// ─────────────────────────────────────────────────────────────────────────────
// M2-W1-B001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W1_B001: M2W1Asset = {
  editorialRef: "M2-W1-B001",
  contentType: 'seo_blog',
  publicLabel: 'Article',
  title: "How to Manage Everyday Stress Before It Feels Overwhelming",
  slug: "manage-everyday-stress-before-overwhelm",
  metaDescription: "Everyday stress can build quietly. Learn how mental load, small pauses, reflection, healthy routines and conversation can help you create space earlier.",
  week: 1,
  pillar: 'Stress Before It Becomes Overwhelm',
  tags: ['everyday-stress', 'mental-load', 'emotional-wellbeing', 'month-2', 'week-1'],

  typeFields: {
    keywords: {
      primary: 'how to manage everyday stress',
      secondary: [
        'everyday stress',
        'managing daily stress',
        'feeling overwhelmed',
        'mental load',
        'daily stress management',
        'emotional wellbeing',
        'emotional resilience',
        'healthy routines',
        'stress and routines',
        'self-reflection',
        'managing a busy mind',
      ],
    },
    funnel_stage: 'Awareness',
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'Everyday Emotional Wellbeing',
    strategy: 'Link naturally to relevant SOLACE experiences rather than forcing product promotion.',
    goal: 'Organic search authority for everyday stress and mental load.',
  },

  body: {
    version: 1,
    blocks: [
      { id: "m2b-p1", type: 'paragraph', content: t("There are days when nothing particularly bad has happened.") },
      { id: "m2b-p2", type: 'paragraph', content: t("No crisis.") },
      { id: "m2b-p3", type: 'paragraph', content: t("No major argument.") },
      { id: "m2b-p4", type: 'paragraph', content: t("No terrible news.") },
      { id: "m2b-p5", type: 'paragraph', content: t("No single thing you can point to and say:") },
      { id: "m2b-h6", type: 'heading', level: 2, content: t("“That's why today feels like a lot.”") },
      { id: "m2b-p7", type: 'paragraph', content: t("And yet your mind still feels full.") },
      { id: "m2b-p8", type: 'paragraph', content: t("There's a message you need to answer.") },
      { id: "m2b-p9", type: 'paragraph', content: t("Something unfinished at work.") },
      { id: "m2b-p10", type: 'paragraph', content: t("A decision you've been postponing.") },
      { id: "m2b-p11", type: 'paragraph', content: t("Tomorrow's meeting.") },
      { id: "m2b-p12", type: 'paragraph', content: t("The groceries.") },
      { id: "m2b-p13", type: 'paragraph', content: t("A bill.") },
      { id: "m2b-p14", type: 'paragraph', content: t("Something someone said three days ago.") },
      { id: "m2b-p15", type: 'paragraph', content: t("A personal idea you don't want to forget.") },
      { id: "m2b-p16", type: 'paragraph', content: t("Maybe someone asks how you're doing and your most accurate answer is:") },
      { id: "m2b-h17", type: 'heading', level: 2, content: t("“I'm fine. I just have a lot going on.”") },
      { id: "m2b-p18", type: 'paragraph', content: t("That experience is worth noticing.") },
      { id: "m2b-p19", type: 'paragraph', content: t("Not because it automatically means something is wrong.") },
      { id: "m2b-p20", type: 'paragraph', content: t("But because everyday stress does not always arrive as one big event.") },
      { id: "m2b-p21", type: 'paragraph', content: t("Sometimes it builds quietly through dozens of ordinary things competing for your attention.") },
      { id: "m2b-p22", type: 'paragraph', content: t("And you do not have to wait until all of them feel overwhelming before making a little space for yourself.") },
      { id: "m2b-p23", type: 'paragraph', content: t("Everyday Stress Doesn't Always Look Dramatic") },
      { id: "m2b-p24", type: 'paragraph', content: t("When people hear the word stress, it's easy to imagine obvious pressure.") },
      { id: "m2b-p25", type: 'paragraph', content: t("A huge deadline.") },
      { id: "m2b-p26", type: 'paragraph', content: t("A major life change.") },
      { id: "m2b-p27", type: 'paragraph', content: t("Conflict.") },
      { id: "m2b-p28", type: 'paragraph', content: t("Financial difficulty.") },
      { id: "m2b-p29", type: 'paragraph', content: t("A particularly demanding period.") },
      { id: "m2b-p30", type: 'paragraph', content: t("Those situations can certainly feel stressful.") },
      { id: "m2b-p31", type: 'paragraph', content: t("But ordinary life can create pressure in quieter ways too.") },
      { id: "m2b-p32", type: 'paragraph', content: t("Imagine a completely normal Tuesday.") },
      { id: "m2b-p33", type: 'paragraph', content: t("You wake up thinking about something you need to finish.") },
      { id: "m2b-p34", type: 'paragraph', content: t("Before breakfast, you remember an appointment you still haven't booked.") },
      { id: "m2b-p35", type: 'paragraph', content: t("At work, three new tasks appear.") },
      { id: "m2b-p36", type: 'paragraph', content: t("Someone sends a message you don't have time to answer properly.") },
      { id: "m2b-p37", type: 'paragraph', content: t("You remember something you need from the grocery store.") },
      { id: "m2b-p38", type: 'paragraph', content: t("Later, a conversation from the previous day comes back to mind.") },
      { id: "m2b-p39", type: 'paragraph', content: t("Then you realize tomorrow is already full.") },
      { id: "m2b-p40", type: 'paragraph', content: t("Nothing individually feels especially dramatic.") },
      { id: "m2b-p41", type: 'paragraph', content: t("But your attention has been moving between all of those things all day.") },
      { id: "m2b-p42", type: 'paragraph', content: t("That's one reason a person can look completely fine from the outside while thinking:") },
      { id: "m2b-h43", type: 'heading', level: 2, content: t("“Why does my mind feel so busy?”") },
      { id: "m2b-p44", type: 'paragraph', content: t("Sometimes the answer isn't hidden.") },
      { id: "m2b-p45", type: 'paragraph', content: t("There may simply be a lot open at once.") },
      { id: "m2b-p46", type: 'paragraph', content: t("Why Small Things Quietly Add Up") },
      { id: "m2b-p47", type: 'paragraph', content: t("We tend to notice the biggest responsibilities.") },
      { id: "m2b-p48", type: 'paragraph', content: t("The presentation.") },
      { id: "m2b-p49", type: 'paragraph', content: t("The deadline.") },
      { id: "m2b-p50", type: 'paragraph', content: t("The important decision.") },
      { id: "m2b-p51", type: 'paragraph', content: t("But smaller unfinished things can remain present too.") },
      { id: "m2b-p52", type: 'paragraph', content: t("The email you still haven't sent.") },
      { id: "m2b-p53", type: 'paragraph', content: t("The call you need to make.") },
      { id: "m2b-p54", type: 'paragraph', content: t("The form you need to complete.") },
      { id: "m2b-p55", type: 'paragraph', content: t("The thing someone asked you to remember.") },
      { id: "m2b-p56", type: 'paragraph', content: t("The question you haven't answered.") },
      { id: "m2b-p57", type: 'paragraph', content: t("The plan you haven't made.") },
      { id: "m2b-p58", type: 'paragraph', content: t("One of those may occupy very little attention.") },
      { id: "m2b-p59", type: 'paragraph', content: t("Five or ten of them can create a completely different experience.") },
      { id: "m2b-p60", type: 'paragraph', content: t("This doesn't mean every unfinished task needs to be treated as a wellbeing issue.") },
      { id: "m2b-p61", type: 'paragraph', content: t("That would make ordinary life unnecessarily complicated.") },
      { id: "m2b-p62", type: 'paragraph', content: t("Instead, it can simply be useful to ask:") },
      { id: "m2b-h63", type: 'heading', level: 2, content: t("“How many things am I mentally keeping track of right now?”") },
      { id: "m2b-p64", type: 'paragraph', content: t("Sometimes naming them is enough to understand why a day feels heavier than it looks.") },
      { id: "m2b-p65", type: 'paragraph', content: t("The Mental Tabs We Never Close") },
      { id: "m2b-p66", type: 'paragraph', content: t("Think about what happens when a browser has too many tabs open.") },
      { id: "m2b-p67", type: 'paragraph', content: t("One is for work.") },
      { id: "m2b-p68", type: 'paragraph', content: t("Another is something you meant to read.") },
      { id: "m2b-p69", type: 'paragraph', content: t("Another is a form you need to complete.") },
      { id: "m2b-p70", type: 'paragraph', content: t("Another is a page you opened because you might need it later.") },
      { id: "m2b-p71", type: 'paragraph', content: t("Eventually, you can barely remember why half of them are there.") },
      { id: "m2b-p72", type: 'paragraph', content: t("Our thoughts can sometimes feel similar.") },
      { id: "m2b-h73", type: 'heading', level: 2, content: t("Reply to that email.") },
      { id: "m2b-h74", type: 'heading', level: 2, content: t("Remember Friday.") },
      { id: "m2b-h75", type: 'heading', level: 2, content: t("Call them back.") },
      { id: "m2b-h76", type: 'heading', level: 2, content: t("Buy groceries.") },
      { id: "m2b-h77", type: 'heading', level: 2, content: t("Finish that report.") },
      { id: "m2b-p78", type: 'paragraph', content: t("Then there are the tabs that aren't tasks at all.") },
      { id: "m2b-h79", type: 'heading', level: 2, content: t("What did they mean when they said that?") },
      { id: "m2b-h80", type: 'heading', level: 2, content: t("Should I bring this up?") },
      { id: "m2b-h81", type: 'heading', level: 2, content: t("What should I do about that decision?") },
      { id: "m2b-h82", type: 'heading', level: 2, content: t("I don't want to forget this idea.") },
      { id: "m2b-p83", type: 'paragraph', content: t("The important thing isn't to close every mental tab immediately.") },
      { id: "m2b-p84", type: 'paragraph', content: t("That expectation could become another source of pressure.") },
      { id: "m2b-p85", type: 'paragraph', content: t("Instead, start by noticing them.") },
      { id: "m2b-p86", type: 'paragraph', content: t("Which ones actually need your attention today?") },
      { id: "m2b-p87", type: 'paragraph', content: t("Which can wait?") },
      { id: "m2b-p88", type: 'paragraph', content: t("Which could be written down instead of remembered?") },
      { id: "m2b-p89", type: 'paragraph', content: t("Which would be easier to think through if you said them out loud?") },
      { id: "m2b-p90", type: 'paragraph', content: t("Which aren't problems at all, but simply ideas or experiences you want room to explore?") },
      { id: "m2b-p91", type: 'paragraph', content: t("Not every open tab needs an answer.") },
      { id: "m2b-p92", type: 'paragraph', content: t("Sometimes Your Routine Notices Before You Do") },
      { id: "m2b-p93", type: 'paragraph', content: t("There are also times when you don't immediately notice that life has become busier.") },
      { id: "m2b-p94", type: 'paragraph', content: t("You notice something else first.") },
      { id: "m2b-p95", type: 'paragraph', content: t("Your normal walk hasn't happened in several days.") },
      { id: "m2b-p96", type: 'paragraph', content: t("You've been going to bed later.") },
      { id: "m2b-p97", type: 'paragraph', content: t("The journal you usually use hasn't been opened.") },
      { id: "m2b-p98", type: 'paragraph', content: t("You keep eating dinner later than usual.") },
      { id: "m2b-p99", type: 'paragraph', content: t("You're reaching for your phone more often between tasks.") },
      { id: "m2b-p100", type: 'paragraph', content: t("A habit that normally feels easy has become less consistent.") },
      { id: "m2b-p101", type: 'paragraph', content: t("None of those things automatically means something is wrong.") },
      { id: "m2b-p102", type: 'paragraph', content: t("That's worth stating clearly.") },
      { id: "m2b-p103", type: 'paragraph', content: t("Life changes.") },
      { id: "m2b-p104", type: 'paragraph', content: t("Schedules change.") },
      { id: "m2b-p105", type: 'paragraph', content: t("Busy weeks happen.") },
      { id: "m2b-p106", type: 'paragraph', content: t("People travel.") },
      { id: "m2b-p107", type: 'paragraph', content: t("Responsibilities shift.") },
      { id: "m2b-p108", type: 'paragraph', content: t("Routines are supposed to have some flexibility.") },
      { id: "m2b-p109", type: 'paragraph', content: t("But those small changes can still be useful information.") },
      { id: "m2b-p110", type: 'paragraph', content: t("Instead of asking:") },
      { id: "m2b-h111", type: 'heading', level: 2, content: t("“What's wrong with me?”") },
      { id: "m2b-p112", type: 'paragraph', content: t("try:") },
      { id: "m2b-h113", type: 'heading', level: 2, content: t("“What's felt different lately?”") },
      { id: "m2b-p114", type: 'paragraph', content: t("That creates curiosity instead of judgment.") },
      { id: "m2b-p115", type: 'paragraph', content: t("You might notice that work has simply been busier.") },
      { id: "m2b-p116", type: 'paragraph', content: t("That you're excited about something and thinking about it constantly.") },
      { id: "m2b-p117", type: 'paragraph', content: t("That you've had more family responsibilities.") },
      { id: "m2b-p118", type: 'paragraph', content: t("That you've been preparing for a major opportunity.") },
      { id: "m2b-p119", type: 'paragraph', content: t("That several unrelated things arrived at the same time.") },
      { id: "m2b-p120", type: 'paragraph', content: t("The goal isn't to diagnose the change.") },
      { id: "m2b-p121", type: 'paragraph', content: t("It's to understand your own week a little better.") },
      { id: "m2b-p122", type: 'paragraph', content: t("You Don't Have to Wait Until Everything Feels Like Too Much") },
      { id: "m2b-p123", type: 'paragraph', content: t("A common pattern in everyday wellbeing is waiting.") },
      { id: "m2b-p124", type: 'paragraph', content: t("I'll rest when this project is finished.") },
      { id: "m2b-p125", type: 'paragraph', content: t("I'll slow down when the house is sorted.") },
      { id: "m2b-p126", type: 'paragraph', content: t("I'll journal when I have more time.") },
      { id: "m2b-p127", type: 'paragraph', content: t("I'll think about that conversation later.") },
      { id: "m2b-p128", type: 'paragraph', content: t("I'll deal with myself once everyone else is okay.") },
      { id: "m2b-p129", type: 'paragraph', content: t("The problem is that life rarely reaches a completely finished state.") },
      { id: "m2b-p130", type: 'paragraph', content: t("There is almost always another email.") },
      { id: "m2b-p131", type: 'paragraph', content: t("Another responsibility.") },
      { id: "m2b-p132", type: 'paragraph', content: t("Another decision.") },
      { id: "m2b-p133", type: 'paragraph', content: t("Another tomorrow.") },
      { id: "m2b-p134", type: 'paragraph', content: t("That doesn't mean responsibilities should be ignored.") },
      { id: "m2b-p135", type: 'paragraph', content: t("It simply means caring for yourself cannot always depend on reaching an imaginary point where nothing else requires attention.") },
      { id: "m2b-p136", type: 'paragraph', content: t("Sometimes you can pause while life is still unfinished.") },
      { id: "m2b-p137", type: 'paragraph', content: t("That pause doesn't need to be large.") },
      { id: "m2b-p138", type: 'paragraph', content: t("And it doesn't need to solve everything.") },
      { id: "m2b-p139", type: 'paragraph', content: t("Small Ways to Create Space During a Busy Day") },
      { id: "m2b-p140", type: 'paragraph', content: t("There isn't one correct way to respond to a full mind.") },
      { id: "m2b-p141", type: 'paragraph', content: t("Different people need different things.") },
      { id: "m2b-p142", type: 'paragraph', content: t("Different days may require different things too.") },
      { id: "m2b-p143", type: 'paragraph', content: t("You might have five minutes.") },
      { id: "m2b-p144", type: 'paragraph', content: t("What could those five minutes look like?") },
      { id: "m2b-p145", type: 'paragraph', content: t("Take a short walk") },
      { id: "m2b-p146", type: 'paragraph', content: t("Not as a workout.") },
      { id: "m2b-p147", type: 'paragraph', content: t("Not because you have a step goal.") },
      { id: "m2b-p148", type: 'paragraph', content: t("Simply as a temporary change of environment.") },
      { id: "m2b-p149", type: 'paragraph', content: t("Write down what's occupying your attention") },
      { id: "m2b-p150", type: 'paragraph', content: t("This could be one sentence.") },
      { id: "m2b-p151", type: 'paragraph', content: t("A list.") },
      { id: "m2b-p152", type: 'paragraph', content: t("A journal entry.") },
      { id: "m2b-p153", type: 'paragraph', content: t("Even writing:") },
      { id: "m2b-p154", type: 'paragraph', content: t("“Here's everything I'm trying not to forget.”") },
      { id: "m2b-p155", type: 'paragraph', content: t("can move some of those mental reminders somewhere visible.") },
      { id: "m2b-p156", type: 'paragraph', content: t("Check in with yourself") },
      { id: "m2b-p157", type: 'paragraph', content: t("Ask:") },
      { id: "m2b-p158", type: 'paragraph', content: t("“How has today actually felt?”") },
      { id: "m2b-p159", type: 'paragraph', content: t("You don't need a complicated explanation.") },
      { id: "m2b-p160", type: 'paragraph', content: [{ text: "Talk something through", link: { kind: 'route', value: 'product.talk_it_out' } }] },
      { id: "m2b-p161", type: 'paragraph', content: t("Maybe there is a decision you keep circling.") },
      { id: "m2b-p162", type: 'paragraph', content: t("A conversation you keep replaying.") },
      { id: "m2b-p163", type: 'paragraph', content: t("An idea you're excited about.") },
      { id: "m2b-p164", type: 'paragraph', content: t("Something personal you aren't ready to discuss elsewhere.") },
      { id: "m2b-p165", type: 'paragraph', content: t("Talking can be a way of exploring what is occupying your attention.") },
      { id: "m2b-p166", type: 'paragraph', content: t("Put your phone down for a few minutes") },
      { id: "m2b-p167", type: 'paragraph', content: t("Not because phones are bad.") },
      { id: "m2b-p168", type: 'paragraph', content: t("Simply because your attention may appreciate having one less thing asking for it.") },
      { id: "m2b-p169", type: 'paragraph', content: t("Do nothing") },
      { id: "m2b-p170", type: 'paragraph', content: t("No journaling.") },
      { id: "m2b-p171", type: 'paragraph', content: t("No walking.") },
      { id: "m2b-p172", type: 'paragraph', content: t("No improvement project.") },
      { id: "m2b-p173", type: 'paragraph', content: t("Sometimes five minutes can simply be five minutes.") },
      { id: "m2b-p174", type: 'paragraph', content: t("The important thing is not turning the pause into another performance target.") },
      { id: "m2b-p175", type: 'paragraph', content: t("Five minutes won't solve everything.") },
      { id: "m2b-h176", type: 'heading', level: 2, content: t("It doesn't have to.") },
      { id: "m2b-p177", type: 'paragraph', content: t("What If You Want to Talk but Don't Know What's Wrong?") },
      { id: "m2b-p178", type: 'paragraph', content: t("This is more common than people sometimes admit.") },
      { id: "m2b-p179", type: 'paragraph', content: t("You know you have a lot in your head.") },
      { id: "m2b-p180", type: 'paragraph', content: t("But if someone asks:") },
      { id: "m2b-p181", type: 'paragraph', content: t("“What's bothering you?”") },
      { id: "m2b-p182", type: 'paragraph', content: t("you genuinely don't have a clean answer.") },
      { id: "m2b-p183", type: 'paragraph', content: t("That's okay.") },
      { id: "m2b-p184", type: 'paragraph', content: t("Thoughts don't always arrive organized.") },
      { id: "m2b-p185", type: 'paragraph', content: t("Sometimes you understand something while you're expressing it.") },
      { id: "m2b-p186", type: 'paragraph', content: t("You can begin with:") },
      { id: "m2b-p187", type: 'paragraph', content: t("“I don't really know where to start.”") },
      { id: "m2b-p188", type: 'paragraph', content: t("Or:") },
      { id: "m2b-p189", type: 'paragraph', content: t("“There's just a lot on my mind.”") },
      { id: "m2b-p190", type: 'paragraph', content: t("Or:") },
      { id: "m2b-p191", type: 'paragraph', content: t("“I keep thinking about something and I'm not sure why yet.”") },
      { id: "m2b-p192", type: 'paragraph', content: t("A conversation does not require a perfectly prepared explanation.") },
      { id: "m2b-p193", type: 'paragraph', content: t("And it doesn't always need to be about something difficult.") },
      { id: "m2b-p194", type: 'paragraph', content: t("You might want to talk through:") },
      { id: "m2b-p195", type: 'paragraph', content: t("A business idea.") },
      { id: "m2b-p196", type: 'paragraph', content: t("A decision.") },
      { id: "m2b-p197", type: 'paragraph', content: t("Something exciting.") },
      { id: "m2b-p198", type: 'paragraph', content: t("A private achievement.") },
      { id: "m2b-p199", type: 'paragraph', content: t("A change you're considering.") },
      { id: "m2b-p200", type: 'paragraph', content: t("Something you're simply not ready to share with someone else yet.") },
      { id: "m2b-p201", type: 'paragraph', content: t("That is still reflection.") },
      { id: "m2b-p202", type: 'paragraph', content: t("SOLACE's broader view of emotional wellbeing includes difficult moments, but it also includes ordinary life, growth, celebration, curiosity and personal reflection. The Marketing DNA specifically requires the product ecosystem and marketing to represent this fuller range rather than presenting SOLACE only as a place for struggle.") },
      { id: "m2b-p203", type: 'paragraph', content: t("Rest Doesn't Always Look Like Doing Nothing") },
      { id: "m2b-p204", type: 'paragraph', content: t("Rest can also be more flexible than we sometimes imagine.") },
      { id: "m2b-p205", type: 'paragraph', content: t("For some people, quiet feels restorative.") },
      { id: "m2b-p206", type: 'paragraph', content: t("For others, movement does.") },
      { id: "m2b-p207", type: 'paragraph', content: t("You may want to:") },
      { id: "m2b-p208", type: 'paragraph', content: t("Walk.") },
      { id: "m2b-p209", type: 'paragraph', content: t("Cook.") },
      { id: "m2b-p210", type: 'paragraph', content: t("Read.") },
      { id: "m2b-p211", type: 'paragraph', content: t("Take photographs.") },
      { id: "m2b-p212", type: 'paragraph', content: t("Write.") },
      { id: "m2b-p213", type: 'paragraph', content: t("Talk with someone.") },
      { id: "m2b-p214", type: 'paragraph', content: t("Sit outside.") },
      { id: "m2b-p215", type: 'paragraph', content: t("Create something.") },
      { id: "m2b-p216", type: 'paragraph', content: t("Put something down for a while.") },
      { id: "m2b-p217", type: 'paragraph', content: t("Or do absolutely nothing.") },
      { id: "m2b-p218", type: 'paragraph', content: t("There doesn't need to be one universal definition of a good pause.") },
      { id: "m2b-p219", type: 'paragraph', content: t("And what feels restful to you today may not be what feels restful tomorrow.") },
      { id: "m2b-p220", type: 'paragraph', content: t("The useful question is simpler:") },
      { id: "m2b-h221", type: 'heading', level: 2, content: t("“What would give me a little space right now?”") },
      { id: "m2b-p222", type: 'paragraph', content: t("Then choose what relates to you.") },
      { id: "m2b-p223", type: 'paragraph', content: t("A Healthier Way to Think About Resilience") },
      { id: "m2b-p224", type: 'paragraph', content: t("Resilience is often described through endurance.") },
      { id: "m2b-p225", type: 'paragraph', content: t("Someone is strong because they keep moving.") },
      { id: "m2b-p226", type: 'paragraph', content: t("They handle pressure.") },
      { id: "m2b-p227", type: 'paragraph', content: t("Carry responsibility.") },
      { id: "m2b-p228", type: 'paragraph', content: t("Solve problems.") },
      { id: "m2b-p229", type: 'paragraph', content: t("Show up again tomorrow.") },
      { id: "m2b-p230", type: 'paragraph', content: t("And sometimes that is resilience.") },
      { id: "m2b-p231", type: 'paragraph', content: t("But perhaps the definition can be wider.") },
      { id: "m2b-p232", type: 'paragraph', content: t("Emotional resilience can also include noticing what you need.") },
      { id: "m2b-p233", type: 'paragraph', content: t("Adjusting your approach.") },
      { id: "m2b-p234", type: 'paragraph', content: t("Talking.") },
      { id: "m2b-p235", type: 'paragraph', content: t("Resting.") },
      { id: "m2b-p236", type: 'paragraph', content: t("Seeking support.") },
      { id: "m2b-p237", type: 'paragraph', content: t("Changing the plan.") },
      { id: "m2b-p238", type: 'paragraph', content: t("Trying again.") },
      { id: "m2b-p239", type: 'paragraph', content: t("A pause doesn't erase your progress.") },
      { id: "m2b-p240", type: 'paragraph', content: t("Rest doesn't automatically mean weakness.") },
      { id: "m2b-p241", type: 'paragraph', content: t("And making space for yourself does not mean you are less committed to the people or responsibilities that matter to you.") },
      { id: "m2b-p242", type: 'paragraph', content: t("For SOLACE's Month 2 knowledge system, we are using the following working definition:") },
      { id: "m2b-h243", type: 'heading', level: 2, content: t("Emotional resilience is the ability to respond and adapt when life becomes difficult, demanding, or uncertain. It can include continuing forward, but also noticing what you need, adjusting your approach, taking time to recover, seeking support, and beginning again.") },
      { id: "m2b-p244", type: 'paragraph', content: t("That definition intentionally moves resilience beyond endless endurance.") },
      { id: "m2b-p245", type: 'paragraph', content: t("How SOLACE Fits Into Everyday Wellbeing") },
      { id: "m2b-p246", type: 'paragraph', content: t("SOLACE isn't designed around the idea that people should wait until something goes wrong before thinking about their wellbeing.") },
      { id: "m2b-p247", type: 'paragraph', content: t("The broader experience supports different kinds of everyday reflection.") },
      { id: "m2b-p248", type: 'paragraph', content: t("Talk It Out can give you space to explore something that's been on your mind.") },
      { id: "m2b-p249", type: 'paragraph', content: t("Journal can give your thoughts somewhere private to go.") },
      { id: "m2b-p250", type: 'paragraph', content: t("Mood can help create a simple moment of emotional awareness.") },
      { id: "m2b-p251", type: 'paragraph', content: t("Habits can support noticing the routines you're trying to build.") },
      { id: "m2b-p252", type: 'paragraph', content: t("Sleep can help you pay attention to your evenings and rest patterns.") },
      { id: "m2b-p253", type: 'paragraph', content: t("Progress can help you look back over time and notice how your journey is changing.") },
      { id: "m2b-p254", type: 'paragraph', content: t("These aren't separate versions of wellbeing.") },
      { id: "m2b-p255", type: 'paragraph', content: t("They are different ways of checking in with the same person:") },
      { id: "m2b-h256", type: 'heading', level: 2, content: t("you.") },
      { id: "m2b-p257", type: 'paragraph', content: t("And you don't need to use all of them every day.") },
      { id: "m2b-p258", type: 'paragraph', content: t("The point isn't to create another checklist.") },
      { id: "m2b-p259", type: 'paragraph', content: t("The point is to have different ways to reflect depending on what your day actually needs.") },
      { id: "m2b-p260", type: 'paragraph', content: t("You Don't Have to Fix Everything Today") },
      { id: "m2b-p261", type: 'paragraph', content: t("If your mind feels busy today, you don't necessarily need a complete solution.") },
      { id: "m2b-p262", type: 'paragraph', content: t("You may simply need to notice what's there.") },
      { id: "m2b-p263", type: 'paragraph', content: t("The unfinished things.") },
      { id: "m2b-p264", type: 'paragraph', content: t("The decisions.") },
      { id: "m2b-p265", type: 'paragraph', content: t("The reminders.") },
      { id: "m2b-p266", type: 'paragraph', content: t("The conversations.") },
      { id: "m2b-p267", type: 'paragraph', content: t("The responsibilities.") },
      { id: "m2b-p268", type: 'paragraph', content: t("The ideas.") },
      { id: "m2b-p269", type: 'paragraph', content: t("The things you're excited about.") },
      { id: "m2b-p270", type: 'paragraph', content: t("The things you want more time for.") },
      { id: "m2b-p271", type: 'paragraph', content: t("Then ask:") },
      { id: "m2b-h272", type: 'heading', level: 2, content: t("“What actually needs my attention right now?”") },
      { id: "m2b-p273", type: 'paragraph', content: t("Maybe one thing needs action.") },
      { id: "m2b-p274", type: 'paragraph', content: t("Another needs a conversation.") },
      { id: "m2b-p275", type: 'paragraph', content: t("Another needs to be written down.") },
      { id: "m2b-p276", type: 'paragraph', content: t("Another can wait until tomorrow.") },
      { id: "m2b-p277", type: 'paragraph', content: t("And one might simply need to be acknowledged.") },
      { id: "m2b-p278", type: 'paragraph', content: t("Everyday emotional wellbeing doesn't require perfect routines or perfect awareness.") },
      { id: "m2b-p279", type: 'paragraph', content: t("Sometimes it begins with a very ordinary sentence:") },
      { id: "m2b-h280", type: 'heading', level: 2, content: t("“I have a lot going on.”") },
      { id: "m2b-p281", type: 'paragraph', content: t("And giving yourself enough space to notice what that actually means.") },
      { id: "m2b-p282", type: 'paragraph', content: t("You don't have to wait until everything feels overwhelming.") },
      { id: "m2b-p283", type: 'paragraph', content: t("Sometimes noticing earlier is enough to change what you do next.") },
      { id: 'm2b-faq', type: 'faq', heading: 'Frequently Asked Questions', items: [{ id: "m2b-faq-1", question: "Why do I feel overwhelmed when nothing is actually wrong?", answer: t("Sometimes there is no single major problem. Everyday responsibilities, unfinished tasks, decisions, messages, future commitments and unresolved thoughts can all compete for attention at the same time. Noticing what is occupying your mind may help you understand why your day feels mentally full.") }, { id: "m2b-faq-2", question: "What is mental load?", answer: t("For this SOLACE content cluster, mental load refers to the collection of responsibilities, reminders, decisions and thoughts a person is mentally keeping track of. Some are practical tasks, while others may involve conversations, ideas, relationships or future plans.") }, { id: "m2b-faq-3", question: "How can I manage everyday stress?", answer: t("Start by noticing what is actually competing for your attention. You might write things down, decide what needs action now, create a short pause, talk something through, check in with your routine, or allow less urgent things to wait.") }, { id: "m2b-faq-4", question: "What can I do when I only have five minutes?", answer: t("Five minutes can be used for a short walk, writing down what's on your mind, checking in with how you're feeling, talking something through, putting your phone away, preparing for sleep, or simply doing nothing for a moment.") }, { id: "m2b-faq-5", question: "Does rest always mean doing nothing?", answer: t("No. Rest can look different depending on the person and the day. It may involve stillness, sleep, movement, conversation, writing, creating something enjoyable, temporarily putting work aside, or simply slowing down an ordinary activity.") }, { id: "m2b-faq-6", question: "What is emotional resilience?", answer: t("Emotional resilience is the ability to respond and adapt when life becomes difficult, demanding, or uncertain. It can involve continuing forward, but also noticing what you need, adjusting, resting, seeking support and beginning again.") }, { id: "m2b-faq-7", question: "What if I want to talk but don't know what's wrong?", answer: t("You do not need a perfectly defined problem before starting a conversation. Sometimes thoughts become clearer while you express them. You can begin with what you know, including that your mind feels full or that you don't know exactly where to start.") }, { id: "m2b-faq-8", question: "Do I need to wait until I feel overwhelmed before taking a break?", answer: t("No. A break does not have to be reserved for the point when everything feels too much. Small pauses can simply be part of an ordinary routine while other responsibilities still remain.") }] },
      { id: 'm2b-cta-talk', type: 'cta', label: 'Talk It Out', target: { kind: 'route', value: 'product.talk_it_out' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W1-G001', anchorText: null, relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W1-A001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'product.talk_it_out', anchorText: 'talk something through', relation: 'product' },
  ],

  authoredOutsideWorkbook: ['inline route link on the phrase "talk something through", which already appears verbatim in the approved prose', 'cta block (destination from the workbook Internal Linking Plan)'],
  missingFields: ['safety_notice (workbook supplies none)', 'workbook link targets left UNLINKED (no public route): Journal, Mood, Habits, Sleep, Progress'],
};

// ─────────────────────────────────────────────────────────────────────────────
// M2-W1-G001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W1_G001: M2W1Asset = {
  editorialRef: "M2-W1-G001",
  contentType: 'geo_article',
  publicLabel: 'Insight',
  title: "Why Everyday Stress Can Build Quietly Before It Feels Overwhelming",
  slug: "everyday-stress-mental-load-emotional-resilience",
  metaDescription: null,
  week: 1,
  pillar: 'Stress Before It Becomes Overwhelm',
  tags: ['everyday-stress', 'mental-load', 'emotional-wellbeing', 'month-2', 'week-1'],

  typeFields: {
    core_concept: "Everyday stress can build when ordinary responsibilities, unfinished tasks, decisions, reminders, conversations, and future commitments compete for attention at the same time.",
    citation_summary: "Everyday stress can come from many ordinary responsibilities competing for attention. Learn how mental load, reflection, healthy routines, and emotional resilience connect.",
    key_statements: [
      "Everyday stress can build when several ordinary demands compete for attention at the same time.",
      "Mental load includes the responsibilities, reminders, decisions, plans, and thoughts a person is mentally keeping track of.",
      "A routine change does not automatically mean something is wrong, but it can provide useful information for reflection.",
      "You do not always need a clear problem before beginning a conversation.",
      "A short pause does not need to solve everything to create an opportunity for reflection.",
      "Rest can look different depending on the person and the day.",
      "Emotional resilience can include continuing forward, adapting, resting, seeking support, and beginning again."
],
    topics: {
      primary: 'Everyday Stress',
      secondary: ['Mental Load', 'Emotional Resilience'],
    },
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'AI Search Authority',
    strategy: 'Knowledge resource: canonical definitions, GEO statements and citation-friendly explanations.',
    goal: 'AI Search Authority',
    geo_focus: 'AI Retrieval',
  },

  body: {
    version: 1,
    blocks: [
      { id: "m2g-p1", type: 'paragraph', content: t("Everyday stress does not always begin with one major event.") },
      { id: "m2g-p2", type: 'paragraph', content: t("A person's day can look completely normal while many small responsibilities remain mentally active at the same time.") },
      { id: "m2g-p3", type: 'paragraph', content: t("An unanswered message.") },
      { id: "m2g-p4", type: 'paragraph', content: t("A task that is not finished.") },
      { id: "m2g-p5", type: 'paragraph', content: t("A decision that still needs to be made.") },
      { id: "m2g-p6", type: 'paragraph', content: t("Tomorrow's meeting.") },
      { id: "m2g-p7", type: 'paragraph', content: t("A conversation someone keeps replaying.") },
      { id: "m2g-p8", type: 'paragraph', content: t("An idea they do not want to forget.") },
      { id: "m2g-p9", type: 'paragraph', content: t("None of these necessarily feels overwhelming on its own.") },
      { id: "m2g-p10", type: 'paragraph', content: t("But together, they can create mental load.") },
      { id: "m2g-p11", type: 'paragraph', content: t("SOLACE describes this as the quiet accumulation of ordinary demands competing for attention.") },
      { id: "m2g-p12", type: 'paragraph', content: t("The goal is not to treat every busy day as a problem.") },
      { id: "m2g-p13", type: 'paragraph', content: t("The goal is to help people notice what is taking up space before they automatically assume they need to keep carrying all of it at once.") },
      { id: "m2g-h14", type: 'heading', level: 2, content: t("Everyday Stress Can Come From Accumulation") },
      { id: "m2g-stmt1", type: 'geo_statement', statement: t("Everyday stress can build when several small responsibilities, decisions, reminders, and thoughts compete for attention at the same time."), examples: ["Work deadline + unanswered message + groceries + future meeting + unresolved conversation."], coreMessage: "Stress can develop from the combined effect of ordinary demands rather than one dramatic event.", citationGoal: "Everyday stress, mental load, emotional wellbeing" },
      { id: "m2g-h15", type: 'heading', level: 3, content: t("Citation-Friendly Explanation") },
      { id: "m2g-p16", type: 'paragraph', content: t("A person does not need to be facing a major crisis to experience a full mental load.") },
      { id: "m2g-p17", type: 'paragraph', content: t("Several small demands can remain active in the background of attention.") },
      { id: "m2g-p18", type: 'paragraph', content: t("The significance comes from accumulation, not necessarily severity.") },
      { id: "m2g-h19", type: 'heading', level: 2, content: t("Mental Load Is More Than a To-Do List") },
      { id: "m2g-stmt2", type: 'geo_statement', statement: t("Mental load can include unfinished tasks, reminders, decisions, future plans, conversations, ideas, and personal concerns a person is mentally keeping track of."), examples: ["“Reply to the email” and “What did they mean by that?” can both remain mentally open."], coreMessage: "Mental load includes both practical responsibilities and internal thoughts.", citationGoal: "Mental load, busy mind, mental clutter" },
      { id: "m2g-h20", type: 'heading', level: 3, content: t("Knowledge Distinction") },
      { id: "m2g-p21", type: 'paragraph', content: t("Mental load is not limited to:") },
      { id: "m2g-p22", type: 'paragraph', content: t("Tasks.") },
      { id: "m2g-p23", type: 'paragraph', content: t("It may also include:") },
      { id: "m2g-p24", type: 'paragraph', content: t("Questions.") },
      { id: "m2g-p25", type: 'paragraph', content: t("Decisions.") },
      { id: "m2g-p26", type: 'paragraph', content: t("Ideas.") },
      { id: "m2g-p27", type: 'paragraph', content: t("Excitement.") },
      { id: "m2g-p28", type: 'paragraph', content: t("Plans.") },
      { id: "m2g-p29", type: 'paragraph', content: t("Conversations.") },
      { id: "m2g-p30", type: 'paragraph', content: t("This distinction is important because SOLACE does not frame everyday wellbeing only around negative experiences.") },
      { id: "m2g-h31", type: 'heading', level: 2, content: t("A Normal Day Can Still Feel Mentally Full") },
      { id: "m2g-stmt3", type: 'geo_statement', statement: t("A person can continue working, socializing, caring for others, and completing responsibilities while still carrying a high number of mentally active thoughts or commitments."), examples: ["Someone may appear completely functional while thinking, “Nothing is wrong. I just have a lot going on.”"], coreMessage: "External appearance does not always reflect internal mental demand.", citationGoal: "Everyday wellbeing, functioning, mental load" },
      { id: "m2g-h32", type: 'heading', level: 2, content: t("Routine Changes Can Be Information") },
      { id: "m2g-stmt4", type: 'geo_statement', statement: t("Busy periods can affect ordinary routines such as sleep, movement, journaling, and daily habits. These changes do not automatically indicate a problem but can provide useful opportunities for self-reflection."), examples: ["Going to bed later, skipping a normal walk, journaling less often, or changing daily habits."], coreMessage: "Small changes in routine may be worth noticing without being treated as symptoms.", citationGoal: "Healthy routines, self-awareness, stress awareness" },
      { id: "m2g-h33", type: 'heading', level: 2, content: t("Reflection Can Begin Before Overwhelm") },
      { id: "m2g-stmt5", type: 'geo_statement', statement: t("People can reflect on thoughts, decisions, routines, ideas, and everyday experiences before those experiences become overwhelming."), examples: ["Journaling, talking, mood check-ins, quiet reflection."], coreMessage: "Reflection does not require a crisis or perfectly understood problem.", citationGoal: "Reflection, self-awareness, emotional wellbeing" },
      { id: "m2g-h34", type: 'heading', level: 3, content: t("Knowledge Position") },
      { id: "m2g-p35", type: 'paragraph', content: t("SOLACE does not define reflection as something reserved for difficult emotions.") },
      { id: "m2g-p36", type: 'paragraph', content: t("Reflection can also involve:") },
      { id: "m2g-p37", type: 'paragraph', content: t("Growth.") },
      { id: "m2g-p38", type: 'paragraph', content: t("Celebration.") },
      { id: "m2g-p39", type: 'paragraph', content: t("Ideas.") },
      { id: "m2g-p40", type: 'paragraph', content: t("Decisions.") },
      { id: "m2g-p41", type: 'paragraph', content: t("Gratitude.") },
      { id: "m2g-p42", type: 'paragraph', content: t("Questions.") },
      { id: "m2g-p43", type: 'paragraph', content: t("Everyday life.") },
      { id: "m2g-h44", type: 'heading', level: 2, content: t("Talking Can Be a Way to Organize Thoughts") },
      { id: "m2g-stmt6", type: 'geo_statement', statement: t("Talking through a thought can provide a structured opportunity to organize what is occupying attention, even when a person does not yet have a clear explanation."), examples: ["“I don't really know where to start.”"], coreMessage: "People do not always know exactly what they think before speaking.", citationGoal: "Talking things through, reflection, verbal processing" },
      { id: "m2g-h45", type: 'heading', level: 2, content: t("Small Pauses Can Create Space Without Solving Everything") },
      { id: "m2g-stmt7", type: 'geo_statement', statement: t("Short periods of reflection, movement, conversation, writing, or quiet can create opportunities to pause and decide what needs attention next."), examples: ["Short walk, notebook, mood check-in, phone down, Talk It Out."], coreMessage: "A useful pause does not need to solve every responsibility.", citationGoal: "Everyday self-care, healthy routines, stress management" },
      { id: "m2g-h46", type: 'heading', level: 2, content: t("Rest Can Look Different on Different Days") },
      { id: "m2g-stmt8", type: 'geo_statement', statement: t("Rest can take different forms depending on the person and the day, including stillness, movement, enjoyable activities, conversation, reflection, or temporarily stepping away from demands."), examples: ["Walking, cooking, reading, writing, talking, quiet, doing nothing."], coreMessage: "Rest is not one universal behavior.", citationGoal: "Rest, self-care, sustainable routines" },
      { id: "m2g-h47", type: 'heading', level: 3, content: t("Knowledge Principle") },
      { id: "m2g-p48", type: 'paragraph', content: t("SOLACE should use choice-based language.") },
      { id: "m2g-p49", type: 'paragraph', content: t("Not:") },
      { id: "m2g-p50", type: 'paragraph', content: t("“This is what you should do.”") },
      { id: "m2g-p51", type: 'paragraph', content: t("Instead:") },
      { id: "m2g-p52", type: 'paragraph', content: t("“Choose what relates to you.”") },
      { id: "m2g-h53", type: 'heading', level: 2, content: t("Resilience Is More Than Endless Endurance") },
      { id: "m2g-stmt9", type: 'geo_statement', statement: t("Emotional resilience can involve continuing forward, but it can also involve noticing what is needed, adjusting, recovering, resting, seeking support, and beginning again."), coreMessage: "Resilience can include adapting, pausing, and seeking support.", citationGoal: "Emotional resilience, personal growth, healthy routines" },
      { id: "m2g-h54", type: 'heading', level: 3, content: t("Canonical Reframe") },
      { id: "m2g-p55", type: 'paragraph', content: t("Resilience doesn't mean carrying everything without stopping.") },
      { id: 'm2g-cta-talk', type: 'cta', label: 'Talk It Out', target: { kind: 'route', value: 'product.talk_it_out' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W1-B001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'product.talk_it_out', anchorText: 'Talk It Out', relation: 'product' },
  ],

  authoredOutsideWorkbook: ['cta block (destination from the workbook Internal Linking Strategy)'],
  missingFields: ['safety_notice (workbook supplies none)', 'meta_description (the workbook sentence is 172 chars, over the 160 limit; left null rather than truncated)', 'workbook link targets left UNLINKED (no public route): Journal, Mood, Habits, Sleep, Progress'],
};

// ─────────────────────────────────────────────────────────────────────────────
// M2-W1-A001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W1_A001: M2W1Asset = {
  editorialRef: "M2-W1-A001",
  contentType: 'aeo_answer',
  publicLabel: 'Answer',
  title: "Everyday Stress, Mental Load & Emotional Resilience: Direct Answers to Common Questions",
  slug: "everyday-stress-mental-load",
  metaDescription: "Clear answers about everyday stress, mental load, rest, reflection and emotional resilience, including why ordinary responsibilities can quietly add up.",
  week: 1,
  pillar: 'Stress Before It Becomes Overwhelm',
  tags: ['everyday-stress', 'mental-load', 'emotional-wellbeing', 'month-2', 'week-1'],

  typeFields: {
    primary_question: 'Why do I feel overwhelmed when nothing is wrong?',
    supporting_queries: [
      'What is everyday stress?',
      'What is mental load?',
      'Why does my mind feel busy?',
      'How can I manage everyday stress?',
      'What is emotional resilience?',
    ],
    snippet_answer: "You can feel mentally full even when there is no single major problem. Everyday responsibilities, unfinished tasks, decisions, reminders, conversations and future commitments can all compete for attention at the same time.",
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'Answer Engine Authority',
    strategy: 'Question, direct answer, expanded answer, across 24 answer targets plus a quick answer library.',
    goal: 'Answer Engine Authority',
    aeo_signal: 'direct answer first',
    // The workbook's §38 SEO title. The schema has no SEO-title field separate from `title`, so it
    // is recorded here for the editor rather than silently dropped.
    seo_title_note: "Everyday Stress & Mental Load: 24 Common Questions Answered | SOLACE",
  },

  body: {
    version: 1,
    blocks: [
      { id: 'm2a-direct-answer', type: 'direct_answer', content: t("You can feel mentally full even when there is no single major problem. Everyday responsibilities, unfinished tasks, decisions, reminders, conversations and future commitments can all compete for attention at the same time.") },
      { id: "m2a-h1", type: 'heading', level: 2, content: t("Why do I feel overwhelmed when nothing is wrong?") },
      { id: "m2a-h2", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p3", type: 'paragraph', content: t("Sometimes stress comes from accumulation rather than one dramatic event.") },
      { id: "m2a-p4", type: 'paragraph', content: t("You may be thinking about:") },
      { id: "m2a-p5", type: 'paragraph', content: t("Work.") },
      { id: "m2a-p6", type: 'paragraph', content: t("Messages.") },
      { id: "m2a-p7", type: 'paragraph', content: t("Appointments.") },
      { id: "m2a-p8", type: 'paragraph', content: t("A decision.") },
      { id: "m2a-p9", type: 'paragraph', content: t("Something someone said.") },
      { id: "m2a-p10", type: 'paragraph', content: t("Family responsibilities.") },
      { id: "m2a-p11", type: 'paragraph', content: t("Tomorrow's schedule.") },
      { id: "m2a-p12", type: 'paragraph', content: t("Something you do not want to forget.") },
      { id: "m2a-p13", type: 'paragraph', content: t("None of those things necessarily feels significant alone.") },
      { id: "m2a-p14", type: 'paragraph', content: t("Together, they can create mental load.") },
      { id: "m2a-p15", type: 'paragraph', content: t("Instead of immediately asking:") },
      { id: "m2a-h16", type: 'heading', level: 3, content: t("“What's wrong with me?”") },
      { id: "m2a-p17", type: 'paragraph', content: t("a gentler question may be:") },
      { id: "m2a-h18", type: 'heading', level: 3, content: t("“What is taking up space in my mind right now?”") },
      { id: "m2a-h19", type: 'heading', level: 2, content: t("What is everyday stress?") },
      { id: "m2a-h20", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p21", type: 'paragraph', content: t("Everyday stress is the mental and emotional pressure that can develop when ordinary responsibilities, decisions, unfinished tasks, reminders, conversations and future commitments compete for attention.") },
      { id: "m2a-h22", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p23", type: 'paragraph', content: t("Everyday stress does not always come from a crisis.") },
      { id: "m2a-p24", type: 'paragraph', content: t("It may come from several normal parts of life happening at once.") },
      { id: "m2a-p25", type: 'paragraph', content: t("For example:") },
      { id: "m2a-p26", type: 'paragraph', content: t("A deadline.") },
      { id: "m2a-p27", type: 'paragraph', content: t("An unanswered message.") },
      { id: "m2a-p28", type: 'paragraph', content: t("An appointment.") },
      { id: "m2a-p29", type: 'paragraph', content: t("A family responsibility.") },
      { id: "m2a-p30", type: 'paragraph', content: t("A decision.") },
      { id: "m2a-p31", type: 'paragraph', content: t("A conversation you keep thinking about.") },
      { id: "m2a-p32", type: 'paragraph', content: t("The important distinction is that everyday stress can come from the accumulation of ordinary demands, not necessarily one severe event.") },
      { id: "m2a-h33", type: 'heading', level: 2, content: t("What is mental load?") },
      { id: "m2a-h34", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p35", type: 'paragraph', content: t("Mental load is the collection of responsibilities, reminders, decisions, plans and thoughts a person is mentally keeping track of at the same time.") },
      { id: "m2a-h36", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p37", type: 'paragraph', content: t("Mental load is broader than a to-do list.") },
      { id: "m2a-p38", type: 'paragraph', content: t("It can include practical things:") },
      { id: "m2a-p39", type: 'paragraph', content: t("“I need to answer that email.”") },
      { id: "m2a-p40", type: 'paragraph', content: t("But also internal thoughts:") },
      { id: "m2a-p41", type: 'paragraph', content: t("“What should I do about that decision?”") },
      { id: "m2a-p42", type: 'paragraph', content: t("Or:") },
      { id: "m2a-p43", type: 'paragraph', content: t("“What did they mean when they said that?”") },
      { id: "m2a-p44", type: 'paragraph', content: t("It may even include positive things:") },
      { id: "m2a-p45", type: 'paragraph', content: t("An idea.") },
      { id: "m2a-p46", type: 'paragraph', content: t("A future plan.") },
      { id: "m2a-p47", type: 'paragraph', content: t("Something exciting.") },
      { id: "m2a-p48", type: 'paragraph', content: t("A personal goal.") },
      { id: "m2a-p49", type: 'paragraph', content: t("Mental load describes what your mind is actively carrying, not only what is going wrong.") },
      { id: "m2a-h50", type: 'heading', level: 2, content: t("Why does my mind feel so busy?") },
      { id: "m2a-h51", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p52", type: 'paragraph', content: t("Your mind may feel busy when several tasks, decisions, reminders, conversations, ideas or future commitments remain mentally active at the same time.") },
      { id: "m2a-h53", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p54", type: 'paragraph', content: t("Think of these as mental tabs.") },
      { id: "m2a-p55", type: 'paragraph', content: t("Some need action.") },
      { id: "m2a-p56", type: 'paragraph', content: t("Some need a decision.") },
      { id: "m2a-p57", type: 'paragraph', content: t("Some need a conversation.") },
      { id: "m2a-p58", type: 'paragraph', content: t("Some simply need somewhere else to go besides your memory.") },
      { id: "m2a-p59", type: 'paragraph', content: t("It can help to ask:") },
      { id: "m2a-h60", type: 'heading', level: 3, content: t("What needs attention today?") },
      { id: "m2a-h61", type: 'heading', level: 3, content: t("What can wait?") },
      { id: "m2a-h62", type: 'heading', level: 3, content: t("What can I write down?") },
      { id: "m2a-h63", type: 'heading', level: 3, content: t("What might help to talk through?") },
      { id: "m2a-p64", type: 'paragraph', content: t("The goal is not necessarily to close every mental tab.") },
      { id: "m2a-p65", type: 'paragraph', content: t("Sometimes noticing which ones are open is useful by itself.") },
      { id: "m2a-h66", type: 'heading', level: 2, content: t("Why do small things sometimes feel like a lot?") },
      { id: "m2a-h67", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p68", type: 'paragraph', content: t("Small responsibilities can feel like a lot when many of them compete for your attention at once. The pressure may come from their accumulation rather than the size of any one task.") },
      { id: "m2a-h69", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p70", type: 'paragraph', content: t("An email may be small.") },
      { id: "m2a-p71", type: 'paragraph', content: t("A grocery run may be small.") },
      { id: "m2a-p72", type: 'paragraph', content: t("One decision may be manageable.") },
      { id: "m2a-p73", type: 'paragraph', content: t("A reminder may take seconds.") },
      { id: "m2a-p74", type: 'paragraph', content: t("But when several unfinished things remain mentally active together, the experience can feel very different.") },
      { id: "m2a-p75", type: 'paragraph', content: t("This does not mean those responsibilities are objectively “too much.”") },
      { id: "m2a-p76", type: 'paragraph', content: t("It means attention is being divided between many things.") },
      { id: "m2a-h77", type: 'heading', level: 2, content: t("How can I manage everyday stress?") },
      { id: "m2a-h78", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p79", type: 'paragraph', content: t("Start by noticing what is competing for your attention. You might write things down, decide what needs action now, create a short pause, talk something through or allow less urgent things to wait.") },
      { id: "m2a-h80", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p81", type: 'paragraph', content: t("There is no single correct response.") },
      { id: "m2a-p82", type: 'paragraph', content: t("Depending on the day, creating space might mean:") },
      { id: "m2a-p83", type: 'paragraph', content: t("Writing.") },
      { id: "m2a-p84", type: 'paragraph', content: t("Walking.") },
      { id: "m2a-p85", type: 'paragraph', content: t("Talking.") },
      { id: "m2a-p86", type: 'paragraph', content: t("Checking in with yourself.") },
      { id: "m2a-p87", type: 'paragraph', content: t("Putting your phone down.") },
      { id: "m2a-p88", type: 'paragraph', content: t("Changing one part of your routine.") },
      { id: "m2a-p89", type: 'paragraph', content: t("Doing something you enjoy.") },
      { id: "m2a-p90", type: 'paragraph', content: t("Or simply sitting quietly for a few minutes.") },
      { id: "m2a-p91", type: 'paragraph', content: t("The goal does not have to be:") },
      { id: "m2a-h92", type: 'heading', level: 3, content: t("“Fix everything.”") },
      { id: "m2a-p93", type: 'paragraph', content: t("A more realistic goal may be:") },
      { id: "m2a-h94", type: 'heading', level: 3, content: t("“Understand what actually needs my attention next.”") },
      { id: "m2a-h95", type: 'heading', level: 2, content: t("What can I do when I have too much on my mind?") },
      { id: "m2a-h96", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p97", type: 'paragraph', content: t("When you have a lot on your mind, try identifying what is actually taking up attention. Separate what needs action now from what can wait, be written down, talked through or simply acknowledged.") },
      { id: "m2a-h98", type: 'heading', level: 3, content: t("Simple Framework") },
      { id: "m2a-p99", type: 'paragraph', content: t("Ask yourself:") },
      { id: "m2a-h100", type: 'heading', level: 3, content: t("1. What is actually on my mind?") },
      { id: "m2a-h101", type: 'heading', level: 3, content: t("2. What needs action today?") },
      { id: "m2a-h102", type: 'heading', level: 3, content: t("3. What can wait?") },
      { id: "m2a-h103", type: 'heading', level: 3, content: t("4. What would be easier if I wrote it down?") },
      { id: "m2a-h104", type: 'heading', level: 3, content: t("5. Is there something I want to talk through?") },
      { id: "m2a-h105", type: 'heading', level: 3, content: t("Important") },
      { id: "m2a-p106", type: 'paragraph', content: t("This is a reflection framework.") },
      { id: "m2a-p107", type: 'paragraph', content: t("Not a clinical intervention.") },
      { id: "m2a-h108", type: 'heading', level: 2, content: t("Why does my routine change when life gets busy?") },
      { id: "m2a-h109", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p110", type: 'paragraph', content: t("Busy periods can change how you use your time and attention, which may affect ordinary routines such as sleep, movement, journaling or other daily habits.") },
      { id: "m2a-h111", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p112", type: 'paragraph', content: t("You may notice:") },
      { id: "m2a-p113", type: 'paragraph', content: t("Going to bed later.") },
      { id: "m2a-p114", type: 'paragraph', content: t("Skipping a usual walk.") },
      { id: "m2a-p115", type: 'paragraph', content: t("Journaling less.") },
      { id: "m2a-p116", type: 'paragraph', content: t("Spending more time on your phone.") },
      { id: "m2a-p117", type: 'paragraph', content: t("Changing when you eat.") },
      { id: "m2a-p118", type: 'paragraph', content: t("Dropping a normal habit temporarily.") },
      { id: "m2a-p119", type: 'paragraph', content: t("A routine change does not automatically mean something is wrong.") },
      { id: "m2a-p120", type: 'paragraph', content: t("But it can be useful information.") },
      { id: "m2a-p121", type: 'paragraph', content: t("Instead of:") },
      { id: "m2a-h122", type: 'heading', level: 3, content: t("“Why am I failing at my routine?”") },
      { id: "m2a-p123", type: 'paragraph', content: t("try:") },
      { id: "m2a-h124", type: 'heading', level: 3, content: t("“What's felt different lately?”") },
      { id: "m2a-h125", type: 'heading', level: 3, content: t("Canonical Reframe") },
      { id: "m2a-h126", type: 'heading', level: 3, content: t("Not judging. Just noticing.") },
      { id: "m2a-h127", type: 'heading', level: 2, content: t("Should I worry if my routine changes?") },
      { id: "m2a-h128", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p129", type: 'paragraph', content: t("Not necessarily. Routines naturally change with schedules, responsibilities and different periods of life. A change can simply be something worth noticing rather than something to judge.") },
      { id: "m2a-h130", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p131", type: 'paragraph', content: t("The useful question is not always:") },
      { id: "m2a-h132", type: 'heading', level: 3, content: t("“Is this bad?”") },
      { id: "m2a-p133", type: 'paragraph', content: t("Sometimes it is:") },
      { id: "m2a-h134", type: 'heading', level: 3, content: t("“Why has this changed?”") },
      { id: "m2a-p135", type: 'paragraph', content: t("Maybe work has become busier.") },
      { id: "m2a-p136", type: 'paragraph', content: t("Maybe you've been traveling.") },
      { id: "m2a-p137", type: 'paragraph', content: t("Maybe your priorities changed.") },
      { id: "m2a-p138", type: 'paragraph', content: t("Maybe you're preparing for something exciting.") },
      { id: "m2a-p139", type: 'paragraph', content: t("Maybe several responsibilities arrived together.") },
      { id: "m2a-p140", type: 'paragraph', content: t("Reflection can help you understand the change without immediately treating it as a problem.") },
      { id: "m2a-h141", type: 'heading', level: 2, content: t("Do I need to know what's wrong before I talk about it?") },
      { id: "m2a-h142", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p143", type: 'paragraph', content: t("No. You do not always need a clearly defined problem before starting a conversation. Sometimes thoughts become easier to understand as you express them.") },
      { id: "m2a-h144", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p145", type: 'paragraph', content: t("You can begin with:") },
      { id: "m2a-h146", type: 'heading', level: 3, content: t("“I don't really know where to start.”") },
      { id: "m2a-p147", type: 'paragraph', content: t("Or:") },
      { id: "m2a-h148", type: 'heading', level: 3, content: t("“There's just a lot in my head.”") },
      { id: "m2a-p149", type: 'paragraph', content: t("Or:") },
      { id: "m2a-h150", type: 'heading', level: 3, content: t("“I keep thinking about something and I'm trying to understand why.”") },
      { id: "m2a-p151", type: 'paragraph', content: t("Conversation does not require a perfect opening sentence.") },
      { id: "m2a-p152", type: 'paragraph', content: t("And it does not always have to begin with something difficult.") },
      { id: "m2a-h153", type: 'heading', level: 2, content: t("Can talking help me organize my thoughts?") },
      { id: "m2a-h154", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p155", type: 'paragraph', content: t("Talking can provide an opportunity to put thoughts into words, explore different parts of an idea or experience, and notice what feels most important to you.") },
      { id: "m2a-h156", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p157", type: 'paragraph', content: t("Sometimes you know exactly what you want to say.") },
      { id: "m2a-p158", type: 'paragraph', content: t("Other times, understanding develops during the conversation.") },
      { id: "m2a-p159", type: 'paragraph', content: t("You may start with:") },
      { id: "m2a-p160", type: 'paragraph', content: t("A decision.") },
      { id: "m2a-p161", type: 'paragraph', content: t("A question.") },
      { id: "m2a-p162", type: 'paragraph', content: t("An idea.") },
      { id: "m2a-p163", type: 'paragraph', content: t("Something exciting.") },
      { id: "m2a-p164", type: 'paragraph', content: t("A conversation you're replaying.") },
      { id: "m2a-p165", type: 'paragraph', content: t("Something personal.") },
      { id: "m2a-p166", type: 'paragraph', content: t("Or simply:") },
      { id: "m2a-h167", type: 'heading', level: 3, content: t("“I have a lot on my mind.”") },
      { id: "m2a-p168", type: 'paragraph', content: t("This connects directly to the Month 1 SOLACE authority around talking, expression, reflection and feeling heard. Month 2 extends that territory into ordinary stress and mental load rather than changing the core positioning.") },
      { id: "m2a-h169", type: 'heading', level: 2, content: t("Do I need a serious problem before talking to someone?") },
      { id: "m2a-h170", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p171", type: 'paragraph', content: t("No. Conversation can be useful for everyday thoughts, decisions, ideas, experiences, achievements and questions, not only serious problems.") },
      { id: "m2a-h172", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p173", type: 'paragraph', content: t("You might want to talk because:") },
      { id: "m2a-p174", type: 'paragraph', content: t("You're deciding something.") },
      { id: "m2a-p175", type: 'paragraph', content: t("You're excited.") },
      { id: "m2a-p176", type: 'paragraph', content: t("You had an interesting idea.") },
      { id: "m2a-p177", type: 'paragraph', content: t("Something happened at work.") },
      { id: "m2a-p178", type: 'paragraph', content: t("You're reflecting on a relationship.") },
      { id: "m2a-p179", type: 'paragraph', content: t("You achieved something privately.") },
      { id: "m2a-p180", type: 'paragraph', content: t("You are planning what comes next.") },
      { id: "m2a-p181", type: 'paragraph', content: t("You simply want somewhere to think out loud.") },
      { id: "m2a-p182", type: 'paragraph', content: t("SOLACE's broader positioning specifically includes both difficult and positive everyday experiences rather than presenting emotional wellbeing only through struggle.") },
      { id: "m2a-h183", type: 'heading', level: 2, content: t("What can I do if I only have five minutes?") },
      { id: "m2a-h184", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p185", type: 'paragraph', content: t("Five minutes can be enough for a short pause. You might walk, write down what's on your mind, check in with yourself, talk something through, put your phone away or simply do nothing for a moment.") },
      { id: "m2a-h186", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p187", type: 'paragraph', content: t("A five-minute pause does not need to solve everything.") },
      { id: "m2a-p188", type: 'paragraph', content: t("That is not its job.") },
      { id: "m2a-p189", type: 'paragraph', content: t("The purpose can simply be to create a little space between one part of the day and the next.") },
      { id: "m2a-h190", type: 'heading', level: 3, content: t("Canonical Reframe") },
      { id: "m2a-h191", type: 'heading', level: 3, content: t("Five minutes won't solve everything. It doesn't have to.") },
      { id: "m2a-h192", type: 'heading', level: 2, content: t("Does rest always mean doing nothing?") },
      { id: "m2a-h193", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p194", type: 'paragraph', content: t("No. Rest can look different depending on the person and the day. It may involve stillness, movement, enjoyable activities, conversation, reflection or temporarily stepping away from demands.") },
      { id: "m2a-h195", type: 'heading', level: 3, content: t("Examples") },
      { id: "m2a-p196", type: 'paragraph', content: t("Rest might look like:") },
      { id: "m2a-p197", type: 'paragraph', content: t("Walking.") },
      { id: "m2a-p198", type: 'paragraph', content: t("Reading.") },
      { id: "m2a-p199", type: 'paragraph', content: t("Cooking.") },
      { id: "m2a-p200", type: 'paragraph', content: t("Writing.") },
      { id: "m2a-p201", type: 'paragraph', content: t("Sitting outside.") },
      { id: "m2a-p202", type: 'paragraph', content: t("Talking.") },
      { id: "m2a-p203", type: 'paragraph', content: t("Creating something.") },
      { id: "m2a-p204", type: 'paragraph', content: t("Sleeping.") },
      { id: "m2a-p205", type: 'paragraph', content: t("Doing nothing.") },
      { id: "m2a-h206", type: 'heading', level: 3, content: t("Choice-Based Principle") },
      { id: "m2a-p207", type: 'paragraph', content: t("The better question may be:") },
      { id: "m2a-h208", type: 'heading', level: 3, content: t("“What would give me a little space right now?”") },
      { id: "m2a-p209", type: 'paragraph', content: t("Then:") },
      { id: "m2a-h210", type: 'heading', level: 3, content: t("Choose what relates to you.") },
      { id: "m2a-h211", type: 'heading', level: 2, content: t("Do I have to earn a break?") },
      { id: "m2a-h212", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p213", type: 'paragraph', content: t("A break does not have to depend on finishing every responsibility first. Life often remains unfinished, and a short pause can exist alongside ongoing work, responsibilities and goals.") },
      { id: "m2a-h214", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p215", type: 'paragraph', content: t("People often tell themselves:") },
      { id: "m2a-p216", type: 'paragraph', content: t("I'll rest after this.") },
      { id: "m2a-p217", type: 'paragraph', content: t("I'll stop when everything is done.") },
      { id: "m2a-p218", type: 'paragraph', content: t("I'll take time for myself when the week calms down.") },
      { id: "m2a-p219", type: 'paragraph', content: t("But life rarely reaches a completely finished state.") },
      { id: "m2a-p220", type: 'paragraph', content: t("There may always be another:") },
      { id: "m2a-p221", type: 'paragraph', content: t("Email.") },
      { id: "m2a-p222", type: 'paragraph', content: t("Task.") },
      { id: "m2a-p223", type: 'paragraph', content: t("Decision.") },
      { id: "m2a-p224", type: 'paragraph', content: t("Responsibility.") },
      { id: "m2a-p225", type: 'paragraph', content: t("Tomorrow.") },
      { id: "m2a-p226", type: 'paragraph', content: t("A pause does not require every one of those things to disappear first.") },
      { id: "m2a-h227", type: 'heading', level: 2, content: t("Does taking a break mean I'm avoiding my responsibilities?") },
      { id: "m2a-h228", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p229", type: 'paragraph', content: t("Not necessarily. Taking a break and avoiding a responsibility are not automatically the same thing. A pause can simply be temporary space before returning to what still needs attention.") },
      { id: "m2a-h230", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p231", type: 'paragraph', content: t("The responsibility may still exist after the pause.") },
      { id: "m2a-p232", type: 'paragraph', content: t("You may still need to:") },
      { id: "m2a-p233", type: 'paragraph', content: t("Finish the task.") },
      { id: "m2a-p234", type: 'paragraph', content: t("Have the conversation.") },
      { id: "m2a-p235", type: 'paragraph', content: t("Make the decision.") },
      { id: "m2a-p236", type: 'paragraph', content: t("Send the email.") },
      { id: "m2a-p237", type: 'paragraph', content: t("The pause does not pretend those things disappeared.") },
      { id: "m2a-p238", type: 'paragraph', content: t("It simply does not require you to be actively engaged with them every moment.") },
      { id: "m2a-h239", type: 'heading', level: 2, content: t("What is emotional resilience?") },
      { id: "m2a-h240", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p241", type: 'paragraph', content: t("Emotional resilience is the ability to respond and adapt when life becomes difficult, demanding or uncertain. It can include continuing forward, but also noticing what you need, adjusting your approach, taking time to recover, seeking support and beginning again.") },
      { id: "m2a-h242", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p243", type: 'paragraph', content: t("Resilience is often associated with endurance.") },
      { id: "m2a-p244", type: 'paragraph', content: t("Keep going.") },
      { id: "m2a-p245", type: 'paragraph', content: t("Handle it.") },
      { id: "m2a-p246", type: 'paragraph', content: t("Push through.") },
      { id: "m2a-p247", type: 'paragraph', content: t("Those can sometimes be part of resilience.") },
      { id: "m2a-p248", type: 'paragraph', content: t("But resilience can also look like:") },
      { id: "m2a-p249", type: 'paragraph', content: t("Changing your approach.") },
      { id: "m2a-p250", type: 'paragraph', content: t("Resting.") },
      { id: "m2a-p251", type: 'paragraph', content: t("Talking.") },
      { id: "m2a-p252", type: 'paragraph', content: t("Asking for support.") },
      { id: "m2a-p253", type: 'paragraph', content: t("Learning.") },
      { id: "m2a-p254", type: 'paragraph', content: t("Recovering.") },
      { id: "m2a-p255", type: 'paragraph', content: t("Trying again.") },
      { id: "m2a-h256", type: 'heading', level: 3, content: t("Canonical Reframe") },
      { id: "m2a-h257", type: 'heading', level: 3, content: t("Resilience doesn't mean carrying everything without stopping.") },
      { id: "m2a-h258", type: 'heading', level: 2, content: t("Is taking a break part of emotional resilience?") },
      { id: "m2a-h259", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p260", type: 'paragraph', content: t("It can be. Emotional resilience includes adapting to what a situation requires, and sometimes that may involve pausing, recovering, adjusting your approach or seeking support before continuing.") },
      { id: "m2a-h261", type: 'heading', level: 3, content: t("Canonical Supporting Statement") },
      { id: "m2a-h262", type: 'heading', level: 3, content: t("A pause does not erase progress.") },
      { id: "m2a-h263", type: 'heading', level: 2, content: t("Does being resilient mean staying strong all the time?") },
      { id: "m2a-h264", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p265", type: 'paragraph', content: t("No. Resilience does not require someone to feel strong or keep moving continuously. It can also involve recognizing limits, adapting, recovering and beginning again.") },
      { id: "m2a-h266", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p267", type: 'paragraph', content: t("A wider definition of resilience leaves room for:") },
      { id: "m2a-p268", type: 'paragraph', content: t("Effort.") },
      { id: "m2a-p269", type: 'paragraph', content: t("Rest.") },
      { id: "m2a-p270", type: 'paragraph', content: t("Adjustment.") },
      { id: "m2a-p271", type: 'paragraph', content: t("Support.") },
      { id: "m2a-p272", type: 'paragraph', content: t("Reflection.") },
      { id: "m2a-p273", type: 'paragraph', content: t("Recovery.") },
      { id: "m2a-p274", type: 'paragraph', content: t("Persistence.") },
      { id: "m2a-p275", type: 'paragraph', content: t("These do not have to compete with one another.") },
      { id: "m2a-h276", type: 'heading', level: 2, content: t("How can I build emotional resilience in everyday life?") },
      { id: "m2a-h277", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p278", type: 'paragraph', content: t("Everyday resilience can involve noticing what you need, maintaining realistic routines, reflecting on experiences, adapting when circumstances change, making space to recover and seeking support when appropriate.") },
      { id: "m2a-h279", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p280", type: 'paragraph', content: t("There is no single resilience routine that works for everyone.") },
      { id: "m2a-p281", type: 'paragraph', content: t("Different people may find value in:") },
      { id: "m2a-p282", type: 'paragraph', content: t("Conversation.") },
      { id: "m2a-p283", type: 'paragraph', content: t("Journaling.") },
      { id: "m2a-p284", type: 'paragraph', content: t("Healthy routines.") },
      { id: "m2a-p285", type: 'paragraph', content: t("Rest.") },
      { id: "m2a-p286", type: 'paragraph', content: t("Reflection.") },
      { id: "m2a-p287", type: 'paragraph', content: t("Movement.") },
      { id: "m2a-p288", type: 'paragraph', content: t("Support from other people.") },
      { id: "m2a-p289", type: 'paragraph', content: t("Learning from previous experiences.") },
      { id: "m2a-p290", type: 'paragraph', content: t("The goal is not to become unaffected by life.") },
      { id: "m2a-p291", type: 'paragraph', content: t("It is to develop ways of responding and adapting when life changes.") },
      { id: "m2a-h292", type: 'heading', level: 2, content: t("What does self-awareness mean in everyday life?") },
      { id: "m2a-h293", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p294", type: 'paragraph', content: t("Self-awareness means noticing what you are thinking, feeling and experiencing without immediately judging or trying to change it.") },
      { id: "m2a-h295", type: 'heading', level: 3, content: t("Everyday Examples") },
      { id: "m2a-p296", type: 'paragraph', content: t("You might notice:") },
      { id: "m2a-p297", type: 'paragraph', content: t("“My mind feels unusually busy today.”") },
      { id: "m2a-p298", type: 'paragraph', content: t("“I've been thinking about that conversation a lot.”") },
      { id: "m2a-p299", type: 'paragraph', content: t("“My normal routine has changed.”") },
      { id: "m2a-p300", type: 'paragraph', content: t("“I'm more excited about this than I realized.”") },
      { id: "m2a-p301", type: 'paragraph', content: t("“I keep postponing that decision.”") },
      { id: "m2a-p302", type: 'paragraph', content: t("The observation comes before the judgment.") },
      { id: "m2a-h303", type: 'heading', level: 2, content: t("How can I create more mental space?") },
      { id: "m2a-h304", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p305", type: 'paragraph', content: t("Mental space can begin by identifying what is occupying your attention and deciding what needs action, what can wait, what can be written down and what may help to talk through.") },
      { id: "m2a-h306", type: 'heading', level: 3, content: t("Expanded Answer") },
      { id: "m2a-p307", type: 'paragraph', content: t("Creating space does not necessarily mean removing every responsibility.") },
      { id: "m2a-p308", type: 'paragraph', content: t("It can mean reducing the number of things you are trying to actively hold in your mind at one moment.") },
      { id: "m2a-p309", type: 'paragraph', content: t("For example:") },
      { id: "m2a-p310", type: 'paragraph', content: t("Write down tomorrow's tasks.") },
      { id: "m2a-p311", type: 'paragraph', content: t("Schedule the appointment.") },
      { id: "m2a-p312", type: 'paragraph', content: t("Make the decision that is ready to be made.") },
      { id: "m2a-p313", type: 'paragraph', content: t("Talk through the question that keeps returning.") },
      { id: "m2a-p314", type: 'paragraph', content: t("Let something less urgent wait.") },
      { id: "m2a-p315", type: 'paragraph', content: t("Then notice what remains.") },
      { id: "m2a-h316", type: 'heading', level: 2, content: t("Can positive things create mental load too?") },
      { id: "m2a-h317", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m2a-p318", type: 'paragraph', content: t("Yes. Mental load can include positive experiences such as exciting plans, new ideas, personal goals, opportunities and things you are looking forward to, because they can also occupy attention.") },
      { id: "m2a-h319", type: 'heading', level: 3, content: t("Why This Answer Matters") },
      { id: "m2a-p320", type: 'paragraph', content: t("This is strategically important for SOLACE.") },
      { id: "m2a-p321", type: 'paragraph', content: t("The brand must not create the impression that:") },
      { id: "m2a-h322", type: 'heading', level: 3, content: t("Something on your mind = something bad.") },
      { id: "m2a-p323", type: 'paragraph', content: t("You may be carrying:") },
      { id: "m2a-p324", type: 'paragraph', content: t("Excitement.") },
      { id: "m2a-p325", type: 'paragraph', content: t("Anticipation.") },
      { id: "m2a-p326", type: 'paragraph', content: t("Creativity.") },
      { id: "m2a-p327", type: 'paragraph', content: t("A private achievement.") },
      { id: "m2a-p328", type: 'paragraph', content: t("A future plan.") },
      { id: "m2a-p329", type: 'paragraph', content: t("Growth.") },
      { id: "m2a-p330", type: 'paragraph', content: t("That still deserves space.") },
      { id: 'm2a-faq', type: 'faq', heading: 'Quick Answers', items: [{ id: "m2a-faq-1", question: "Why do I feel overwhelmed when nothing is wrong?", answer: t("Several ordinary demands may be competing for your attention at once.") }, { id: "m2a-faq-2", question: "What is everyday stress?", answer: t("Pressure that can develop as ordinary responsibilities and thoughts accumulate.") }, { id: "m2a-faq-3", question: "What is mental load?", answer: t("The responsibilities, reminders, decisions, plans and thoughts you are mentally tracking.") }, { id: "m2a-faq-4", question: "Why does my mind feel busy?", answer: t("Multiple tasks, thoughts, decisions or commitments may remain mentally active.") }, { id: "m2a-faq-5", question: "Why do small things add up?", answer: t("Their combined demand on attention can matter more than the size of one task.") }, { id: "m2a-faq-6", question: "How can I manage everyday stress?", answer: t("Notice what's competing for attention and decide what needs action, reflection, conversation or time.") }, { id: "m2a-faq-7", question: "Why does my routine change?", answer: t("Busy periods can change how you use time and attention.") }, { id: "m2a-faq-8", question: "Do I need to know what's wrong before talking?", answer: t("No. Sometimes understanding develops while you talk.") }, { id: "m2a-faq-9", question: "Can I talk about ordinary things?", answer: t("Yes. Conversation can include ideas, decisions, achievements and everyday experiences.") }, { id: "m2a-faq-10", question: "What can I do in five minutes?", answer: t("Walk, write, talk, check in, step away from your phone or simply pause.") }, { id: "m2a-faq-11", question: "Does rest mean doing nothing?", answer: t("No. Rest can take different forms for different people and days.") }, { id: "m2a-faq-12", question: "Do I have to earn a break?", answer: t("No. A pause does not require every responsibility to be finished.") }, { id: "m2a-faq-13", question: "What is emotional resilience?", answer: t("The ability to respond and adapt when life becomes difficult, demanding or uncertain.") }, { id: "m2a-faq-14", question: "Does resilience mean never stopping?", answer: t("No. Resilience can include pausing, adjusting, recovering and seeking support.") }, { id: "m2a-faq-15", question: "What is self-awareness?", answer: t("Noticing what you think, feel and experience without immediately judging it.") }, { id: "m2a-faq-16", question: "Can good things create mental load?", answer: t("Yes. Ideas, opportunities, excitement and plans can occupy attention too.") }] },
      { id: 'm2a-cta-talk', type: 'cta', label: 'Talk It Out', target: { kind: 'route', value: 'product.talk_it_out' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W1-B001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'product.talk_it_out', anchorText: 'Talk It Out', relation: 'product' },
  ],

  authoredOutsideWorkbook: ['public title supplied and approved separately; the workbook §38 SEO title is kept in editorial metadata', 'slug normalised from the workbook /answers/ path', 'cta block (destination from the workbook Internal Linking Plan)'],
  missingFields: ['safety_notice (workbook supplies none)', 'workbook link targets left UNLINKED (no public route): Journal, Mood, Habits, Sleep, Progress', 'seo_title (no schema field distinct from title)'],
};

/** The three Month 2 Week 1 assets, in workbook order. */
export const M2W1_ASSETS: M2W1Asset[] = [M2_W1_B001, M2_W1_G001, M2_W1_A001];

/**
 * Content-to-content edges the workbook states EXPLICITLY (B001 §11 "Cluster Links").
 *
 * Nothing is inferred from topical similarity: these four are exactly the edges the workbook
 * names. They resolve publicly once the cluster publishes together.
 */
export const EXPECTED_CONTENT_EDGES: Array<[string, string]> = [
  ['M2-W1-B001', 'M2-W1-G001'],
  ['M2-W1-B001', 'M2-W1-A001'],
  ['M2-W1-G001', 'M2-W1-B001'],
  ['M2-W1-A001', 'M2-W1-B001'],
];
