import { AdminLayoutNew } from "../../components/AdminLayoutNew";
import { Card } from "../../components/ui/card";
import { Button } from "../../components/ui/button";
import { StatsCard } from "../../components/StatsCard";
import { motion } from "motion/react";
import { Download, TrendingUp, Users, Clock, Activity } from "lucide-react";
import { LineChart, Line, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";

export function ReportsAnalytics() {
  const userData = [
    { month: "Jan", users: 8423, active: 6234 },
    { month: "Feb", users: 9156, active: 6892 },
    { month: "Mar", users: 10234, active: 7654 },
    { month: "Apr", users: 11456, active: 8234 },
    { month: "May", users: 12459, active: 9123 },
  ];

  const engagementData = [
    { week: "Week 1", engagement: 72 },
    { week: "Week 2", engagement: 75 },
    { week: "Week 3", engagement: 78 },
    { week: "Week 4", engagement: 81 },
  ];

  // Function to handle PDF download
  const handleDownloadPDF = (reportName: string) => {
    // Create a simple PDF-like text content
    const reportContent = `
EZRI MENTAL HEALTH & WELLNESS PLATFORM
${reportName}
Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}

========================================

EXECUTIVE SUMMARY
${reportName === "User Activity Report" ? `
Total Active Users: 12,459
Monthly Growth: +8.8%
Average Session Duration: 18 minutes
Peak Activity Hours: 6-10 PM

TOP FEATURES USED:
1. AI Therapy Sessions - 95% adoption
2. Mood Tracking - 89% adoption
3. Journaling - 72% adoption
4. Wellness Tools - 68% adoption

USER ENGAGEMENT METRICS:
- Daily Active Users: 8,234
- Weekly Active Users: 10,987
- Monthly Active Users: 12,459
- Average Sessions per User: 4.8/week
` : reportName === "Financial Report" ? `
REVENUE OVERVIEW:
Total Revenue (This Month): $286,450
Monthly Recurring Revenue (MRR): $274,280
Year-over-Year Growth: +34.5%

59→SUBSCRIPTION BREAKDOWN:
60→- Trial: 2,340 users (18.8%)
61→- Core ($25/mo): 5,680 users (45.6%)
62→- Pro ($59/mo): 4,439 users (35.6%)

KEY METRICS:
- Average Revenue Per User (ARPU): $23.50
- Customer Lifetime Value: $1,380
- Churn Rate: 4.8%
- Customer Acquisition Cost: $42
` : reportName === "Crisis Intervention Report" ? `
CRISIS RESPONSE METRICS:
Total Crisis Alerts: 142
Average Response Time: 4.2 minutes
Escalated Cases: 28 (19.7%)
Successfully Resolved: 138 (97.2%)

SEVERITY BREAKDOWN:
- High Risk: 28 alerts (19.7%)
- Medium Risk: 67 alerts (47.2%)
- Low Risk: 47 alerts (33.1%)

RESPONSE TEAM PERFORMANCE:
- Average Contact Time: 2.8 minutes
- Follow-up Completion Rate: 94.4%
- Professional Referrals: 34 cases
- Emergency Services Contacted: 6 cases

TREND ANALYSIS:
- Week-over-Week Change: -12.3%
- Peak Crisis Times: 10 PM - 2 AM
- Most Common Triggers: Anxiety (42%), Depression (31%)
` : `
AI SESSION ANALYTICS:
Total Sessions: 48,420
Average Session Length: 18.3 minutes
User Satisfaction: 4.8/5.0
Completion Rate: 92.4%

SESSION BREAKDOWN BY AVATAR:
- Dr. Sarah Chen: 34% (16,463 sessions)
- Dr. Marcus Reid: 28% (13,558 sessions)
- Dr. Emma Torres: 23% (11,137 sessions)
- Dr. James Wilson: 15% (7,262 sessions)

USAGE PATTERNS:
- Peak Hours: 6-10 PM (42% of sessions)
- Average Sessions per User: 3.9/week
- Return Rate (7 days): 76%
- New User Adoption: 87%

THERAPEUTIC OUTCOMES:
- Mood Improvement: +23% average
- Anxiety Reduction: +31% average
- User Progress Tracking: 85% active
`}

DETAILED ANALYTICS:
[Additional detailed metrics and insights would appear here in a production report]

========================================
Report Generated by Ezri Admin Dashboard
For internal use only - Confidential
========================================
`;

    // Create a Blob from the content
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    
    // Create a temporary link and trigger download
    const link = document.createElement('a');
    link.href = url;
    link.download = `${reportName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    
    // Cleanup
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  return (
    <AdminLayoutNew>
      <div className="space-y-6">
        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}>
          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-3xl font-bold mb-2">Reports & Analytics</h1>
              <p className="text-muted-foreground">
                Comprehensive platform insights and data exports
              </p>
            </div>
            <Button className="gap-2">
              <Download className="w-4 h-4" />
              Export All Reports
            </Button>
          </div>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <StatsCard
            title="Total Revenue"
            value="$284,459"
            change="+18.2%"
            changeType="positive"
            icon={TrendingUp}
            color="success"
            delay={0}
          />
          <StatsCard
            title="Paying Users"
            value="8,234"
            change="+12.5%"
            changeType="positive"
            icon={Users}
            color="primary"
            delay={0.1}
          />
          <StatsCard
            title="Avg Session Time"
            value="42 min"
            change="+5 min"
            changeType="positive"
            icon={Clock}
            color="secondary"
            delay={0.2}
          />
          <StatsCard
            title="User Engagement"
            value="81%"
            change="+9%"
            changeType="positive"
            icon={Activity}
            color="accent"
            delay={0.3}
          />
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4 }}
          >
            <Card className="p-6">
              <h2 className="text-xl font-bold mb-6">User Growth (5 Months)</h2>
              <ResponsiveContainer width="100%" height={300}>
                <AreaChart data={userData}>
                  <defs>
                    <linearGradient id="colorUsers" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#9b87f5" stopOpacity={0.3} />
                      <stop offset="95%" stopColor="#9b87f5" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                  <XAxis dataKey="month" stroke="#6b7280" />
                  <YAxis stroke="#6b7280" />
                  <Tooltip />
                  <Area
                    type="monotone"
                    dataKey="users"
                    stroke="#9b87f5"
                    fillOpacity={1}
                    fill="url(#colorUsers)"
                  />
                </AreaChart>
              </ResponsiveContainer>
            </Card>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.5 }}
          >
            <Card className="p-6">
              <h2 className="text-xl font-bold mb-6">User Engagement Rate</h2>
              <ResponsiveContainer width="100%" height={300}>
                <LineChart data={engagementData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                  <XAxis dataKey="week" stroke="#6b7280" />
                  <YAxis stroke="#6b7280" />
                  <Tooltip />
                  <Line
                    type="monotone"
                    dataKey="engagement"
                    stroke="#7c3aed"
                    strokeWidth={3}
                    dot={{ fill: "#7c3aed", r: 6 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </Card>
          </motion.div>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
        >
          <Card className="p-6">
            <h2 className="text-xl font-bold mb-4">Available Reports</h2>
            <div className="grid md:grid-cols-2 gap-4">
              {[
                { name: "User Activity Report", description: "Detailed user engagement metrics" },
                { name: "Financial Report", description: "Revenue and subscription data" },
                { name: "Crisis Intervention Report", description: "Crisis events and response times" },
                { name: "Session Analytics Report", description: "AI session metrics and trends" },
              ].map((report, index) => (
                <div
                  key={index}
                  className="p-4 border border-gray-200 rounded-lg hover:border-primary transition-colors"
                >
                  <h3 className="font-bold mb-1">{report.name}</h3>
                  <p className="text-sm text-muted-foreground mb-3">{report.description}</p>
                  <Button variant="outline" size="sm" className="gap-2" onClick={() => handleDownloadPDF(report.name)}>
                    <Download className="w-4 h-4" />
                    Download PDF
                  </Button>
                </div>
              ))}
            </div>
          </Card>
        </motion.div>
      </div>
    </AdminLayoutNew>
  );
}