/**
 * Month 2 Week 4 workbook -> Content Hub mapping.
 *
 * SOURCE: `Month 2 Week 4 Operational Workbookqqq.docx`. Weekly theme "Tell Me Yours" — replaying
 * conversations, everyday reflection and communication.
 *
 * ============================================================================
 * EVERY STRING OF PROSE BELOW IS THE WORKBOOK\'S OWN WORDING.
 * ============================================================================
 *
 * Transcribed mechanically by `scripts/content-hub/m2w4-generate.py`. Regenerating from the same
 * workbook reproduces this file byte for byte.
 *
 * EDITORIAL REFS. These are `M2-W4-*`. The bare `W4-*` refs belong to published Month 1 Week 4
 * content ("small daily habits vs motivation") and are untouched by this module.
 *
 * SCAFFOLDING. Writer instructions that sit inside otherwise public ranges ("Suggested copy:",
 * "Mandatory section.", "Do not imply a formal therapeutic process.", "This safety section is
 * essential.", "Place near top:", …) are excluded BY LINE NUMBER and each exclusion is asserted
 * against its expected text. Two borderline lines — "The important distinction:" (744) and
 * "Important distinction:" (809) — are PRESERVED: both introduce, in the reader\'s own voice, the
 * distinction stated immediately after them.
 *
 * G001 PART 27 stays ordinary body content. "What Replaying a Conversation Does Not Automatically
 * Mean" is topical reassurance written for the reader, not a crisis or disclaimer notice, and the
 * `safety_notice` block is used across published content for crisis/disclaimer copy only.
 *
 * DELIBERATELY ABSENT:
 *   - `safety_notice` on all three. The workbook supplies no approved crisis/disclaimer copy, and
 *     its BRAND & SAFETY GUARDRAILS sections are Must/Must-Not instructions for writers. No empty
 *     placeholder is manufactured to clear the publish check.
 *   - G001 `meta_description`. The workbook value is 172 characters, over the 160 limit. Left null
 *     rather than truncated or rewritten; the original is preserved in editorial notes.
 *   - G001 `key_statements`. The workbook has no Key Statements section anywhere — the single
 *     "Key Statement" in the document belongs to B001, which is an seo_blog and requires none.
 *   - Links to Journal and Mood/Progress/Sleep/Habits, which have no registered public route, and
 *     to M2-W4-L001, which has no Content Hub record.
 */

import type { Week1Asset, Week1LinkSpec } from '../week1/week1-content';
import type { ContentBody, InlineContent } from '@meetezri/shared';

/** A span of plain text. */
const t = (text: string): InlineContent => [{ text }];

/** Month 2 Week 4 reuses the Week 1 asset and link contracts EXACTLY. */
export type M2W4LinkSpec = Week1LinkSpec;
export type M2W4Asset = Week1Asset;

// ─────────────────────────────────────────────────────────────────────────────
// M2-W4-B001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W4_B001: M2W4Asset = {
  editorialRef: "M2-W4-B001",
  contentType: 'seo_blog',
  publicLabel: 'Article',
  title: "Why Do I Keep Replaying Conversations in My Head?",
  slug: "why-do-i-keep-replaying-conversations-in-my-head",
  metaDescription: "Learn why conversations replay in your mind, what unfinished moments can mean, and how reflection helps you understand what keeps returning afterward.",
  week: 4,
  pillar: 'Everyday Wellbeing, Reflection, Communication and Self-Awareness',
  tags: ['replaying-conversations', 'everyday-reflection', 'communication', 'month-2', 'week-4'],

  typeFields: {
    keywords: { primary: "replaying conversations in my head" },
    funnel_stage: 'Search Discovery',
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'SEO Authority Blog — organic search discovery and search depth.',
    goal: 'Organic Search Traffic',
    search_intent: "Informational",
    search_intent_note: "The reader wants to understand why a conversation continues to occupy their attention after it has ended.",
    // The schema has no field distinct from `title`, so the approved SEO title is recorded here
    // rather than dropped.
    seo_title_note: "Why Do I Keep Replaying Conversations in My Head? | SOLACE",
    article_excerpt: "A conversation can end while part of your attention stays with it. Learn why certain words, questions, decisions and even positive moments can keep returning to your mind—and how reflection can help you understand what still feels unfinished.",
    key_statement: "A conversation may keep returning to your mind because something about it still feels meaningful, unfinished, uncertain, surprising or worth understanding.",
    supporting_search_phrases: "why do I replay conversationswhy do conversations stay in my headwhy do I keep thinking about what I saidreplaying a conversation after it happenedthinking about conversations afterwardwhy do work conversations stay on my mindwhy do I rehearse conversationsunfinished conversationseveryday reflectionself-reflection",
  },

  body: {
    version: 1,
    blocks: [
      { id: "m4b-p1", type: 'paragraph', content: t("The conversation ended hours ago.") },
      { id: "m4b-p2", type: 'paragraph', content: t("Maybe even days ago.") },
      { id: "m4b-p3", type: 'paragraph', content: t("But somehow, part of it is still with you.") },
      { id: "m4b-p4", type: 'paragraph', content: t("You remember something you said.") },
      { id: "m4b-p5", type: 'paragraph', content: t("You think about what the other person meant.") },
      { id: "m4b-p6", type: 'paragraph', content: t("You imagine a different response.") },
      { id: "m4b-p7", type: 'paragraph', content: t("You wonder whether you should have asked another question.") },
      { id: "m4b-p8", type: 'paragraph', content: t("Or maybe the conversation went well—and you keep returning to a compliment, some good news, or a moment that meant more to you than you expected.") },
      { id: "m4b-p9", type: 'paragraph', content: t("Replaying conversations in your head is not limited to arguments, awkward moments or difficult experiences.") },
      { id: "m4b-p10", type: 'paragraph', content: t("Sometimes we mentally return to conversations simply because they still feel relevant.") },
      { id: "m4b-p11", type: 'paragraph', content: t("The interaction may be over.") },
      { id: "m4b-p12", type: 'paragraph', content: t("Your thoughts about it may not be.") },
      { id: "m4b-p13", type: 'paragraph', content: t("And that can happen for several very ordinary reasons.") },
      { id: "m4b-h14", type: 'heading', level: 2, content: t("Why Do Conversations Replay in Our Minds?") },
      { id: "m4b-p15", type: 'paragraph', content: t("A conversation does not always feel complete just because people stopped speaking.") },
      { id: "m4b-p16", type: 'paragraph', content: t("Sometimes there is still something you are trying to understand.") },
      { id: "m4b-p17", type: 'paragraph', content: t("It could be what someone meant.") },
      { id: "m4b-p18", type: 'paragraph', content: t("It could be how you feel about what happened.") },
      { id: "m4b-p19", type: 'paragraph', content: t("It could be what you want to say next.") },
      { id: "m4b-p20", type: 'paragraph', content: t("It could be a decision that now needs to be made.") },
      { id: "m4b-p21", type: 'paragraph', content: t("Or it could simply be that the moment mattered to you.") },
      { id: "m4b-p22", type: 'paragraph', content: t("That distinction is important.") },
      { id: "m4b-p23", type: 'paragraph', content: t("When a conversation stays on your mind, the most useful first question may not be:") },
      { id: "m4b-p24", type: 'paragraph', content: t("“Why can't I stop thinking about this?”") },
      { id: "m4b-p25", type: 'paragraph', content: t("A more helpful question can be:") },
      { id: "m4b-p26", type: 'paragraph', content: t("“What about this conversation am I still trying to understand?”") },
      { id: "m4b-p27", type: 'paragraph', content: t("That changes the focus from trying to get rid of the thought to becoming curious about why it keeps returning.") },
      { id: "m4b-h28", type: 'heading', level: 2, content: t("1. Something About the Conversation May Feel Unfinished") },
      { id: "m4b-p29", type: 'paragraph', content: t("Some conversations end neatly.") },
      { id: "m4b-p30", type: 'paragraph', content: t("Others do not.") },
      { id: "m4b-p31", type: 'paragraph', content: t("Maybe someone said:") },
      { id: "m4b-p32", type: 'paragraph', content: t("“We'll talk about it later.”") },
      { id: "m4b-p33", type: 'paragraph', content: t("Maybe you asked a question and did not really get an answer.") },
      { id: "m4b-p34", type: 'paragraph', content: t("Maybe you wanted to say something but decided not to.") },
      { id: "m4b-p35", type: 'paragraph', content: t("Maybe a decision still needs to be made.") },
      { id: "m4b-p36", type: 'paragraph', content: t("Or perhaps everything sounded complete on the surface, but you are still deciding what the conversation meant to you.") },
      { id: "m4b-p37", type: 'paragraph', content: t("An unfinished conversation does not always mean there needs to be another conversation.") },
      { id: "m4b-p38", type: 'paragraph', content: t("Sometimes what is unfinished is simply your own understanding of it.") },
      { id: "m4b-p39", type: 'paragraph', content: t("You may still be asking yourself:") },
      { id: "m4b-p40", type: 'paragraph', content: t("What did I think about that?") },
      { id: "m4b-p41", type: 'paragraph', content: t("How did I actually feel?") },
      { id: "m4b-p42", type: 'paragraph', content: t("Do I agree?") },
      { id: "m4b-p43", type: 'paragraph', content: t("Do I need to do anything?") },
      { id: "m4b-p44", type: 'paragraph', content: t("Does this change something?") },
      { id: "m4b-p45", type: 'paragraph', content: t("Those questions can keep an ordinary interaction active in your attention long after the interaction itself has ended.") },
      { id: "m4b-h46", type: 'heading', level: 2, content: t("2. You May Be Trying to Understand What Someone Really Meant") },
      { id: "m4b-p47", type: 'paragraph', content: t("Words are only one part of a conversation.") },
      { id: "m4b-p48", type: 'paragraph', content: t("We also notice tone.") },
      { id: "m4b-p49", type: 'paragraph', content: t("Timing.") },
      { id: "m4b-p50", type: 'paragraph', content: t("Pauses.") },
      { id: "m4b-p51", type: 'paragraph', content: t("Expressions.") },
      { id: "m4b-p52", type: 'paragraph', content: t("Context.") },
      { id: "m4b-p53", type: 'paragraph', content: t("What someone said before.") },
      { id: "m4b-p54", type: 'paragraph', content: t("What they did not say.") },
      { id: "m4b-p55", type: 'paragraph', content: t("And sometimes we leave a conversation knowing exactly what was said but feeling less certain about what it meant.") },
      { id: "m4b-p56", type: 'paragraph', content: t("A colleague says:") },
      { id: "m4b-p57", type: 'paragraph', content: t("“That was interesting.”") },
      { id: "m4b-p58", type: 'paragraph', content: t("Was that positive?") },
      { id: "m4b-p59", type: 'paragraph', content: t("Neutral?") },
      { id: "m4b-p60", type: 'paragraph', content: t("Were they unsure?") },
      { id: "m4b-p61", type: 'paragraph', content: t("A friend says:") },
      { id: "m4b-p62", type: 'paragraph', content: t("“It's fine.”") },
      { id: "m4b-p63", type: 'paragraph', content: t("Was it actually fine?") },
      { id: "m4b-p64", type: 'paragraph', content: t("Someone tells you:") },
      { id: "m4b-p65", type: 'paragraph', content: t("“We should talk about this again.”") },
      { id: "m4b-p66", type: 'paragraph', content: t("Is that casual, or important?") },
      { id: "m4b-p67", type: 'paragraph', content: t("This does not mean every sentence contains a hidden message.") },
      { id: "m4b-p68", type: 'paragraph', content: t("Often it does not.") },
      { id: "m4b-p69", type: 'paragraph', content: t("But when meaning feels unclear, the mind may naturally return to the interaction because the question still feels open.") },
      { id: "m4b-h70", type: 'heading', level: 2, content: t("3. You May Be Thinking About What You Said") },
      { id: "m4b-p71", type: 'paragraph', content: t("Sometimes the part that stays with us is our own response.") },
      { id: "m4b-p72", type: 'paragraph', content: t("You remember saying something and wonder:") },
      { id: "m4b-p73", type: 'paragraph', content: t("Did that come across the way I intended?") },
      { id: "m4b-p74", type: 'paragraph', content: t("Should I have explained that differently?") },
      { id: "m4b-p75", type: 'paragraph', content: t("Was I too direct?") },
      { id: "m4b-p76", type: 'paragraph', content: t("Did I forget something important?") },
      { id: "m4b-p77", type: 'paragraph', content: t("Why did I say that?") },
      { id: "m4b-p78", type: 'paragraph', content: t("Or even:") },
      { id: "m4b-p79", type: 'paragraph', content: t("Why didn't I say what I was actually thinking?") },
      { id: "m4b-p80", type: 'paragraph', content: t("This can happen after conversations at work, with friends, with family, or with someone we have only just met.") },
      { id: "m4b-p81", type: 'paragraph', content: t("The sentence itself may have lasted five seconds.") },
      { id: "m4b-p82", type: 'paragraph', content: t("Thinking about it afterward can last much longer.") },
      { id: "m4b-p83", type: 'paragraph', content: t("That does not automatically mean the sentence was wrong.") },
      { id: "m4b-p84", type: 'paragraph', content: t("Sometimes you are simply comparing what you said with what you meant.") },
      { id: "m4b-h85", type: 'heading', level: 2, content: t("4. The Conversation May Matter to You More Than It Looked Like It Did") },
      { id: "m4b-p86", type: 'paragraph', content: t("Some interactions look small from the outside but carry more meaning personally.") },
      { id: "m4b-p87", type: 'paragraph', content: t("A manager tells you:") },
      { id: "m4b-p88", type: 'paragraph', content: t("“You handled that really well.”") },
      { id: "m4b-p89", type: 'paragraph', content: t("A friend casually mentions something that changes how you see a situation.") },
      { id: "m4b-p90", type: 'paragraph', content: t("Someone asks a question you have never thought about before.") },
      { id: "m4b-p91", type: 'paragraph', content: t("A family member says something unexpectedly kind.") },
      { id: "m4b-p92", type: 'paragraph', content: t("A person whose opinion matters to you notices something you worked hard on.") },
      { id: "m4b-p93", type: 'paragraph', content: t("The conversation itself may have been brief.") },
      { id: "m4b-p94", type: 'paragraph', content: t("Its meaning may not be.") },
      { id: "m4b-p95", type: 'paragraph', content: t("We tend to notice and revisit moments that connect with something we care about.") },
      { id: "m4b-p96", type: 'paragraph', content: t("That might be:") },
      { id: "m4b-p97", type: 'paragraph', content: t("our work,") },
      { id: "m4b-p98", type: 'paragraph', content: t("a relationship,") },
      { id: "m4b-p99", type: 'paragraph', content: t("a decision,") },
      { id: "m4b-p100", type: 'paragraph', content: t("an achievement,") },
      { id: "m4b-p101", type: 'paragraph', content: t("our future,") },
      { id: "m4b-p102", type: 'paragraph', content: t("something we value,") },
      { id: "m4b-p103", type: 'paragraph', content: t("or how we see ourselves.") },
      { id: "m4b-p104", type: 'paragraph', content: t("Sometimes the conversation stays because it touched something important.") },
      { id: "m4b-h105", type: 'heading', level: 2, content: t("5. Uncertainty Can Keep a Conversation Mentally Open") },
      { id: "m4b-p106", type: 'paragraph', content: t("Imagine sending a message and waiting for a reply.") },
      { id: "m4b-p107", type: 'paragraph', content: t("Or finishing an important conversation without knowing what the other person will decide.") },
      { id: "m4b-p108", type: 'paragraph', content: t("The conversation may technically be over.") },
      { id: "m4b-p109", type: 'paragraph', content: t("But the outcome is not.") },
      { id: "m4b-p110", type: 'paragraph', content: t("You might still be waiting to find out:") },
      { id: "m4b-p111", type: 'paragraph', content: t("Will they agree?") },
      { id: "m4b-p112", type: 'paragraph', content: t("What will they say next?") },
      { id: "m4b-p113", type: 'paragraph', content: t("Did I explain myself clearly?") },
      { id: "m4b-p114", type: 'paragraph', content: t("What happens now?") },
      { id: "m4b-p115", type: 'paragraph', content: t("This can make the interaction feel mentally unfinished.") },
      { id: "m4b-p116", type: 'paragraph', content: t("Part of your attention is no longer focused on what happened.") },
      { id: "m4b-p117", type: 'paragraph', content: t("It is focused on what comes next.") },
      { id: "m4b-p118", type: 'paragraph', content: t("That is why anticipation and reflection can sometimes overlap.") },
      { id: "m4b-p119", type: 'paragraph', content: t("You replay the past conversation because the next part of the story has not happened yet.") },
      { id: "m4b-h120", type: 'heading', level: 2, content: t("6. Work Conversations Can Follow You Home") },
      { id: "m4b-p121", type: 'paragraph', content: t("Sometimes the thing you carry home from work is not the workload.") },
      { id: "m4b-p122", type: 'paragraph', content: t("It is one conversation.") },
      { id: "m4b-p123", type: 'paragraph', content: t("A meeting.") },
      { id: "m4b-p124", type: 'paragraph', content: t("Feedback.") },
      { id: "m4b-p125", type: 'paragraph', content: t("A client call.") },
      { id: "m4b-p126", type: 'paragraph', content: t("A question you did not answer the way you wanted.") },
      { id: "m4b-p127", type: 'paragraph', content: t("A decision you have to make tomorrow.") },
      { id: "m4b-p128", type: 'paragraph', content: t("Something your manager said.") },
      { id: "m4b-p129", type: 'paragraph', content: t("Something your team finally figured out.") },
      { id: "m4b-p130", type: 'paragraph', content: t("Or a presentation that went much better than expected.") },
      { id: "m4b-p131", type: 'paragraph', content: t("The workday can end at a specific time.") },
      { id: "m4b-p132", type: 'paragraph', content: t("Attention does not always operate on the same schedule.") },
      { id: "m4b-p133", type: 'paragraph', content: t("A professional interaction can stay with you because it is connected to responsibility, progress, uncertainty, relationships or something you care about doing well.") },
      { id: "m4b-p134", type: 'paragraph', content: t("And importantly, the work conversations that stay with us are not always negative.") },
      { id: "m4b-p135", type: 'paragraph', content: t("Sometimes it is:") },
      { id: "m4b-p136", type: 'paragraph', content: t("“I finally got that right.”") },
      { id: "m4b-p137", type: 'paragraph', content: t("“They noticed how much work I put into that.”") },
      { id: "m4b-p138", type: 'paragraph', content: t("“That meeting actually went really well.”") },
      { id: "m4b-p139", type: 'paragraph', content: t("“I think this opportunity could become something.”") },
      { id: "m4b-p140", type: 'paragraph', content: t("Positive work moments can follow us home too.") },
      { id: "m4b-h141", type: 'heading', level: 2, content: t("7. Good Conversations Replay Too") },
      { id: "m4b-p142", type: 'paragraph', content: t("When people talk about replaying conversations, the examples are often uncomfortable ones.") },
      { id: "m4b-p143", type: 'paragraph', content: t("But think about a conversation that made you feel good.") },
      { id: "m4b-p144", type: 'paragraph', content: t("Maybe someone gave you wonderful news.") },
      { id: "m4b-p145", type: 'paragraph', content: t("Maybe you received a compliment you were not expecting.") },
      { id: "m4b-p146", type: 'paragraph', content: t("Maybe you finally told someone something important.") },
      { id: "m4b-p147", type: 'paragraph', content: t("Maybe you had a conversation that left you excited about the future.") },
      { id: "m4b-p148", type: 'paragraph', content: t("Maybe someone said exactly what you needed to hear—not as advice, but as recognition.") },
      { id: "m4b-p149", type: 'paragraph', content: t("You might replay that moment too.") },
      { id: "m4b-p150", type: 'paragraph', content: t("You remember the words.") },
      { id: "m4b-p151", type: 'paragraph', content: t("The expression.") },
      { id: "m4b-p152", type: 'paragraph', content: t("The timing.") },
      { id: "m4b-p153", type: 'paragraph', content: t("How you responded.") },
      { id: "m4b-p154", type: 'paragraph', content: t("How you felt afterward.") },
      { id: "m4b-p155", type: 'paragraph', content: t("Positive experiences can stay active in our attention because they matter.") },
      { id: "m4b-p156", type: 'paragraph', content: t("Reflection is not only something we do with problems.") },
      { id: "m4b-p157", type: 'paragraph', content: t("Sometimes we return to the moments we want to appreciate, understand or remember.") },
      { id: "m4b-h158", type: 'heading', level: 2, content: t("8. Text Messages Can Create Their Own Kind of Replay") },
      { id: "m4b-p159", type: 'paragraph', content: t("Not every conversation happens face to face.") },
      { id: "m4b-p160", type: 'paragraph', content: t("Sometimes the line you keep thinking about is sitting in a message thread.") },
      { id: "m4b-p161", type: 'paragraph', content: t("You reread it.") },
      { id: "m4b-p162", type: 'paragraph', content: t("You start typing a response.") },
      { id: "m4b-p163", type: 'paragraph', content: t("Delete it.") },
      { id: "m4b-p164", type: 'paragraph', content: t("Write another one.") },
      { id: "m4b-p165", type: 'paragraph', content: t("Put your phone down.") },
      { id: "m4b-p166", type: 'paragraph', content: t("Pick it up later.") },
      { id: "m4b-p167", type: 'paragraph', content: t("Or you may have already replied and still wonder how your message sounded.") },
      { id: "m4b-p168", type: 'paragraph', content: t("Written conversations remove some of the information we naturally receive in person.") },
      { id: "m4b-p169", type: 'paragraph', content: t("There may be no tone of voice.") },
      { id: "m4b-p170", type: 'paragraph', content: t("No expression.") },
      { id: "m4b-p171", type: 'paragraph', content: t("No immediate opportunity to clarify what someone meant.") },
      { id: "m4b-p172", type: 'paragraph', content: t("That can sometimes leave more room for interpretation.") },
      { id: "m4b-p173", type: 'paragraph', content: t("Again, it does not mean anything is necessarily wrong.") },
      { id: "m4b-p174", type: 'paragraph', content: t("There may simply be more that you are still trying to understand.") },
      { id: "m4b-h175", type: 'heading', level: 2, content: t("9. Sometimes We Replay Conversations Before They Even Happen") },
      { id: "m4b-p176", type: 'paragraph', content: t("Not all repeated conversations are memories.") },
      { id: "m4b-p177", type: 'paragraph', content: t("Some are rehearsals.") },
      { id: "m4b-p178", type: 'paragraph', content: t("You imagine asking your manager a question.") },
      { id: "m4b-p179", type: 'paragraph', content: t("You think through what you want to tell someone.") },
      { id: "m4b-p180", type: 'paragraph', content: t("You practice how you might explain a decision.") },
      { id: "m4b-p181", type: 'paragraph', content: t("You picture different ways another person could respond.") },
      { id: "m4b-p182", type: 'paragraph', content: t("You prepare for a difficult conversation.") },
      { id: "m4b-p183", type: 'paragraph', content: t("Or an exciting one.") },
      { id: "m4b-p184", type: 'paragraph', content: t("The actual conversation has not happened yet, but it is already taking up attention.") },
      { id: "m4b-p185", type: 'paragraph', content: t("That may be because you care about how the conversation goes.") },
      { id: "m4b-p186", type: 'paragraph', content: t("You are trying to find your words.") },
      { id: "m4b-p187", type: 'paragraph', content: t("You are anticipating a response.") },
      { id: "m4b-p188", type: 'paragraph', content: t("Or you simply want to understand what you think before you say it.") },
      { id: "m4b-p189", type: 'paragraph', content: t("Sometimes talking something through beforehand—even just saying it aloud to yourself—can reveal which part actually matters most.") },
      { id: "m4b-h190", type: 'heading', level: 2, content: t("Reflection and Repetition Are Not Always the Same Thing") },
      { id: "m4b-p191", type: 'paragraph', content: t("There is a difference between returning to a conversation and understanding something new about it.") },
      { id: "m4b-p192", type: 'paragraph', content: t("Useful reflection might sound like:") },
      { id: "m4b-p193", type: 'paragraph', content: t("“What part of that is still bothering me?”") },
      { id: "m4b-p194", type: 'paragraph', content: t("“What did I actually want to say?”") },
      { id: "m4b-p195", type: 'paragraph', content: t("“Did I misunderstand something?”") },
      { id: "m4b-p196", type: 'paragraph', content: t("“What matters to me here?”") },
      { id: "m4b-p197", type: 'paragraph', content: t("“Do I need to respond?”") },
      { id: "m4b-p198", type: 'paragraph', content: t("“Was there something positive in that conversation I don't want to rush past?”") },
      { id: "m4b-p199", type: 'paragraph', content: t("The goal is not to analyse every word.") },
      { id: "m4b-p200", type: 'paragraph', content: t("It is to become clearer about why the moment stayed with you.") },
      { id: "m4b-p201", type: 'paragraph', content: t("Sometimes that clarity leads to an action.") },
      { id: "m4b-p202", type: 'paragraph', content: t("You send the message.") },
      { id: "m4b-p203", type: 'paragraph', content: t("Ask the question.") },
      { id: "m4b-p204", type: 'paragraph', content: t("Make the decision.") },
      { id: "m4b-p205", type: 'paragraph', content: t("Clarify something.") },
      { id: "m4b-p206", type: 'paragraph', content: t("Write the thought down.") },
      { id: "m4b-p207", type: 'paragraph', content: t("Sometimes there is no action at all.") },
      { id: "m4b-p208", type: 'paragraph', content: t("You simply understand the experience better.") },
      { id: "m4b-p209", type: 'paragraph', content: t("Both outcomes can be useful.") },
      { id: "m4b-h210", type: 'heading', level: 2, content: t("A Simple Way to Reflect on a Conversation That Keeps Returning") },
      { id: "m4b-p211", type: 'paragraph', content: t("If the same conversation keeps showing up in your thoughts, you can give it a little structure without turning it into a major exercise.") },
      { id: "m4b-p212", type: 'paragraph', content: t("Start with:") },
      { id: "m4b-h213", type: 'heading', level: 3, content: t("What actually happened?") },
      { id: "m4b-p214", type: 'paragraph', content: t("Describe the conversation as simply as possible.") },
      { id: "m4b-p215", type: 'paragraph', content: t("What was said?") },
      { id: "m4b-p216", type: 'paragraph', content: t("What happened next?") },
      { id: "m4b-p217", type: 'paragraph', content: t("Try separating the actual interaction from everything you have imagined about it afterward.") },
      { id: "m4b-h218", type: 'heading', level: 3, content: t("What part keeps returning?") },
      { id: "m4b-p219", type: 'paragraph', content: t("Usually, the entire conversation is not repeating.") },
      { id: "m4b-p220", type: 'paragraph', content: t("It is one moment.") },
      { id: "m4b-p221", type: 'paragraph', content: t("One sentence.") },
      { id: "m4b-p222", type: 'paragraph', content: t("One reaction.") },
      { id: "m4b-p223", type: 'paragraph', content: t("One unanswered question.") },
      { id: "m4b-p224", type: 'paragraph', content: t("One thing you wished you had said.") },
      { id: "m4b-p225", type: 'paragraph', content: t("Finding that part makes the thought more specific.") },
      { id: "m4b-h226", type: 'heading', level: 3, content: t("Why might that part matter to me?") },
      { id: "m4b-p227", type: 'paragraph', content: t("Maybe it connects to something you care about.") },
      { id: "m4b-p228", type: 'paragraph', content: t("A relationship.") },
      { id: "m4b-p229", type: 'paragraph', content: t("Your work.") },
      { id: "m4b-p230", type: 'paragraph', content: t("How you were understood.") },
      { id: "m4b-p231", type: 'paragraph', content: t("A decision.") },
      { id: "m4b-p232", type: 'paragraph', content: t("An opportunity.") },
      { id: "m4b-p233", type: 'paragraph', content: t("Something you are proud of.") },
      { id: "m4b-p234", type: 'paragraph', content: t("Something you are uncertain about.") },
      { id: "m4b-p235", type: 'paragraph', content: t("You do not need a perfect answer.") },
      { id: "m4b-p236", type: 'paragraph', content: t("Even noticing the connection can create more clarity.") },
      { id: "m4b-h237", type: 'heading', level: 3, content: t("Is there anything I actually need to do?") },
      { id: "m4b-p238", type: 'paragraph', content: t("Maybe yes.") },
      { id: "m4b-p239", type: 'paragraph', content: t("Maybe no.") },
      { id: "m4b-p240", type: 'paragraph', content: t("You may need to ask a question, respond, make a decision or have another conversation.") },
      { id: "m4b-p241", type: 'paragraph', content: t("But sometimes the answer is simply:") },
      { id: "m4b-p242", type: 'paragraph', content: t("“No. I'm still thinking about it.”") },
      { id: "m4b-p243", type: 'paragraph', content: t("That is allowed too.") },
      { id: "m4b-h244", type: 'heading', level: 3, content: t("Do I want to give the thought somewhere to go?") },
      { id: "m4b-p245", type: 'paragraph', content: t("That might mean:") },
      { id: "m4b-p246", type: 'paragraph', content: t("writing it down,") },
      { id: "m4b-p247", type: 'paragraph', content: t("talking to someone you trust,") },
      { id: "m4b-p248", type: 'paragraph', content: t("taking a walk and thinking it through,") },
      { id: "m4b-p249", type: 'paragraph', content: t("or saying the thought aloud.") },
      { id: "m4b-p250", type: 'paragraph', content: t("The purpose is not to force an answer.") },
      { id: "m4b-p251", type: 'paragraph', content: t("It is to give yourself enough room to understand what is still asking for your attention.") },
      { id: "m4b-h252", type: 'heading', level: 2, content: t("You Don't Have to Treat Every Replayed Conversation Like a Problem") },
      { id: "m4b-p253", type: 'paragraph', content: t("Sometimes we become concerned simply because a thought has returned more than once.") },
      { id: "m4b-p254", type: 'paragraph', content: t("But repetition by itself does not tell you what the thought means.") },
      { id: "m4b-p255", type: 'paragraph', content: t("A conversation may return because it was:") },
      { id: "m4b-p256", type: 'paragraph', content: t("unfinished,") },
      { id: "m4b-p257", type: 'paragraph', content: t("uncertain,") },
      { id: "m4b-p258", type: 'paragraph', content: t("important,") },
      { id: "m4b-p259", type: 'paragraph', content: t("surprising,") },
      { id: "m4b-p260", type: 'paragraph', content: t("funny,") },
      { id: "m4b-p261", type: 'paragraph', content: t("encouraging,") },
      { id: "m4b-p262", type: 'paragraph', content: t("exciting,") },
      { id: "m4b-p263", type: 'paragraph', content: t("awkward,") },
      { id: "m4b-p264", type: 'paragraph', content: t("meaningful,") },
      { id: "m4b-p265", type: 'paragraph', content: t("or simply memorable.") },
      { id: "m4b-p266", type: 'paragraph', content: t("Instead of immediately labeling the experience, notice it.") },
      { id: "m4b-p267", type: 'paragraph', content: t("What exactly keeps returning?") },
      { id: "m4b-p268", type: 'paragraph', content: t("Why that part?") },
      { id: "m4b-p269", type: 'paragraph', content: t("What does it seem connected to?") },
      { id: "m4b-p270", type: 'paragraph', content: t("Does it need action—or only attention?") },
      { id: "m4b-p271", type: 'paragraph', content: t("Those questions often tell you more than trying to force the thought away.") },
      { id: "m4b-h272", type: 'heading', level: 2, content: t("Sometimes the Conversation Is Really With Yourself") },
      { id: "m4b-p273", type: 'paragraph', content: t("You may think you are replaying what another person said.") },
      { id: "m4b-p274", type: 'paragraph', content: t("But after a while, you realize the bigger conversation is happening internally.") },
      { id: "m4b-p275", type: 'paragraph', content: t("Do I agree with them?") },
      { id: "m4b-p276", type: 'paragraph', content: t("What do I want?") },
      { id: "m4b-p277", type: 'paragraph', content: t("Did that change my mind?") },
      { id: "m4b-p278", type: 'paragraph', content: t("Why did that matter so much?") },
      { id: "m4b-p279", type: 'paragraph', content: t("What would I do differently?") },
      { id: "m4b-p280", type: 'paragraph', content: t("Am I ready to say what I actually think?") },
      { id: "m4b-p281", type: 'paragraph', content: t("That is where replaying a conversation can turn into reflection.") },
      { id: "m4b-p282", type: 'paragraph', content: t("The other person's words may have started the thought.") },
      { id: "m4b-p283", type: 'paragraph', content: t("But what you are really trying to understand is your own response to it.") },
      { id: "m4b-h284", type: 'heading', level: 2, content: t("What If I Still Don't Have an Answer?") },
      { id: "m4b-p285", type: 'paragraph', content: t("You do not always need one.") },
      { id: "m4b-p286", type: 'paragraph', content: t("Some experiences become clearer slowly.") },
      { id: "m4b-p287", type: 'paragraph', content: t("You may understand something differently tomorrow than you do tonight.") },
      { id: "m4b-p288", type: 'paragraph', content: t("You might hear yourself say one sentence and realize:") },
      { id: "m4b-p289", type: 'paragraph', content: t("“That's the part I actually care about.”") },
      { id: "m4b-p290", type: 'paragraph', content: t("Or:") },
      { id: "m4b-p291", type: 'paragraph', content: t("“I don't need to do anything. I just needed to admit that bothered me.”") },
      { id: "m4b-p292", type: 'paragraph', content: t("Or:") },
      { id: "m4b-p293", type: 'paragraph', content: t("“That actually meant more to me than I realized.”") },
      { id: "m4b-p294", type: 'paragraph', content: t("Or even:") },
      { id: "m4b-p295", type: 'paragraph', content: t("“I still don't know what I think.”") },
      { id: "m4b-p296", type: 'paragraph', content: t("Reflection does not have to end in certainty.") },
      { id: "m4b-p297", type: 'paragraph', content: t("Sometimes it simply moves you from a vague repeating thought toward a clearer question.") },
      { id: "m4b-p298", type: 'paragraph', content: t("That can be enough for now.") },
      { id: "m4b-h299", type: 'heading', level: 2, content: t("The SOLACE Perspective") },
      { id: "m4b-p300", type: 'paragraph', content: t("At SOLACE, we believe meaningful conversations are not limited to difficult days.") },
      { id: "m4b-p301", type: 'paragraph', content: t("Sometimes what we carry is a concern.") },
      { id: "m4b-p302", type: 'paragraph', content: t("Sometimes it is a decision.") },
      { id: "m4b-p303", type: 'paragraph', content: t("Sometimes it is work.") },
      { id: "m4b-p304", type: 'paragraph', content: t("Sometimes it is good news.") },
      { id: "m4b-p305", type: 'paragraph', content: t("Sometimes it is one sentence someone said three hours ago that you are still thinking about.") },
      { id: "m4b-p306", type: 'paragraph', content: t("And sometimes there is no obvious problem at all.") },
      { id: "m4b-p307", type: 'paragraph', content: t("You simply have a thought that has not finished becoming clear yet.") },
      { id: "m4b-p308", type: 'paragraph', content: t("That's part of why conversation, journaling and everyday reflection can have a place in ordinary life.") },
      { id: "m4b-p-talkitout", type: 'paragraph', content: [{ text: "Talk It Out", link: { kind: 'route', value: 'product.talk_it_out' } }, { text: " by SOLACE is designed to give you somewhere to begin with your own words—without needing to have everything perfectly organized first." }] },
      { id: "m4b-p310", type: 'paragraph', content: t("Because sometimes the most useful question is not:") },
      { id: "m4b-p311", type: 'paragraph', content: t("“How do I stop thinking about this?”") },
      { id: "m4b-p312", type: 'paragraph', content: t("It is:") },
      { id: "m4b-p313", type: 'paragraph', content: t("“What am I still trying to understand?”") },
      { id: "m4b-p314", type: 'paragraph', content: t("Replaying a conversation does not automatically mean something went wrong.") },
      { id: "m4b-p315", type: 'paragraph', content: t("You may be returning to it because something still feels unfinished, uncertain, meaningful, positive or worth understanding.") },
      { id: "m4b-p316", type: 'paragraph', content: t("Instead of judging yourself for thinking about it again, try becoming more specific:") },
      { id: "m4b-p317", type: 'paragraph', content: t("What part stayed with me?") },
      { id: "m4b-p318", type: 'paragraph', content: t("Why might it matter?") },
      { id: "m4b-p319", type: 'paragraph', content: t("Do I need to do anything—or do I simply need a little more time to understand it?") },
      { id: "m4b-p320", type: 'paragraph', content: t("Sometimes the conversation has ended.") },
      { id: "m4b-p321", type: 'paragraph', content: t("The reflection has not.") },
      { id: "m4b-p322", type: 'paragraph', content: t("And those are not always the same thing.") },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W4-G001', anchorText: 'everyday reflection and why conversations stay with us', relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W4-A001', anchorText: 'common questions about replaying conversations', relation: 'related_content' },
  ],

  authoredOutsideWorkbook: ['inline link on the workbook\'s own "Talk It Out" wording (line 353) to the registered product.talk_it_out route; the sentence itself is unchanged'],
  missingFields: [
    'safety_notice (the workbook supplies no reader-facing crisis or disclaimer copy)',
    'cta (B001 is the one asset whose workbook section supplies no CTA label; none invented)',
    'faq (the workbook keeps FAQ authority on A001: "FAQ content should remain primarily on M2-W4-A001")',
    'seo_title (no schema field distinct from title)',
    'workbook references left UNLINKED: M2-W4-L001 (no Content Hub record), Journal and Mood/Reflection destinations (no registered public route)',
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// M2-W4-G001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W4_G001: M2W4Asset = {
  editorialRef: "M2-W4-G001",
  contentType: 'geo_article',
  publicLabel: 'Insight',
  title: "Why Conversations Stay With Us: Everyday Reflection and Replaying Interactions",
  slug: "replaying-conversations-and-everyday-reflection",
  // 172 characters in the workbook, over the 160 limit. Left null by editorial decision; the
  // original is in `editorial.geo_meta_description_over_limit` for Admin to shorten.
  metaDescription: null,
  week: 4,
  pillar: 'Everyday Wellbeing, Reflection, Communication and Self-Awareness',
  tags: ['replaying-conversations', 'everyday-reflection', 'communication', 'month-2', 'week-4'],

  typeFields: {
    core_concept: "Everyday Reflection, Replaying Conversations and Emotional Processing",
    citation_summary: "Conversations can stay in your thoughts after they end when something about them remains unfinished, uncertain, meaningful, or connected to what happens next. People may also replay positive conversations because they felt encouraging, important, or worth remembering.",
    topics: { primary: 'Everyday Reflection', secondary: ['Replaying Conversations', 'Emotional Processing'] },
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'GEO Authority Resource — structured knowledge, AI retrieval and topic depth.',
    goal: 'AI retrieval/referral visibility',
    internal_asset_title: "Everyday Reflection, Replaying Conversations and Emotional Processing",
    meta_title_note: "Replaying Conversations and Everyday Reflection | SOLACE",
    geo_meta_description_over_limit: "Explore why conversations, messages and social moments can stay in your thoughts after they end, and how everyday reflection can help you understand what remains important.",
    alternative_slug_note: "Preferred for clarity:",
  },

  body: {
    version: 1,
    blocks: [
      { id: "m4g-h1", type: 'heading', level: 2, content: t("What is everyday reflection?") },
      { id: "m4g-p2", type: 'paragraph', content: t("Everyday reflection is the process of noticing and thinking about ordinary experiences after they happen.") },
      { id: "m4g-p3", type: 'paragraph', content: t("It can involve:") },
      { id: "m4g-p4", type: 'paragraph', content: t("A conversation.") },
      { id: "m4g-p5", type: 'paragraph', content: t("A decision.") },
      { id: "m4g-p6", type: 'paragraph', content: t("A message.") },
      { id: "m4g-p7", type: 'paragraph', content: t("A work interaction.") },
      { id: "m4g-p8", type: 'paragraph', content: t("A piece of feedback.") },
      { id: "m4g-p9", type: 'paragraph', content: t("A small win.") },
      { id: "m4g-p10", type: 'paragraph', content: t("Something someone said.") },
      { id: "m4g-p11", type: 'paragraph', content: t("Good news.") },
      { id: "m4g-p12", type: 'paragraph', content: t("An unfinished moment.") },
      { id: "m4g-p13", type: 'paragraph', content: t("Reflection does not automatically mean something is wrong.") },
      { id: "m4g-p14", type: 'paragraph', content: t("It can simply be a way of making sense of an experience.") },
      { id: "m4g-h15", type: 'heading', level: 2, content: t("What does it mean to replay a conversation?") },
      { id: "m4g-p16", type: 'paragraph', content: t("Replaying a conversation means mentally returning to part of an interaction after the interaction has ended.") },
      { id: "m4g-p17", type: 'paragraph', content: t("A person may revisit:") },
      { id: "m4g-p18", type: 'paragraph', content: t("What they said.") },
      { id: "m4g-p19", type: 'paragraph', content: t("What the other person said.") },
      { id: "m4g-p20", type: 'paragraph', content: t("How something sounded.") },
      { id: "m4g-p21", type: 'paragraph', content: t("What they meant.") },
      { id: "m4g-p22", type: 'paragraph', content: t("What happened next.") },
      { id: "m4g-p23", type: 'paragraph', content: t("Something they wish they had explained better.") },
      { id: "m4g-p24", type: 'paragraph', content: t("Something positive they want to remember.") },
      { id: "m4g-p25", type: 'paragraph', content: t("The conversation itself may be over while the meaning of the moment still feels active.") },
      { id: "m4g-h26", type: 'heading', level: 2, content: t("What Is Everyday Reflection?") },
      { id: "m4g-p27", type: 'paragraph', content: t("Everyday reflection means noticing an experience and continuing to think about it after the moment itself has passed.") },
      { id: "m4g-p28", type: 'paragraph', content: t("It can happen after:") },
      { id: "m4g-p29", type: 'paragraph', content: t("A work conversation.") },
      { id: "m4g-p30", type: 'paragraph', content: t("A personal conversation.") },
      { id: "m4g-p31", type: 'paragraph', content: t("A message.") },
      { id: "m4g-p32", type: 'paragraph', content: t("An appointment.") },
      { id: "m4g-p33", type: 'paragraph', content: t("A decision.") },
      { id: "m4g-p34", type: 'paragraph', content: t("A compliment.") },
      { id: "m4g-p35", type: 'paragraph', content: t("A difficult moment.") },
      { id: "m4g-p36", type: 'paragraph', content: t("A small success.") },
      { id: "m4g-p37", type: 'paragraph', content: t("Reflection may help someone understand:") },
      { id: "m4g-p38", type: 'paragraph', content: t("What mattered.") },
      { id: "m4g-p39", type: 'paragraph', content: t("What still feels unfinished.") },
      { id: "m4g-p40", type: 'paragraph', content: t("What they want to do next.") },
      { id: "m4g-p41", type: 'paragraph', content: t("What they want to remember.") },
      { id: "m4g-h42", type: 'heading', level: 2, content: t("What Does It Mean to Replay a Conversation?") },
      { id: "m4g-p43", type: 'paragraph', content: t("Replaying a conversation means mentally revisiting part of an interaction after it has ended.") },
      { id: "m4g-p44", type: 'paragraph', content: t("Sometimes the whole conversation returns.") },
      { id: "m4g-p45", type: 'paragraph', content: t("More often, it may be one part:") },
      { id: "m4g-p46", type: 'paragraph', content: t("A sentence.") },
      { id: "m4g-p47", type: 'paragraph', content: t("A tone.") },
      { id: "m4g-p48", type: 'paragraph', content: t("A reaction.") },
      { id: "m4g-p49", type: 'paragraph', content: t("A pause.") },
      { id: "m4g-p50", type: 'paragraph', content: t("A question.") },
      { id: "m4g-p51", type: 'paragraph', content: t("A piece of feedback.") },
      { id: "m4g-p52", type: 'paragraph', content: t("A moment of connection.") },
      { id: "m4g-p53", type: 'paragraph', content: t("This can happen in both difficult and positive interactions.") },
      { id: "m4g-h54", type: 'heading', level: 2, content: t("Why Can Conversations Stay Mentally Active?") },
      { id: "m4g-p55", type: 'paragraph', content: t("Common reasons can include:") },
      { id: "m4g-p56", type: 'paragraph', content: t("Uncertainty.") },
      { id: "m4g-p57", type: 'paragraph', content: t("Unfinished meaning.") },
      { id: "m4g-p58", type: 'paragraph', content: t("Waiting for a response.") },
      { id: "m4g-p59", type: 'paragraph', content: t("Wanting to clarify something.") },
      { id: "m4g-p60", type: 'paragraph', content: t("Caring about how you were understood.") },
      { id: "m4g-p61", type: 'paragraph', content: t("Thinking about what happens next.") },
      { id: "m4g-p62", type: 'paragraph', content: t("Feeling proud of how something went.") },
      { id: "m4g-p63", type: 'paragraph', content: t("Remembering something kind or meaningful.") },
      { id: "m4g-p64", type: 'paragraph', content: t("The amount of time a conversation takes does not always match how much meaning it carries.") },
      { id: "m4g-h65", type: 'heading', level: 2, content: t("Uncertainty Can Keep a Conversation Open in Your Thoughts") },
      { id: "m4g-p66", type: 'paragraph', content: t("Examples:") },
      { id: "m4g-p67", type: 'paragraph', content: t("Did they understand what I meant?") },
      { id: "m4g-p68", type: 'paragraph', content: t("Were they serious?") },
      { id: "m4g-p69", type: 'paragraph', content: t("What did that response mean?") },
      { id: "m4g-p70", type: 'paragraph', content: t("Will they follow up?") },
      { id: "m4g-p71", type: 'paragraph', content: t("Should I say something else?") },
      { id: "m4g-p72", type: 'paragraph', content: t("When the outcome or meaning is still unclear, attention may return to the interaction.") },
      { id: "m4g-p73", type: 'paragraph', content: t("This is an everyday observation, not a diagnosis.") },
      { id: "m4g-h74", type: 'heading', level: 2, content: t("Unfinished Conversations Can Keep Returning") },
      { id: "m4g-p75", type: 'paragraph', content: t("A conversation may feel unfinished if:") },
      { id: "m4g-p76", type: 'paragraph', content: t("You still need to reply.") },
      { id: "m4g-p77", type: 'paragraph', content: t("Something still needs to be clarified.") },
      { id: "m4g-p78", type: 'paragraph', content: t("A decision has not been made.") },
      { id: "m4g-p79", type: 'paragraph', content: t("Another conversation needs to happen.") },
      { id: "m4g-p80", type: 'paragraph', content: t("You are waiting for the other person.") },
      { id: "m4g-p81", type: 'paragraph', content: t("You did not say what you intended to say.") },
      { id: "m4g-p82", type: 'paragraph', content: t("The interaction itself may have stopped while the situation remains open.") },
      { id: "m4g-h83", type: 'heading', level: 2, content: t("Caring About How You Were Understood Can Matter") },
      { id: "m4g-p84", type: 'paragraph', content: t("People may revisit a conversation because they are thinking about:") },
      { id: "m4g-p85", type: 'paragraph', content: t("Whether they communicated clearly.") },
      { id: "m4g-p86", type: 'paragraph', content: t("Whether their tone matched what they meant.") },
      { id: "m4g-p87", type: 'paragraph', content: t("Whether the other person understood the intention.") },
      { id: "m4g-p88", type: 'paragraph', content: t("Whether the moment came across differently than expected.") },
      { id: "m4g-p89", type: 'paragraph', content: t("This can happen in:") },
      { id: "m4g-p90", type: 'paragraph', content: t("Work.") },
      { id: "m4g-p91", type: 'paragraph', content: t("Friendships.") },
      { id: "m4g-p92", type: 'paragraph', content: t("Relationships.") },
      { id: "m4g-p93", type: 'paragraph', content: t("Family conversations.") },
      { id: "m4g-p94", type: 'paragraph', content: t("Professional communication.") },
      { id: "m4g-h95", type: 'heading', level: 2, content: t("Replaying Before a Conversation Happens") },
      { id: "m4g-p96", type: 'paragraph', content: t("Not every replay happens afterward.") },
      { id: "m4g-p97", type: 'paragraph', content: t("Sometimes people mentally rehearse an interaction before it begins.") },
      { id: "m4g-p98", type: 'paragraph', content: t("Examples:") },
      { id: "m4g-p99", type: 'paragraph', content: t("Practicing how to ask a question.") },
      { id: "m4g-p100", type: 'paragraph', content: t("Thinking about how to start.") },
      { id: "m4g-p101", type: 'paragraph', content: t("Preparing for a meeting.") },
      { id: "m4g-p102", type: 'paragraph', content: t("Rehearsing a difficult sentence.") },
      { id: "m4g-p103", type: 'paragraph', content: t("Planning how to share good news.") },
      { id: "m4g-p104", type: 'paragraph', content: t("This is closely connected to anticipation.") },
      { id: "m4g-p105", type: 'paragraph', content: t("The mental preparation may last longer than the conversation itself.") },
      { id: "m4g-h106", type: 'heading', level: 2, content: t("Work Conversations Can Follow Us Home") },
      { id: "m4g-p107", type: 'paragraph', content: t("At work, replaying may involve:") },
      { id: "m4g-p108", type: 'paragraph', content: t("Feedback.") },
      { id: "m4g-p109", type: 'paragraph', content: t("Client conversations.") },
      { id: "m4g-p110", type: 'paragraph', content: t("Meetings.") },
      { id: "m4g-p111", type: 'paragraph', content: t("Manager discussions.") },
      { id: "m4g-p112", type: 'paragraph', content: t("Presentations.") },
      { id: "m4g-p113", type: 'paragraph', content: t("A difficult question.") },
      { id: "m4g-p114", type: 'paragraph', content: t("A compliment.") },
      { id: "m4g-p115", type: 'paragraph', content: t("A decision still waiting.") },
      { id: "m4g-p116", type: 'paragraph', content: t("A successful outcome.") },
      { id: "m4g-p117", type: 'paragraph', content: t("The important distinction:") },
      { id: "m4g-p118", type: 'paragraph', content: t("Not every work thought carried home is negative.") },
      { id: "m4g-p119", type: 'paragraph', content: t("Some conversations stay because they mattered in a positive way.") },
      { id: "m4g-h120", type: 'heading', level: 2, content: t("Positive Conversations Can Replay Too") },
      { id: "m4g-p121", type: 'paragraph', content: t("People may replay positive conversations because they felt:") },
      { id: "m4g-p122", type: 'paragraph', content: t("Encouraging.") },
      { id: "m4g-p123", type: 'paragraph', content: t("Meaningful.") },
      { id: "m4g-p124", type: 'paragraph', content: t("Funny.") },
      { id: "m4g-p125", type: 'paragraph', content: t("Supportive.") },
      { id: "m4g-p126", type: 'paragraph', content: t("Surprising.") },
      { id: "m4g-p127", type: 'paragraph', content: t("Validating.") },
      { id: "m4g-p128", type: 'paragraph', content: t("Exciting.") },
      { id: "m4g-p129", type: 'paragraph', content: t("A compliment can stay in mind.") },
      { id: "m4g-p130", type: 'paragraph', content: t("Good feedback can stay in mind.") },
      { id: "m4g-p131", type: 'paragraph', content: t("Someone saying “I’m proud of you” can stay in mind.") },
      { id: "m4g-p132", type: 'paragraph', content: t("A conversation that went better than expected can stay in mind.") },
      { id: "m4g-p133", type: 'paragraph', content: t("Everyday reflection includes those moments too.") },
      { id: "m4g-h134", type: 'heading', level: 2, content: t("Digital Conversations Can Stay Active Too") },
      { id: "m4g-p135", type: 'paragraph', content: t("Modern communication includes:") },
      { id: "m4g-p136", type: 'paragraph', content: t("Texts.") },
      { id: "m4g-p137", type: 'paragraph', content: t("Emails.") },
      { id: "m4g-p138", type: 'paragraph', content: t("Voice notes.") },
      { id: "m4g-p139", type: 'paragraph', content: t("Work chats.") },
      { id: "m4g-p140", type: 'paragraph', content: t("DMs.") },
      { id: "m4g-p141", type: 'paragraph', content: t("Video calls.") },
      { id: "m4g-p142", type: 'paragraph', content: t("People may replay:") },
      { id: "m4g-p143", type: 'paragraph', content: t("A sent message.") },
      { id: "m4g-p144", type: 'paragraph', content: t("A delayed reply.") },
      { id: "m4g-p145", type: 'paragraph', content: t("A short phrase.") },
      { id: "m4g-p146", type: 'paragraph', content: t("The tone of a response.") },
      { id: "m4g-p147", type: 'paragraph', content: t("What has not been answered.") },
      { id: "m4g-p148", type: 'paragraph', content: t("The same everyday reflective pattern can happen without a face-to-face conversation.") },
      { id: "m4g-h149", type: 'heading', level: 2, content: t("What Is Emotional Processing in Everyday Language?") },
      { id: "m4g-p150", type: 'paragraph', content: t("Emotional processing can be understood as continuing to make sense of how an experience felt, what it meant, and whether anything still needs attention after the moment ends.") },
      { id: "m4g-p151", type: 'paragraph', content: t("This might involve:") },
      { id: "m4g-p152", type: 'paragraph', content: t("Recognizing how you felt.") },
      { id: "m4g-p153", type: 'paragraph', content: t("Understanding why the moment mattered.") },
      { id: "m4g-p154", type: 'paragraph', content: t("Deciding whether action is needed.") },
      { id: "m4g-p155", type: 'paragraph', content: t("Remembering something positive.") },
      { id: "m4g-p156", type: 'paragraph', content: t("Allowing a conversation to become clearer with time.") },
      { id: "m4g-h157", type: 'heading', level: 2, content: t("When Can Reflection Be Useful?") },
      { id: "m4g-p158", type: 'paragraph', content: t("Reflection can be useful when it helps answer:") },
      { id: "m4g-p159", type: 'paragraph', content: t("What part of this interaction keeps returning?") },
      { id: "m4g-p160", type: 'paragraph', content: t("Is anything actually unfinished?") },
      { id: "m4g-p161", type: 'paragraph', content: t("Am I waiting for a response?") },
      { id: "m4g-p162", type: 'paragraph', content: t("Do I need to clarify something?") },
      { id: "m4g-p163", type: 'paragraph', content: t("Did the conversation matter because it was positive?") },
      { id: "m4g-p164", type: 'paragraph', content: t("Is there anything I need to carry forward?") },
      { id: "m4g-p165", type: 'paragraph', content: t("Is there anything I can simply acknowledge and leave alone?") },
      { id: "m4g-h166", type: 'heading', level: 2, content: t("Reflection Is Not the Same as Endless Analysis") },
      { id: "m4g-p167", type: 'paragraph', content: t("Important distinction:") },
      { id: "m4g-p168", type: 'paragraph', content: t("Reflection can be:") },
      { id: "m4g-p169", type: 'paragraph', content: t("Brief.") },
      { id: "m4g-p170", type: 'paragraph', content: t("Specific.") },
      { id: "m4g-p171", type: 'paragraph', content: t("Purposeful.") },
      { id: "m4g-p172", type: 'paragraph', content: t("Open.") },
      { id: "m4g-p173", type: 'paragraph', content: t("It may simply mean noticing:") },
      { id: "m4g-p174", type: 'paragraph', content: t("“That conversation is still with me.”") },
      { id: "m4g-p175", type: 'paragraph', content: t("Then asking:") },
      { id: "m4g-p176", type: 'paragraph', content: t("“Why?”") },
      { id: "m4g-p177", type: 'paragraph', content: t("without trying to interpret every word indefinitely.") },
      { id: "m4g-h178", type: 'heading', level: 2, content: t("What Replaying a Conversation Does Not Automatically Mean") },
      { id: "m4g-p179", type: 'paragraph', content: t("Replaying an interaction does not automatically mean:") },
      { id: "m4g-p180", type: 'paragraph', content: t("You have anxiety.") },
      { id: "m4g-p181", type: 'paragraph', content: t("You have social anxiety.") },
      { id: "m4g-p182", type: 'paragraph', content: t("You have OCD.") },
      { id: "m4g-p183", type: 'paragraph', content: t("You communicated badly.") },
      { id: "m4g-p184", type: 'paragraph', content: t("The other person is upset.") },
      { id: "m4g-p185", type: 'paragraph', content: t("Something is wrong with you.") },
      { id: "m4g-p186", type: 'paragraph', content: t("It can simply reflect:") },
      { id: "m4g-p187", type: 'paragraph', content: t("Uncertainty.") },
      { id: "m4g-p188", type: 'paragraph', content: t("Interest.") },
      { id: "m4g-p189", type: 'paragraph', content: t("Importance.") },
      { id: "m4g-p190", type: 'paragraph', content: t("Connection.") },
      { id: "m4g-p191", type: 'paragraph', content: t("Anticipation.") },
      { id: "m4g-p192", type: 'paragraph', content: t("Unfinished meaning.") },
      { id: "m4g-p193", type: 'paragraph', content: t("Positive emotional impact.") },
      { id: "m4g-h194", type: 'heading', level: 2, content: t("Why the Same Conversation Can Affect People Differently") },
      { id: "m4g-p195", type: 'paragraph', content: t("Different people may give the same interaction different amounts of attention depending on:") },
      { id: "m4g-p196", type: 'paragraph', content: t("What the relationship means to them.") },
      { id: "m4g-p197", type: 'paragraph', content: t("Whether the outcome matters.") },
      { id: "m4g-p198", type: 'paragraph', content: t("Whether the conversation was expected.") },
      { id: "m4g-p199", type: 'paragraph', content: t("What happened beforehand.") },
      { id: "m4g-p200", type: 'paragraph', content: t("Whether something remains unresolved.") },
      { id: "m4g-p201", type: 'paragraph', content: t("Whether the moment felt positive.") },
      { id: 'm4g-takeaway', type: 'key_takeaway', title: "Key Takeaway", points: [t("Conversations can stay in your thoughts after they end because something about them remains:"), t("Unfinished"), t("Uncertain"), t("Meaningful"), t("Important"), t("Connected to another person"), t("Relevant to what happens next"), t("or:"), t("Worth remembering"), t("Replaying a conversation does not automatically mean there is a problem.")] },
      { id: 'm4g-table', type: 'table', headers: ["Situation", "What May Stay With You"], rows: [[t("Work meeting"), t("One sentence or piece of feedback")], [t("Text message"), t("How the message was understood")], [t("Difficult conversation"), t("Something still unresolved")], [t("Positive conversation"), t("A kind or meaningful comment")], [t("Presentation"), t("How the moment went")], [t("Manager conversation"), t("What happens next")], [t("Good news"), t("Who you want to tell")], [t("Unanswered message"), t("Waiting for the response")]] },
      { id: "m4g-l202", type: 'list', style: 'bullet', items: [t("What part of the conversation keeps returning?"), t("Is something still unfinished?"), t("Am I waiting for another person?"), t("Do I need to clarify anything?"), t("Am I simply remembering something meaningful?"), t("Did something positive happen that I want to hold onto?"), t("Is there actually any action needed?"), t("Can I acknowledge the moment without continuing to examine every detail?")] },
      { id: 'm4g-faq', type: 'faq', heading: 'Frequently Asked Questions', items: [{ id: "m4g-faq-1", question: "Why do I replay conversations after they happen?", answer: t("You may replay a conversation when you are still interpreting what happened, waiting for what comes next, thinking about how you were understood, or because the interaction felt meaningful.") }, { id: "m4g-faq-2", question: "Why do I replay conversations before they happen?", answer: t("People may mentally rehearse conversations when they want to prepare what to say or are unsure how the other person will respond. This is a common form of anticipation.") }, { id: "m4g-faq-3", question: "Why do work conversations stay in my mind after work?", answer: t("A work conversation may remain mentally active when there is still a task, decision, response, meaning, or positive outcome connected to it.") }, { id: "m4g-faq-4", question: "Why do I replay text messages?", answer: t("Messages can stay in your thoughts when tone feels unclear, the response is still pending, or you are considering how something was understood.") }, { id: "m4g-faq-5", question: "Can a good conversation stay on my mind too?", answer: t("Yes. Compliments, good feedback, meaningful connection, humor, good news, and conversations that went better than expected can all stay with you.") }, { id: "m4g-faq-6", question: "Does replaying a conversation mean I said something wrong?", answer: t("Not necessarily. A conversation can stay in your thoughts because it mattered, felt unfinished, created uncertainty, or was simply memorable.") }, { id: "m4g-faq-7", question: "Is replaying a conversation the same as overthinking?", answer: t("Not always. Replaying simply describes returning to an interaction in your thoughts. “Overthinking” is a broader everyday term that people often use when something feels repetitive or receives more attention than expected.") }, { id: "m4g-faq-8", question: "How can I reflect on a conversation without analysing everything?", answer: t("Focus on the part that keeps returning and ask whether anything still needs understanding, clarification, action, or simply acknowledgment.") }] },
      { id: 'm4g-statement', type: 'geo_statement', statement: t("Conversations can stay in your thoughts after they end when something about them remains unfinished, uncertain, meaningful, or connected to what happens next. People may also replay positive conversations because they felt encouraging, important, or worth remembering.") },
      { id: "m4g-h203", type: 'heading', level: 3, content: t("Everyday reflection") },
      { id: "m4g-p204", type: 'paragraph', content: t("Thinking about an ordinary experience after it happens in order to understand what mattered, what remains unfinished, or what is worth remembering.") },
      { id: "m4g-h205", type: 'heading', level: 3, content: t("Replaying a conversation") },
      { id: "m4g-p206", type: 'paragraph', content: t("Mentally returning to part of an interaction after it has ended.") },
      { id: "m4g-h207", type: 'heading', level: 3, content: t("Emotional processing") },
      { id: "m4g-p208", type: 'paragraph', content: t("Continuing to make sense of what an experience felt like, meant, or may require next.") },
      { id: "m4g-p209", type: 'paragraph', content: t("SOLACE creates space for adults to reflect on everyday conversations, work moments, decisions, good news, unfinished thoughts, and the experiences that continue to matter after the moment itself ends.") },
      { id: 'm4g-cta', type: 'cta', label: "Explore more everyday reflection resources.", target: { kind: 'route', value: 'resource_library' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W4-B001', anchorText: 'why conversations keep replaying in your head', relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W4-A001', anchorText: 'common questions about replaying conversations', relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W3-G001', anchorText: 'anticipation and everyday mental attention', relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'resource_library', anchorText: "Explore more everyday reflection resources.", relation: 'resource_library' },
  ],

  authoredOutsideWorkbook: ['cta block (label and destination from the workbook PART 52 optional CTA)'],
  missingFields: [
    'safety_notice (PART 27 is reader-facing topical reassurance, not crisis or disclaimer copy; PART 53 is a writer guardrail list. Neither is a safety notice and none is manufactured)',
    'meta_description (workbook value is 172 chars, over the 160 limit; left null by editorial decision)',
    'key_statements (the workbook has no Key Statements section; none manufactured)',
    'workbook references left UNLINKED: M2-W4-L001 (no Content Hub record), Journal (no registered public route)',
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// M2-W4-A001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W4_A001: M2W4Asset = {
  editorialRef: "M2-W4-A001",
  contentType: 'aeo_answer',
  publicLabel: 'Answer',
  title: "Why Do I Replay Conversations? Common Questions About Everyday Reflection",
  slug: "why-do-i-replay-conversations",
  metaDescription: "Why do conversations stay in your head after they end? Find clear answers about replaying conversations, messages, work moments and everyday reflection.",
  week: 4,
  pillar: 'Everyday Wellbeing, Reflection, Communication and Self-Awareness',
  tags: ['replaying-conversations', 'everyday-reflection', 'communication', 'month-2', 'week-4'],

  typeFields: {
    primary_question: "Why do I replay conversations in my head?",
    snippet_answer: "Conversations can replay when something about them still feels unfinished, uncertain, important or meaningful. You may also revisit a conversation because you care about how you were understood, what the other person meant, or what happens next. Positive conversations can stay with you too.",
    supporting_queries: ["Why do I replay conversations in my head?", "Why do I keep thinking about what I said?", "Why do work conversations stay on my mind?", "Why do I replay text messages?", "Why do I think about conversations before they happen?", "Can positive conversations replay too?", "Does replaying mean I did something wrong?"],
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'AEO / FAQ Authority Resource — direct answers and search/AI visibility.',
    goal: 'Direct-answer visibility across search and AI systems',
    meta_title_note: "Why Do I Replay Conversations? | SOLACE",
    geo_meta_description_note: "Explore clear answers about why conversations, messages and social moments can stay active in your thoughts, including uncertainty, meaning and positive experiences.",
    alternative_title_note: "Why Do Conversations Stay in My Head? Common Questions About Replaying and Reflection",
    alternative_slug_note: "/resources/why-do-i-replay-conversations",
  },

  body: {
    version: 1,
    blocks: [
      { id: 'm4a-direct', type: 'direct_answer', content: t("Conversations can replay when something about them still feels unfinished, uncertain, important or meaningful. You may also revisit a conversation because you care about how you were understood, what the other person meant, or what happens next. Positive conversations can stay with you too.") },
      { id: "m4a-p1", type: 'paragraph', content: t("A conversation can be over and still stay active in your thoughts.") },
      { id: "m4a-p2", type: 'paragraph', content: t("You may replay what you said.") },
      { id: "m4a-p3", type: 'paragraph', content: t("What the other person said.") },
      { id: "m4a-p4", type: 'paragraph', content: t("Something you wish you had explained differently.") },
      { id: "m4a-p5", type: 'paragraph', content: t("A question still waiting for an answer.") },
      { id: "m4a-p6", type: 'paragraph', content: t("Or even a compliment or piece of good news that felt worth holding onto.") },
      { id: "m4a-p7", type: 'paragraph', content: t("Below are clear answers to common questions about why everyday conversations can stay with us after they end.") },
      { id: "m4a-h8", type: 'heading', level: 2, content: t("Why Do I Replay Conversations in My Head?") },
      { id: "m4a-p9", type: 'paragraph', content: t("You may replay a conversation when part of it still feels unfinished, unclear, important or connected to what happens next.") },
      { id: "m4a-p10", type: 'paragraph', content: t("Sometimes you are thinking about how you were understood.") },
      { id: "m4a-p11", type: 'paragraph', content: t("Sometimes you are simply remembering a moment that mattered.") },
      { id: "m4a-h12", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About Something I Said?") },
      { id: "m4a-p13", type: 'paragraph', content: t("A sentence may stay in your mind when you are wondering whether it matched what you meant or how the other person may have understood it.") },
      { id: "m4a-p14", type: 'paragraph', content: t("That does not automatically mean you said something wrong.") },
      { id: "m4a-h15", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About What Someone Else Said?") },
      { id: "m4a-p16", type: 'paragraph', content: t("Someone’s words can stay with you when they felt surprising, unclear, encouraging, meaningful or connected to something you care about.") },
      { id: "m4a-p17", type: 'paragraph', content: t("A short sentence can carry more meaning than its length suggests.") },
      { id: "m4a-h18", type: 'heading', level: 2, content: t("Why Do I Replay Conversations After They Happen?") },
      { id: "m4a-p19", type: 'paragraph', content: t("After a conversation ends, you may still be interpreting what happened, thinking about what comes next or deciding whether anything remains unresolved.") },
      { id: "m4a-p20", type: 'paragraph', content: t("The social interaction may be finished while the meaning of it is still active.") },
      { id: "m4a-h21", type: 'heading', level: 2, content: t("Why Do I Rehearse Conversations Before They Happen?") },
      { id: "m4a-p22", type: 'paragraph', content: t("People often mentally prepare when they care about what they want to say or do not know exactly how the other person will respond.") },
      { id: "m4a-p23", type: 'paragraph', content: t("The preparation may last much longer than the actual conversation.") },
      { id: "m4a-h24", type: 'heading', level: 2, content: t("Why Do I Think About a Conversation All Day?") },
      { id: "m4a-p25", type: 'paragraph', content: t("A conversation can occupy attention for longer when the outcome matters, something still feels open or you are waiting for another step.") },
      { id: "m4a-p26", type: 'paragraph', content: t("Its duration may be short, but its meaning can follow you through the rest of the day.") },
      { id: "m4a-h27", type: 'heading', level: 2, content: t("Why Do Work Conversations Stay on My Mind After Work?") },
      { id: "m4a-p28", type: 'paragraph', content: t("A work conversation may stay active because there is still a task, decision, response, follow-up or meaning connected to it.") },
      { id: "m4a-p29", type: 'paragraph', content: t("Positive work moments can stay with you too, including praise, good feedback or a presentation that went well.") },
      { id: "m4a-h30", type: 'heading', level: 2, content: t("Why Do I Replay Meetings?") },
      { id: "m4a-p31", type: 'paragraph', content: t("You may replay a meeting when you are thinking about what was decided, what was left unclear, what you said or what you need to do next.") },
      { id: "m4a-p32", type: 'paragraph', content: t("Sometimes one small moment from the meeting is what stays, not the whole thing.") },
      { id: "m4a-h33", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About Feedback I Received?") },
      { id: "m4a-p34", type: 'paragraph', content: t("Feedback can stay with you because it may affect how you understand your work, progress or next step.") },
      { id: "m4a-p35", type: 'paragraph', content: t("Positive feedback can remain just as memorable as criticism.") },
      { id: "m4a-h36", type: 'heading', level: 2, content: t("Why Do I Replay a Text Message?") },
      { id: "m4a-p37", type: 'paragraph', content: t("Texts can stay mentally active when tone feels unclear, the response is still pending or you are thinking about how your own message was understood.") },
      { id: "m4a-p38", type: 'paragraph', content: t("Because text removes some face-to-face cues, small wording details can feel more noticeable.") },
      { id: "m4a-h39", type: 'heading', level: 2, content: t("Why Do I Keep Rereading an Email I Already Sent?") },
      { id: "m4a-p40", type: 'paragraph', content: t("You may reread a sent email because the action is complete but the outcome is not.") },
      { id: "m4a-p41", type: 'paragraph', content: t("You may still be thinking about whether the message was clear, how it will be received or what response might come next.") },
      { id: "m4a-h42", type: 'heading', level: 2, content: t("Why Do I Think I Sounded Rude?") },
      { id: "m4a-p43", type: 'paragraph', content: t("After a conversation or message, you may notice wording or tone more closely than you did in the moment.") },
      { id: "m4a-p44", type: 'paragraph', content: t("That does not automatically mean you were rude; it may simply mean you are reviewing how the interaction came across.") },
      { id: "m4a-h45", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About a Conversation That Went Well?") },
      { id: "m4a-p46", type: 'paragraph', content: t("Positive conversations can stay with you because they felt encouraging, meaningful, funny, validating or unexpectedly good.") },
      { id: "m4a-p47", type: 'paragraph', content: t("Not every recurring thought is something that needs to be reduced.") },
      { id: "m4a-h48", type: 'heading', level: 2, content: t("Why Do Compliments Stay in My Mind?") },
      { id: "m4a-p49", type: 'paragraph', content: t("A compliment may stay with you because it connects to something you care about, confirms effort, surprises you or simply feels meaningful.") },
      { id: "m4a-p50", type: 'paragraph', content: t("Positive words can occupy attention too.") },
      { id: "m4a-h51", type: 'heading', level: 2, content: t("Why Do I Replay Good News in My Head?") },
      { id: "m4a-p52", type: 'paragraph', content: t("Good news can stay mentally active because it creates excitement, pride, anticipation or a desire to share the moment with someone important to you.") },
      { id: "m4a-p53", type: 'paragraph', content: t("Positive reflection is still reflection.") },
      { id: "m4a-h54", type: 'heading', level: 2, content: t("Why Do I Immediately Think of Someone When Something Good Happens?") },
      { id: "m4a-p55", type: 'paragraph', content: t("Positive moments often bring to mind people we associate with support, celebration, connection or shared experience.") },
      { id: "m4a-p56", type: 'paragraph', content: t("That person may feel like a natural part of the good news.") },
      { id: "m4a-h57", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About an Unfinished Conversation?") },
      { id: "m4a-p58", type: 'paragraph', content: t("An unfinished conversation can stay in your thoughts because another response, clarification, decision or action is still expected.") },
      { id: "m4a-p59", type: 'paragraph', content: t("The interaction may have paused while the situation remains open.") },
      { id: "m4a-h60", type: 'heading', level: 2, content: t("Why Do I Think About What I Should Have Said?") },
      { id: "m4a-p61", type: 'paragraph', content: t("You may notice alternative wording after the moment has passed because you now have more time to reflect on what happened.") },
      { id: "m4a-p62", type: 'paragraph', content: t("That does not necessarily mean your original response was wrong.") },
      { id: "m4a-h63", type: 'heading', level: 2, content: t("Why Do I Replay a Conversation With My Manager?") },
      { id: "m4a-p64", type: 'paragraph', content: t("A manager conversation can stay with you when it affects work, feedback, expectations, decisions or what happens next.") },
      { id: "m4a-p65", type: 'paragraph', content: t("It may also matter because professional relationships carry meaning beyond the few minutes of the conversation itself.") },
      { id: "m4a-h66", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About a Client Conversation?") },
      { id: "m4a-p67", type: 'paragraph', content: t("Client conversations can remain active when there are follow-ups, outcomes, expectations or uncertainties attached to them.") },
      { id: "m4a-p68", type: 'paragraph', content: t("You may also replay moments that went especially well because they felt important or satisfying.") },
      { id: "m4a-h69", type: 'heading', level: 2, content: t("Why Do I Think About a Presentation After It’s Over?") },
      { id: "m4a-p70", type: 'paragraph', content: t("A presentation may stay in your thoughts because it involved preparation, attention from others and a result you cared about.") },
      { id: "m4a-p71", type: 'paragraph', content: t("You may remember something you would change, but you may also keep thinking about what went well.") },
      { id: "m4a-h72", type: 'heading', level: 2, content: t("Does Replaying a Conversation Mean I Did Something Wrong?") },
      { id: "m4a-p73", type: 'paragraph', content: t("Not necessarily.") },
      { id: "m4a-p74", type: 'paragraph', content: t("Conversations can replay because they were uncertain, meaningful, unfinished, surprising, positive or simply worth remembering.") },
      { id: "m4a-p75", type: 'paragraph', content: t("The fact that a moment returns to mind does not by itself mean there was a problem.") },
      { id: "m4a-h76", type: 'heading', level: 2, content: t("Is Replaying Conversations the Same as Overthinking?") },
      { id: "m4a-p77", type: 'paragraph', content: t("Not always.") },
      { id: "m4a-p78", type: 'paragraph', content: t("Replaying describes mentally returning to an interaction, while “overthinking” is a broader everyday term people often use when a thought feels repetitive or receives more attention than expected.") },
      { id: "m4a-h79", type: 'heading', level: 2, content: t("Is Replaying a Conversation Always Negative?") },
      { id: "m4a-p80", type: 'paragraph', content: t("No.") },
      { id: "m4a-p81", type: 'paragraph', content: t("People also replay compliments, good news, meaningful conversations, successful presentations and moments that made them feel understood or proud.") },
      { id: "m4a-h82", type: 'heading', level: 2, content: t("Why Do Some Conversations Stay With Me Longer Than Others?") },
      { id: "m4a-p83", type: 'paragraph', content: t("A conversation may stay longer when it feels more important, more uncertain, more personal or more connected to what happens next.") },
      { id: "m4a-p84", type: 'paragraph', content: t("Positive emotional meaning can also make a moment especially memorable.") },
      { id: "m4a-h85", type: 'heading', level: 2, content: t("Why Does One Sentence Stay in My Head?") },
      { id: "m4a-p86", type: 'paragraph', content: t("One sentence can stand out because it felt surprising, meaningful, unclear, encouraging or connected to something you already care about.") },
      { id: "m4a-p87", type: 'paragraph', content: t("Sometimes the smallest part of a conversation carries the most meaning.") },
      { id: "m4a-h88", type: 'heading', level: 2, content: t("How Can I Tell If a Conversation Still Needs My Attention?") },
      { id: "m4a-p89", type: 'paragraph', content: t("Ask whether anything remains unresolved, whether you are waiting for a response, whether you need to clarify something or whether there is a next step.") },
      { id: "m4a-p90", type: 'paragraph', content: t("If there is nothing left to do, the conversation may simply be something you are still reflecting on.") },
      { id: "m4a-h91", type: 'heading', level: 2, content: t("How Can I Reflect Without Analysing Every Word?") },
      { id: "m4a-p92", type: 'paragraph', content: t("Focus on the part that keeps returning and ask what it represents.") },
      { id: "m4a-p93", type: 'paragraph', content: t("You do not need to examine every sentence; sometimes one question is enough: Is there anything here I still need to understand, do, or simply acknowledge?") },
      { id: "m4a-h94", type: 'heading', level: 2, content: t("What Can I Ask Myself When I Keep Replaying a Conversation?") },
      { id: "m4a-p95", type: 'paragraph', content: t("Try asking:") },
      { id: "m4a-p96", type: 'paragraph', content: t("What part keeps returning?") },
      { id: "m4a-p97", type: 'paragraph', content: t("Is anything unfinished?") },
      { id: "m4a-p98", type: 'paragraph', content: t("Am I waiting for a response?") },
      { id: "m4a-p99", type: 'paragraph', content: t("Did something matter more than I expected?") },
      { id: "m4a-p100", type: 'paragraph', content: t("Is there any next step?") },
      { id: "m4a-p101", type: 'paragraph', content: t("Was there something positive I want to remember?") },
      { id: "m4a-h102", type: 'heading', level: 2, content: t("Can Everyday Reflection Be Useful?") },
      { id: "m4a-p103", type: 'paragraph', content: t("Yes.") },
      { id: "m4a-p104", type: 'paragraph', content: t("Reflection can help you notice what mattered, what may still need action and what is simply worth remembering.") },
      { id: "m4a-p105", type: 'paragraph', content: t("It does not have to mean analysing every detail or turning the experience into a problem.") },
      { id: 'm4a-quick', type: 'key_takeaway', title: "Quick Answer", points: [t("Conversations can stay in your thoughts because they are:"), t("Unfinished"), t("Uncertain"), t("Important"), t("Connected to another person"), t("Relevant to what happens next"), t("Positive"), t("or simply:"), t("Meaningful enough to remember"), t("Replaying a conversation does not automatically mean something is wrong.")] },
      { id: "m4a-h106", type: 'heading', level: 2, content: t("A Place for Everyday Conversations") },
      { id: "m4a-p107", type: 'paragraph', content: t("Some conversations need action.") },
      { id: "m4a-p108", type: 'paragraph', content: t("Some need reflection.") },
      { id: "m4a-p109", type: 'paragraph', content: t("Some are simply worth saying out loud.") },
      { id: "m4a-p110", type: 'paragraph', content: t("SOLACE is designed around everyday moments like these, including work conversations, personal decisions, good news and the thoughts that stay with you afterward.") },
      { id: "m4a-p111", type: 'paragraph', content: t("What conversation is still with you today?") },
      { id: "m4a-p112", type: 'paragraph', content: t("Is there something to do?") },
      { id: "m4a-p113", type: 'paragraph', content: t("Something to understand?") },
      { id: "m4a-p114", type: 'paragraph', content: t("Something good to remember?") },
      { id: "m4a-p115", type: 'paragraph', content: t("Or simply something you want to say out loud?") },
      { id: 'm4a-faq', type: 'faq', heading: 'Frequently Asked Questions', items: [{ id: "m4a-faq-1", question: "Why Do I Replay Conversations in My Head?", answer: t("You may replay a conversation when part of it still feels unfinished, unclear, important or connected to what happens next. Sometimes you are thinking about how you were understood. Sometimes you are simply remembering a moment that mattered.") }, { id: "m4a-faq-2", question: "Why Do I Keep Thinking About Something I Said?", answer: t("A sentence may stay in your mind when you are wondering whether it matched what you meant or how the other person may have understood it. That does not automatically mean you said something wrong.") }, { id: "m4a-faq-3", question: "Why Do Work Conversations Stay on My Mind After Work?", answer: t("A work conversation may stay active because there is still a task, decision, response, follow-up or meaning connected to it. Positive work moments can stay with you too, including praise, good feedback or a presentation that went well.") }, { id: "m4a-faq-4", question: "Why Do I Replay a Text Message?", answer: t("Texts can stay mentally active when tone feels unclear, the response is still pending or you are thinking about how your own message was understood. Because text removes some face-to-face cues, small wording details can feel more noticeable.") }, { id: "m4a-faq-5", question: "Why Do I Rehearse Conversations Before They Happen?", answer: t("People often mentally prepare when they care about what they want to say or do not know exactly how the other person will respond. The preparation may last much longer than the actual conversation.") }, { id: "m4a-faq-6", question: "Is Replaying a Conversation Always Negative?", answer: t("No. People also replay compliments, good news, meaningful conversations, successful presentations and moments that made them feel understood or proud.") }, { id: "m4a-faq-7", question: "Does Replaying a Conversation Mean I Did Something Wrong?", answer: t("Not necessarily. Conversations can replay because they were uncertain, meaningful, unfinished, surprising, positive or simply worth remembering. The fact that a moment returns to mind does not by itself mean there was a problem.") }] },
      { id: 'm4a-cta', type: 'cta', label: "Explore more everyday reflection resources from SOLACE.", target: { kind: 'route', value: 'resource_library' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W4-B001', anchorText: 'why conversations keep replaying in your head', relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W4-G001', anchorText: 'everyday reflection and why conversations stay with us', relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W3-A001', anchorText: 'common questions about everyday overthinking', relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'resource_library', anchorText: "Explore more everyday reflection resources from SOLACE.", relation: 'resource_library' },
  ],

  authoredOutsideWorkbook: ['cta block (label and destination from the workbook PART 49 optional CTA)'],
  missingFields: [
    'safety_notice (the workbook supplies no reader-facing crisis or disclaimer copy)',
    'seo_title (no schema field distinct from title)',
    'workbook references left UNLINKED: M2-W4-L001 (no Content Hub record), Journal (no registered public route)',
  ],
};

/** The three Month 2 Week 4 assets, in workbook order. */
export const M2W4_ASSETS: M2W4Asset[] = [M2_W4_B001, M2_W4_G001, M2_W4_A001];

/**
 * Content-to-content edges the workbook states explicitly.
 *
 * B001\'s INTERNAL LINKING PLAN names G001 and A001 with anchors; G001 PART 44 names "To B001",
 * "To A001" and "To M2-W3-G001"; A001 PART 45 names "To B001", "To G001" and "To Week 3 A001".
 * No edge is inferred from shared-week membership, and the L001 references in all three are
 * skipped because no Content Hub record exists for them.
 */
export const EXPECTED_CONTENT_EDGES: Array<[string, string]> = [
  ['M2-W4-B001', 'M2-W4-G001'],
  ['M2-W4-B001', 'M2-W4-A001'],
  ['M2-W4-G001', 'M2-W4-B001'],
  ['M2-W4-G001', 'M2-W4-A001'],
  ['M2-W4-G001', 'M2-W3-G001'],
  ['M2-W4-A001', 'M2-W4-B001'],
  ['M2-W4-A001', 'M2-W4-G001'],
  ['M2-W4-A001', 'M2-W3-A001'],
];
