/**
 * Month 2 Week 2 workbook -> Content Hub mapping.
 *
 * SOURCE: `Month 2 Week 2 Operational WorkBook.docx`.
 * Authority theme: attention switching, mental load and everyday wellbeing.
 *
 * ============================================================================
 * EVERY STRING OF PROSE BELOW IS THE WORKBOOK'S OWN WORDING.
 * ============================================================================
 *
 * Transcribed mechanically by `scripts/content-hub/m2w2-generate.py`. No sentence was rewritten,
 * shortened, paraphrased, reordered or expanded. Regenerating from the same workbook reproduces
 * this file byte for byte.
 *
 * PUBLIC RANGES ONLY. B001 §11-§17, G001 §7-§11, A001 §6, §7-§24, §25-§27. Every other section —
 * asset information, strategy, search intent, keyword maps, internal linking plans, image briefs,
 * alt text, structured-data direction, social derivatives, publishing plans, performance
 * measurement, QA and approval checklists — is operational and is NOT in the public body.
 *
 * STRUCTURAL MAPPINGS, all source-faithful:
 *   - B001 Featured Answer -> `key_takeaway` (question as title, answer as its single point).
 *     `direct_answer` is restricted to `aeo_answer`, so it cannot be used on a `seo_blog`; the
 *     takeaway block is the existing mechanism that renders a highlighted answer near the top.
 *   - A001 Featured Answer -> the single `direct_answer` at block[0], with the workbook's
 *     "Supporting sentence" kept as the paragraph that follows it. Neither is merged or dropped.
 *   - G001's twelve Key Statements go to `type_fields.key_statements` ONLY. They are identified
 *     in the workbook as machine-readable citation statements, and the finished reader-facing GEO
 *     resource does not present them as body copy, so they are not duplicated as blocks.
 *
 * DELIBERATELY ABSENT:
 *   - `safety_notice` on all three. The workbook's §26/§20/§40 safety sections are "DO NOT SAY"
 *     guardrails for writers, not reader-facing safety copy, and safety copy is never invented.
 *   - Links to Journal, Mood, Brain Health, Habits, Progress and Wellness Tools. Those exist only
 *     behind authentication at `/app/*` and `ROUTE_REGISTRY` excludes authenticated destinations.
 *   - The article deck / page excerpt. The Content Hub schema has no excerpt field.
 *   - Any Content Hub link to M2-W2-L001, which is a LinkedIn asset with no Content Hub URL.
 */

import type { Week1Asset, Week1LinkSpec } from '../week1/week1-content';
import type { ContentBody, InlineContent } from '@meetezri/shared';

/** A span of plain text. */
const t = (text: string): InlineContent => [{ text }];

/** Month 2 Week 2 reuses the Week 1 asset and link contracts EXACTLY. */
export type M2W2LinkSpec = Week1LinkSpec;
export type M2W2Asset = Week1Asset;

// ─────────────────────────────────────────────────────────────────────────────
// M2-W2-B001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W2_B001: M2W2Asset = {
  editorialRef: "M2-W2-B001",
  contentType: 'seo_blog',
  publicLabel: 'Article',
  title: "Why Does My Mind Still Feel Busy When the Day Is Over?",
  slug: "why-does-my-mind-feel-so-busy",
  metaDescription: "Why does your mind still feel busy after the day ends? Explore common everyday reasons and simple ways to create more space to reflect.",
  week: 2,
  pillar: 'Attention, Mental Load and Everyday Wellbeing',
  tags: ['attention-switching', 'mental-load', 'everyday-wellbeing', 'month-2', 'week-2'],

  typeFields: {
    keywords: {
      primary: 'why does my mind feel so busy',
      secondary: ['busy mind', 'mental load', 'attention switching', 'racing thoughts at night'],
    },
    funnel_stage: 'Awareness',
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'SEO Blog / Website Resource for the Week 2 authority cluster.',
    goal: 'Organic search authority for a busy mind, attention switching and mental load.',
    // The workbook distinguishes the public H1 from the SEO title; the schema has no separate
    // SEO-title field, so the approved value is recorded here rather than dropped.
    seo_title_note: "Why Does My Mind Feel So Busy? 7 Everyday Reasons",
    // The workbook supplies an article deck/excerpt; the schema has no excerpt field.
    excerpt_note: "A full day can end while your thoughts keep moving. Here are some everyday reasons your mind may still feel busy—and ways to create a little more room to reflect.",
  },

  body: {
    version: 1,
    blocks: [
      { id: 'm2w2b-featured', type: 'key_takeaway', title: "Why does my mind still feel busy at the end of the day?", points: [t("Your mind may still feel busy because your attention has moved between many tasks, conversations, decisions and responsibilities throughout the day. Unfinished thoughts, anticipation about what comes next, or finally having quiet time to reflect can also bring thoughts to the surface. A busy mind does not always mean something is wrong; sometimes it simply reflects how much has been asking for your attention.")] },
      { id: "m2w2b-p1", type: 'paragraph', content: t("The day is technically finished.") },
      { id: "m2w2b-p2", type: 'paragraph', content: t("Your laptop is closed.") },
      { id: "m2w2b-p3", type: 'paragraph', content: t("The meeting ended hours ago.") },
      { id: "m2w2b-p4", type: 'paragraph', content: t("The messages have slowed down.") },
      { id: "m2w2b-p5", type: 'paragraph', content: t("Maybe you've finished dinner, changed clothes, taken a shower or finally climbed into bed.") },
      { id: "m2w2b-p6", type: 'paragraph', content: t("And then your mind seems to get busier.") },
      { id: "m2w2b-p7", type: 'paragraph', content: t("You remember something you forgot to do.") },
      { id: "m2w2b-p8", type: 'paragraph', content: t("You replay part of a conversation.") },
      { id: "m2w2b-p9", type: 'paragraph', content: t("You think about tomorrow.") },
      { id: "m2w2b-p10", type: 'paragraph', content: t("You reconsider a decision.") },
      { id: "m2w2b-p11", type: 'paragraph', content: t("You remember something someone said.") },
      { id: "m2w2b-p12", type: 'paragraph', content: t("Or you finally start thinking about something you simply didn't have time to think about earlier.") },
      { id: "m2w2b-p13", type: 'paragraph', content: t("It can leave you wondering:") },
      { id: "m2w2b-h14", type: 'heading', level: 2, content: t("Why does my mind still feel so busy when the day itself is over?") },
      { id: "m2w2b-p15", type: 'paragraph', content: t("There isn't always one explanation.") },
      { id: "m2w2b-p16", type: 'paragraph', content: t("Sometimes a day can feel mentally full because of how much happened.") },
      { id: "m2w2b-p17", type: 'paragraph', content: t("Sometimes it's because of how often your attention moved.") },
      { id: "m2w2b-p18", type: 'paragraph', content: t("Sometimes thoughts that had nowhere to go during the day finally have room to surface when life becomes quieter.") },
      { id: "m2w2b-p19", type: 'paragraph', content: t("And sometimes you're simply still thinking about a life that contains a lot worth thinking about.") },
      { id: "m2w2b-h20", type: 'heading', level: 2, content: t("A busy mind doesn't automatically mean something is wrong") },
      { id: "m2w2b-p21", type: 'paragraph', content: t("When people hear the words “busy mind,” it's easy to assume they describe something negative.") },
      { id: "m2w2b-p22", type: 'paragraph', content: t("But thoughts don't only stay active because you're worried.") },
      { id: "m2w2b-p23", type: 'paragraph', content: t("You might be thinking about:") },
      { id: "m2w2b-list24", type: 'list', style: 'bullet', items: [t("A presentation that went better than expected."), t("An idea you're excited about."), t("A conversation you want to continue."), t("A decision you haven't made yet."), t("Something funny that happened."), t("A project you're looking forward to."), t("A person you miss."), t("Something you accomplished."), t("Tomorrow's plans."), t("A problem you still want to solve.")] },
      { id: "m2w2b-p25", type: 'paragraph', content: t("Your thoughts can be active because you're processing, anticipating, reflecting, remembering or imagining.") },
      { id: "m2w2b-p26", type: 'paragraph', content: t("The useful question isn't always:") },
      { id: "m2w2b-h27", type: 'heading', level: 2, content: t("“How do I stop thinking?”") },
      { id: "m2w2b-p28", type: 'paragraph', content: t("Sometimes it may be:") },
      { id: "m2w2b-h29", type: 'heading', level: 2, content: t("“What is my mind still trying to give attention to?”") },
      { id: "m2w2b-h30", type: 'heading', level: 2, content: t("1. Your attention may have been switching all day") },
      { id: "m2w2b-p31", type: 'paragraph', content: t("Think about an ordinary weekday.") },
      { id: "m2w2b-p32", type: 'paragraph', content: t("You begin one task.") },
      { id: "m2w2b-p33", type: 'paragraph', content: t("A message arrives.") },
      { id: "m2w2b-p34", type: 'paragraph', content: t("You reply.") },
      { id: "m2w2b-p35", type: 'paragraph', content: t("You return.") },
      { id: "m2w2b-p36", type: 'paragraph', content: t("Someone asks a question.") },
      { id: "m2w2b-p37", type: 'paragraph', content: t("You answer.") },
      { id: "m2w2b-p38", type: 'paragraph', content: t("Back to the task.") },
      { id: "m2w2b-p39", type: 'paragraph', content: t("An email appears.") },
      { id: "m2w2b-p40", type: 'paragraph', content: t("Then a meeting.") },
      { id: "m2w2b-p41", type: 'paragraph', content: t("Then another task.") },
      { id: "m2w2b-p42", type: 'paragraph', content: t("Then a phone call.") },
      { id: "m2w2b-p43", type: 'paragraph', content: t("Then something you need to remember for later.") },
      { id: "m2w2b-p44", type: 'paragraph', content: t("Nothing about that day necessarily sounds extraordinary.") },
      { id: "m2w2b-p45", type: 'paragraph', content: t("But your attention has moved repeatedly.") },
      { id: "m2w2b-p46", type: 'paragraph', content: t("Sometimes the tiring part of a full day isn't only how much you did.") },
      { id: "m2w2b-p47", type: 'paragraph', content: t("It's how often you had to move from one thing to another.") },
      { id: "m2w2b-p48", type: 'paragraph', content: t("And when the day finally becomes quieter, you may notice how little uninterrupted space there was to simply stay with one thought.") },
      { id: "m2w2b-h49", type: 'heading', level: 2, content: t("2. Some thoughts never got their turn") },
      { id: "m2w2b-p50", type: 'paragraph', content: t("Imagine something happens at 11:00 AM.") },
      { id: "m2w2b-p51", type: 'paragraph', content: t("Maybe someone says something that makes you think.") },
      { id: "m2w2b-p52", type: 'paragraph', content: t("But you have another meeting.") },
      { id: "m2w2b-p53", type: 'paragraph', content: t("Then lunch.") },
      { id: "m2w2b-p54", type: 'paragraph', content: t("Then work.") },
      { id: "m2w2b-p55", type: 'paragraph', content: t("Then an errand.") },
      { id: "m2w2b-p56", type: 'paragraph', content: t("Then someone needs something.") },
      { id: "m2w2b-p57", type: 'paragraph', content: t("You never deliberately decided not to think about what happened.") },
      { id: "m2w2b-p58", type: 'paragraph', content: t("There simply wasn't much room.") },
      { id: "m2w2b-p59", type: 'paragraph', content: t("Later that evening, the day becomes quiet.") },
      { id: "m2w2b-p60", type: 'paragraph', content: t("And suddenly the thought returns.") },
      { id: "m2w2b-p61", type: 'paragraph', content: t("That doesn't necessarily mean the thought became more important at night.") },
      { id: "m2w2b-p62", type: 'paragraph', content: t("It may simply be the first moment when it had enough space to be noticed.") },
      { id: "m2w2b-p63", type: 'paragraph', content: t("This is one reason quiet moments can sometimes feel mentally louder than busy ones.") },
      { id: "m2w2b-h64", type: 'heading', level: 2, content: t("3. You may still have open decisions") },
      { id: "m2w2b-p65", type: 'paragraph', content: t("Not every thought occupying attention is a major life decision.") },
      { id: "m2w2b-p66", type: 'paragraph', content: t("Sometimes it's:") },
      { id: "m2w2b-p67", type: 'paragraph', content: t("Should I reply tonight or tomorrow?") },
      { id: "m2w2b-p68", type: 'paragraph', content: t("When am I going to book that appointment?") },
      { id: "m2w2b-p69", type: 'paragraph', content: t("What should I make this weekend?") },
      { id: "m2w2b-p70", type: 'paragraph', content: t("Should I say yes to that invitation?") },
      { id: "m2w2b-p71", type: 'paragraph', content: t("Do I need to order that?") },
      { id: "m2w2b-p72", type: 'paragraph', content: t("When am I going to finish that task?") },
      { id: "m2w2b-p73", type: 'paragraph', content: t("Should I bring that up again?") },
      { id: "m2w2b-p74", type: 'paragraph', content: t("Each question may be small.") },
      { id: "m2w2b-p75", type: 'paragraph', content: t("But when several remain unresolved, they can continue appearing in your thoughts.") },
      { id: "m2w2b-p76", type: 'paragraph', content: t("You don't necessarily need to solve all of them immediately.") },
      { id: "m2w2b-p77", type: 'paragraph', content: t("Sometimes simply noticing what is still open can make the day easier to understand.") },
      { id: "m2w2b-h78", type: 'heading', level: 2, content: t("4. You may be mentally living in what's next") },
      { id: "m2w2b-p79", type: 'paragraph', content: t("The current day can be over while part of your attention has already moved into tomorrow.") },
      { id: "m2w2b-p80", type: 'paragraph', content: t("The meeting.") },
      { id: "m2w2b-p81", type: 'paragraph', content: t("The school run.") },
      { id: "m2w2b-p82", type: 'paragraph', content: t("The appointment.") },
      { id: "m2w2b-p83", type: 'paragraph', content: t("The deadline.") },
      { id: "m2w2b-p84", type: 'paragraph', content: t("The trip.") },
      { id: "m2w2b-p85", type: 'paragraph', content: t("The conversation.") },
      { id: "m2w2b-p86", type: 'paragraph', content: t("The presentation.") },
      { id: "m2w2b-p87", type: 'paragraph', content: t("The thing you're excited about.") },
      { id: "m2w2b-p88", type: 'paragraph', content: t("The thing you're unsure about.") },
      { id: "m2w2b-p89", type: 'paragraph', content: t("Anticipation isn't always negative.") },
      { id: "m2w2b-p90", type: 'paragraph', content: t("We think ahead because future events matter to us.") },
      { id: "m2w2b-p91", type: 'paragraph', content: t("But if your attention spends much of the evening rehearsing tomorrow, tonight can begin to feel like an extension of the next day's responsibilities.") },
      { id: "m2w2b-p92", type: 'paragraph', content: t("A useful reflection can be:") },
      { id: "m2w2b-h93", type: 'heading', level: 2, content: t("“Is there anything I actually need to do about this tonight?”") },
      { id: "m2w2b-p94", type: 'paragraph', content: t("Sometimes the answer is yes.") },
      { id: "m2w2b-p95", type: 'paragraph', content: t("Sometimes the answer is:") },
      { id: "m2w2b-h96", type: 'heading', level: 2, content: t("Not yet.") },
      { id: "m2w2b-h97", type: 'heading', level: 2, content: t("5. You may still be replaying something that's already finished") },
      { id: "m2w2b-p98", type: 'paragraph', content: t("Attention doesn't only move forward.") },
      { id: "m2w2b-p99", type: 'paragraph', content: t("It moves backward too.") },
      { id: "m2w2b-p100", type: 'paragraph', content: t("You might replay:") },
      { id: "m2w2b-p101", type: 'paragraph', content: t("Something you said.") },
      { id: "m2w2b-p102", type: 'paragraph', content: t("Something someone else said.") },
      { id: "m2w2b-p103", type: 'paragraph', content: t("A meeting.") },
      { id: "m2w2b-p104", type: 'paragraph', content: t("A presentation.") },
      { id: "m2w2b-p105", type: 'paragraph', content: t("A decision.") },
      { id: "m2w2b-p106", type: 'paragraph', content: t("A mistake.") },
      { id: "m2w2b-p107", type: 'paragraph', content: t("A good moment.") },
      { id: "m2w2b-p108", type: 'paragraph', content: t("A compliment.") },
      { id: "m2w2b-p109", type: 'paragraph', content: t("Something awkward.") },
      { id: "m2w2b-p110", type: 'paragraph', content: t("Something you're proud of.") },
      { id: "m2w2b-p111", type: 'paragraph', content: t("Sometimes we replay events because we're trying to understand them.") },
      { id: "m2w2b-p112", type: 'paragraph', content: t("Sometimes because we wish they had gone differently.") },
      { id: "m2w2b-p113", type: 'paragraph', content: t("And sometimes because they mattered.") },
      { id: "m2w2b-p114", type: 'paragraph', content: t("If you notice yourself returning to something that has already happened, try shifting from simply replaying it to reflecting on it.") },
      { id: "m2w2b-p115", type: 'paragraph', content: t("For example:") },
      { id: "m2w2b-h116", type: 'heading', level: 2, content: t("What am I actually thinking about here?") },
      { id: "m2w2b-h117", type: 'heading', level: 2, content: t("Is there something I want to understand?") },
      { id: "m2w2b-h118", type: 'heading', level: 2, content: t("Is there something I want to do differently?") },
      { id: "m2w2b-h119", type: 'heading', level: 2, content: t("Is there something I handled well?") },
      { id: "m2w2b-p120", type: 'paragraph', content: t("That last question matters too.") },
      { id: "m2w2b-p121", type: 'paragraph', content: t("Reflection doesn't only have to search for problems.") },
      { id: "m2w2b-h122", type: 'heading', level: 2, content: t("6. Everything may have been getting your attention except you") },
      { id: "m2w2b-p123", type: 'paragraph', content: t("Work needed something.") },
      { id: "m2w2b-p124", type: 'paragraph', content: t("People needed something.") },
      { id: "m2w2b-p125", type: 'paragraph', content: t("Your phone needed checking.") },
      { id: "m2w2b-p126", type: 'paragraph', content: t("The calendar needed following.") },
      { id: "m2w2b-p127", type: 'paragraph', content: t("Dinner needed making.") },
      { id: "m2w2b-p128", type: 'paragraph', content: t("Plans needed organizing.") },
      { id: "m2w2b-p129", type: 'paragraph', content: t("The day kept moving.") },
      { id: "m2w2b-p130", type: 'paragraph', content: t("You kept responding.") },
      { id: "m2w2b-p131", type: 'paragraph', content: t("Then everything became quiet.") },
      { id: "m2w2b-p132", type: 'paragraph', content: t("And your own thoughts finally got a turn.") },
      { id: "m2w2b-p133", type: 'paragraph', content: t("This doesn't mean the other things weren't important.") },
      { id: "m2w2b-p134", type: 'paragraph', content: t("They may have been genuinely important.") },
      { id: "m2w2b-p135", type: 'paragraph', content: t("But there is a difference between giving attention to your responsibilities and never leaving any attention for your own experience of them.") },
      { id: "m2w2b-p136", type: 'paragraph', content: t("Sometimes a busy mind at the end of the day is an invitation to ask:") },
      { id: "m2w2b-h137", type: 'heading', level: 2, content: t("“What have I not had a chance to hear from myself yet?”") },
      { id: "m2w2b-h138", type: 'heading', level: 2, content: t("7. You may simply have had a full day") },
      { id: "m2w2b-p139", type: 'paragraph', content: t("Not every busy mind needs to become a problem to solve.") },
      { id: "m2w2b-p140", type: 'paragraph', content: t("Sometimes life was simply full.") },
      { id: "m2w2b-p141", type: 'paragraph', content: t("You learned something.") },
      { id: "m2w2b-p142", type: 'paragraph', content: t("Handled something.") },
      { id: "m2w2b-p143", type: 'paragraph', content: t("Saw someone.") },
      { id: "m2w2b-p144", type: 'paragraph', content: t("Made decisions.") },
      { id: "m2w2b-p145", type: 'paragraph', content: t("Had conversations.") },
      { id: "m2w2b-p146", type: 'paragraph', content: t("Made progress.") },
      { id: "m2w2b-p147", type: 'paragraph', content: t("Changed your mind.") },
      { id: "m2w2b-p148", type: 'paragraph', content: t("Got good news.") },
      { id: "m2w2b-p149", type: 'paragraph', content: t("Received disappointing news.") },
      { id: "m2w2b-p150", type: 'paragraph', content: t("Started something.") },
      { id: "m2w2b-p151", type: 'paragraph', content: t("Finished something.") },
      { id: "m2w2b-p152", type: 'paragraph', content: t("Thought about what comes next.") },
      { id: "m2w2b-p153", type: 'paragraph', content: t("A full day can leave a lot behind to process.") },
      { id: "m2w2b-p154", type: 'paragraph', content: t("Sometimes the most useful response isn't immediately trying to empty your mind.") },
      { id: "m2w2b-p155", type: 'paragraph', content: t("It is giving yourself somewhere for those thoughts to go.") },
      { id: "m2w2b-p156", type: 'paragraph', content: t("What can you do when your mind still feels busy?") },
      { id: "m2w2b-p157", type: 'paragraph', content: t("There isn't one approach that works for every person or every day.") },
      { id: "m2w2b-p158", type: 'paragraph', content: t("But a few simple options can create room to notice what's occupying your attention.") },
      { id: "m2w2b-p159", type: 'paragraph', content: t("1. Ask what is actually still on your mind") },
      { id: "m2w2b-p160", type: 'paragraph', content: t("Instead of:") },
      { id: "m2w2b-h161", type: 'heading', level: 2, content: t("“Why can't I switch off?”") },
      { id: "m2w2b-p162", type: 'paragraph', content: t("Try:") },
      { id: "m2w2b-h163", type: 'heading', level: 2, content: t("“What am I still thinking about?”") },
      { id: "m2w2b-p164", type: 'paragraph', content: t("The second question is more specific.") },
      { id: "m2w2b-p165", type: 'paragraph', content: t("2. Write down what's still open") },
      { id: "m2w2b-p166", type: 'paragraph', content: t("This could be:") },
      { id: "m2w2b-p167", type: 'paragraph', content: t("Something to remember.") },
      { id: "m2w2b-p168", type: 'paragraph', content: t("A decision.") },
      { id: "m2w2b-p169", type: 'paragraph', content: t("A question.") },
      { id: "m2w2b-p170", type: 'paragraph', content: t("A task.") },
      { id: "m2w2b-p171", type: 'paragraph', content: t("An idea.") },
      { id: "m2w2b-p172", type: 'paragraph', content: t("A thought you want to revisit.") },
      { id: "m2w2b-p173", type: 'paragraph', content: t("You don't have to resolve it.") },
      { id: "m2w2b-p174", type: 'paragraph', content: t("Sometimes recording it is enough to stop relying on yourself to keep remembering it.") },
      { id: "m2w2b-p175", type: 'paragraph', content: t("3. Notice whether you're thinking forward or backward") },
      { id: "m2w2b-p176", type: 'paragraph', content: t("Ask:") },
      { id: "m2w2b-h177", type: 'heading', level: 2, content: t("Am I preparing for something that hasn't happened yet?") },
      { id: "m2w2b-p178", type: 'paragraph', content: t("Or:") },
      { id: "m2w2b-h179", type: 'heading', level: 2, content: t("Am I replaying something that already happened?") },
      { id: "m2w2b-p180", type: 'paragraph', content: t("That distinction can help you understand what your attention is doing.") },
      { id: "m2w2b-p181", type: 'paragraph', content: t("4. Give yourself credit for what went well") },
      { id: "m2w2b-p182", type: 'paragraph', content: t("A busy mind can quickly move from:") },
      { id: "m2w2b-h183", type: 'heading', level: 2, content: t("What happened?") },
      { id: "m2w2b-p184", type: 'paragraph', content: t("to:") },
      { id: "m2w2b-h185", type: 'heading', level: 2, content: t("What's next?") },
      { id: "m2w2b-p186", type: 'paragraph', content: t("Before doing that, notice:") },
      { id: "m2w2b-p187", type: 'paragraph', content: t("What did you finish?") },
      { id: "m2w2b-p188", type: 'paragraph', content: t("What did you handle?") },
      { id: "m2w2b-p189", type: 'paragraph', content: t("What did you learn?") },
      { id: "m2w2b-p190", type: 'paragraph', content: t("What went better than expected?") },
      { id: "m2w2b-p191", type: 'paragraph', content: t("What are you proud of?") },
      { id: "m2w2b-p192", type: 'paragraph', content: t("Progress deserves reflection too.") },
      { id: "m2w2b-p193", type: 'paragraph', content: t("5. Create a small transition") },
      { id: "m2w2b-p194", type: 'paragraph', content: t("You don't necessarily need an elaborate evening routine.") },
      { id: "m2w2b-p195", type: 'paragraph', content: t("A transition might be:") },
      { id: "m2w2b-p196", type: 'paragraph', content: t("Changing clothes after work.") },
      { id: "m2w2b-p197", type: 'paragraph', content: t("Walking around the block.") },
      { id: "m2w2b-p198", type: 'paragraph', content: t("Putting the laptop away.") },
      { id: "m2w2b-p199", type: 'paragraph', content: t("Taking a shower.") },
      { id: "m2w2b-p200", type: 'paragraph', content: t("Making dinner without checking work.") },
      { id: "m2w2b-p201", type: 'paragraph', content: t("Writing for five minutes.") },
      { id: "m2w2b-p202", type: 'paragraph', content: t("Sitting somewhere for a moment before moving into the next part of the day.") },
      { id: "m2w2b-p203", type: 'paragraph', content: t("The purpose isn't to perform the perfect routine.") },
      { id: "m2w2b-p204", type: 'paragraph', content: t("It's simply to create a small distinction between what just happened and what comes next.") },
      { id: "m2w2b-p205", type: 'paragraph', content: t("6. Talk something through") },
      { id: "m2w2b-p206", type: 'paragraph', content: t("Some thoughts become clearer once they're expressed.") },
      { id: "m2w2b-p207", type: 'paragraph', content: t("You don't necessarily need to know exactly what you want to say before starting.") },
      { id: "m2w2b-p208", type: 'paragraph', content: t("Sometimes:") },
      { id: "m2w2b-h209", type: 'heading', level: 2, content: t("“I don't really know where to start…”") },
      { id: "m2w2b-p210", type: 'paragraph', content: t("is enough of a start.") },
      { id: "m2w2b-p211", type: 'paragraph', content: t("Talking something through can give a thought somewhere to go besides continuing to circle internally.") },
      { id: "m2w2b-p212", type: 'paragraph', content: t("Why do I think about everything at night?") },
      { id: "m2w2b-p213", type: 'paragraph', content: t("Night may be one of the first times during the day when fewer things are competing for your attention.") },
      { id: "m2w2b-p214", type: 'paragraph', content: t("There may be fewer conversations.") },
      { id: "m2w2b-p215", type: 'paragraph', content: t("Fewer tasks.") },
      { id: "m2w2b-p216", type: 'paragraph', content: t("Fewer places to go.") },
      { id: "m2w2b-p217", type: 'paragraph', content: t("Fewer immediate responses required.") },
      { id: "m2w2b-p218", type: 'paragraph', content: t("That quieter environment can make thoughts that were already present easier to notice.") },
      { id: "m2w2b-p219", type: 'paragraph', content: t("This doesn't necessarily mean nighttime created those thoughts.") },
      { id: "m2w2b-p220", type: 'paragraph', content: t("You may simply be hearing them more clearly.") },
      { id: "m2w2b-p221", type: 'paragraph', content: t("That's also why the goal doesn't always have to be:") },
      { id: "m2w2b-h222", type: 'heading', level: 2, content: t("“How do I make my mind completely empty?”") },
      { id: "m2w2b-p223", type: 'paragraph', content: t("A more useful question might be:") },
      { id: "m2w2b-h224", type: 'heading', level: 2, content: t("“Is there something here I need to acknowledge, record, reflect on or come back to?”") },
      { id: "m2w2b-p225", type: 'paragraph', content: t("Not everything needs to become “right now”") },
      { id: "m2w2b-p226", type: 'paragraph', content: t("Sometimes mental space starts earlier in the day.") },
      { id: "m2w2b-p227", type: 'paragraph', content: t("A notification appears.") },
      { id: "m2w2b-p228", type: 'paragraph', content: t("A request comes in.") },
      { id: "m2w2b-p229", type: 'paragraph', content: t("Something occurs to you.") },
      { id: "m2w2b-p230", type: 'paragraph', content: t("Before automatically switching, you can ask:") },
      { id: "m2w2b-h231", type: 'heading', level: 2, content: t("Does this need me now?") },
      { id: "m2w2b-h232", type: 'heading', level: 2, content: t("Does it need me today?") },
      { id: "m2w2b-h233", type: 'heading', level: 2, content: t("Can it wait?") },
      { id: "m2w2b-h234", type: 'heading', level: 2, content: t("Can someone else handle it?") },
      { id: "m2w2b-h235", type: 'heading', level: 2, content: t("Am I checking automatically?") },
      { id: "m2w2b-h236", type: 'heading', level: 2, content: t("What am I already doing?") },
      { id: "m2w2b-h237", type: 'heading', level: 2, content: t("What deserves my attention next?") },
      { id: "m2w2b-p238", type: 'paragraph', content: t("These questions aren't about ignoring responsibilities.") },
      { id: "m2w2b-p239", type: 'paragraph', content: t("They're about noticing that not everything necessarily deserves the same amount of attention at the same moment.") },
      { id: "m2w2b-p240", type: 'paragraph', content: t("Making room for your own thoughts") },
      { id: "m2w2b-p241", type: 'paragraph', content: t("SOLACE was built around a simple idea:") },
      { id: "m2w2b-p242", type: 'paragraph', content: t("People need space to talk through what they're carrying.") },
      { id: "m2w2b-p243", type: 'paragraph', content: t("And what you're carrying doesn't have to be a crisis.") },
      { id: "m2w2b-p244", type: 'paragraph', content: t("It can be:") },
      { id: "m2w2b-p245", type: 'paragraph', content: t("A decision.") },
      { id: "m2w2b-p246", type: 'paragraph', content: t("An idea.") },
      { id: "m2w2b-p247", type: 'paragraph', content: t("A full day.") },
      { id: "m2w2b-p248", type: 'paragraph', content: t("Something you're proud of.") },
      { id: "m2w2b-p249", type: 'paragraph', content: t("Something you're uncertain about.") },
      { id: "m2w2b-p250", type: 'paragraph', content: t("Something you're looking forward to.") },
      { id: "m2w2b-p251", type: 'paragraph', content: t("Something you keep replaying.") },
      { id: "m2w2b-p252", type: 'paragraph', content: t("Or simply a thought you haven't had room to finish yet.") },
      { id: "m2w2b-p253", type: 'paragraph', content: t("Sometimes the day doesn't need fixing.") },
      { id: "m2w2b-p254", type: 'paragraph', content: t("Sometimes you just need somewhere to hear yourself think.") },
      { id: "m2w2b-p255", type: 'paragraph', content: t("SOLACE creates different ways to pause, notice, reflect and understand your everyday experiences—whether through conversation, journaling, mood awareness, habits, progress or other wellbeing tools.") },
      { id: "m2w2b-p256", type: 'paragraph', content: t("Because your thoughts deserve somewhere to go too.") },
      { id: "m2w2b-p257", type: 'paragraph', content: t("The end of the day doesn't always mean the end of your thoughts.") },
      { id: "m2w2b-p258", type: 'paragraph', content: t("Your attention may still be catching up with everything the day contained.") },
      { id: "m2w2b-p259", type: 'paragraph', content: t("Instead of immediately asking:") },
      { id: "m2w2b-h260", type: 'heading', level: 2, content: t("“How do I stop thinking?”") },
      { id: "m2w2b-p261", type: 'paragraph', content: t("you might begin with:") },
      { id: "m2w2b-h262", type: 'heading', level: 2, content: t("“What still has my attention?”") },
      { id: "m2w2b-p263", type: 'paragraph', content: t("Maybe it's work.") },
      { id: "m2w2b-p264", type: 'paragraph', content: t("Maybe it's tomorrow.") },
      { id: "m2w2b-p265", type: 'paragraph', content: t("Maybe it's a conversation.") },
      { id: "m2w2b-p266", type: 'paragraph', content: t("Maybe it's something unfinished.") },
      { id: "m2w2b-p267", type: 'paragraph', content: t("Maybe it's something exciting.") },
      { id: "m2w2b-p268", type: 'paragraph', content: t("Maybe it's something that went better than expected.") },
      { id: "m2w2b-p269", type: 'paragraph', content: t("Whatever it is, noticing it can be the beginning of understanding it.") },
      { id: "m2w2b-p270", type: 'paragraph', content: t("You spend a lot of your day giving attention to the world around you.") },
      { id: "m2w2b-p271", type: 'paragraph', content: t("It's okay to leave a little for yourself too.") },
      { id: 'm2w2b-faq', type: 'faq', heading: 'Frequently Asked Questions', items: [{ id: "m2w2b-faq-1", question: "Why does my mind feel busy even when I'm not doing anything?", answer: t("Your attention may still be occupied by unfinished thoughts, decisions, upcoming events, previous conversations or experiences from earlier in the day. Quiet moments can also make thoughts easier to notice because fewer external demands are competing for your attention.") }, { id: "m2w2b-faq-2", question: "Why do I think about work after work?", answer: t("Work-related thoughts can continue after the workday when you're thinking about unfinished tasks, upcoming responsibilities, decisions or conversations. You may also notice these thoughts more clearly once the workday becomes quieter.") }, { id: "m2w2b-faq-3", question: "Why do I think about everything when I go to bed?", answer: t("Bedtime may be one of the first quiet periods in your day. With fewer external demands competing for attention, thoughts about the day, tomorrow or unresolved decisions may become easier to notice.") }, { id: "m2w2b-faq-4", question: "How can I create more mental space after a busy day?", answer: t("You can experiment with simple transitions such as writing down open thoughts, taking a short walk, changing environments, reflecting on the day or talking something through. Different approaches work for different people.") }, { id: "m2w2b-faq-5", question: "Does everything that feels urgent need immediate attention?", answer: t("No. Some things genuinely require an immediate response, but others may reasonably be handled later. Asking whether something needs attention now, today or at another appropriate time can help separate urgency from simple recency.") }, { id: "m2w2b-faq-6", question: "Can reflection help after a busy day?", answer: t("Reflection can give you an opportunity to notice what happened, what remains unfinished, what mattered and what you handled well. It doesn't need to involve solving every thought or problem.") }] },
      { id: 'm2w2b-cta', type: 'cta', label: 'Talk It Out', target: { kind: 'route', value: 'product.talk_it_out' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W2-G001', anchorText: null, relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W2-A001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'product.talk_it_out', anchorText: 'Talk It Out', relation: 'product' },
  ],

  authoredOutsideWorkbook: ['featured answer mapped to a key_takeaway block (direct_answer is aeo_answer-only); wording unchanged', 'cta block (destination from the workbook CTA structure)'],
  missingFields: ['safety_notice (workbook supplies no reader-facing safety copy)', 'workbook product references left UNLINKED (no public route): Journal, Mood, Brain Health, Habits, Progress, Wellness Tools', 'excerpt/deck (the Content Hub schema has no excerpt field; kept in editorial notes)', 'seo_title (no schema field distinct from title)'],
};

// ─────────────────────────────────────────────────────────────────────────────
// M2-W2-G001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W2_G001: M2W2Asset = {
  editorialRef: "M2-W2-G001",
  contentType: 'geo_article',
  publicLabel: 'Insight',
  title: "Attention Switching, Mental Load and Everyday Wellbeing",
  slug: "attention-switching-mental-load-everyday-wellbeing",
  metaDescription: "Understand attention switching, mental load and how everyday reflection can help you notice what is occupying your attention and what matters next.",
  week: 2,
  pillar: 'Attention, Mental Load and Everyday Wellbeing',
  tags: ['attention-switching', 'mental-load', 'everyday-wellbeing', 'month-2', 'week-2'],

  typeFields: {
    core_concept: "Attention Switching, Mental Load and Everyday Wellbeing",
    citation_summary: "Attention switching refers to moving attention between tasks, thoughts, conversations or other demands. Mental load includes the responsibilities, plans, decisions and unfinished thoughts a person is mentally managing. These experiences can overlap in everyday life and may contribute to a day feeling mentally full. Reflection can help people notice what has been occupying their attention and consider what needs action, what can wait and what matters next.",
    key_statements: [
      "Attention switching is the movement of attention from one task, thought, conversation or demand to another.",
      "Attention switching is a normal part of everyday life because work, relationships, communication and responsibilities regularly require people to redirect their attention.",
      "A day can feel mentally busy even when no single task or event feels particularly difficult.",
      "Repeated switching between messages, tasks, conversations, decisions and responsibilities can contribute to the experience of a mentally full day.",
      "Mental load can include tasks, decisions, plans, reminders, responsibilities and unfinished thoughts that a person is keeping track of mentally.",
      "Mental load is not limited to work; it can involve family responsibilities, personal plans, social commitments, household decisions and other areas of everyday life.",
      "Not every demand that gets a person's attention requires an immediate response.",
      "Reflection can help a person notice what has been occupying their attention and distinguish between what needs action, what can wait and what may simply need acknowledgment.",
      "A busy mind does not automatically mean something is wrong; thoughts can remain active around concerns, decisions, ideas, anticipation, achievements and other meaningful experiences.",
      "Everyday wellbeing can include creating realistic opportunities to notice, reflect on and understand one's own experiences.",
      "Making space for personal reflection does not require caring less about work, relationships or responsibilities.",
      "SOLACE provides adults with ways to talk, reflect, notice patterns and engage with everyday wellbeing through conversation and reflective wellbeing tools."
],
    topics: {
      primary: 'Attention Switching',
      secondary: ['Mental Load', 'Everyday Wellbeing'],
    },
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'GEO Knowledge Asset for the Week 2 authority cluster.',
    goal: 'AI Search Authority',
    geo_focus: 'AI Retrieval',
  },

  body: {
    version: 1,
    blocks: [
      { id: "m2w2g-p1", type: 'paragraph', content: t("Attention is continually directed toward different parts of everyday life.") },
      { id: "m2w2g-p2", type: 'paragraph', content: t("A person may move from a work task to a message, from a conversation to a decision, from a household responsibility to a personal thought, and then back to the original activity.") },
      { id: "m2w2g-p3", type: 'paragraph', content: t("This movement of attention is normal.") },
      { id: "m2w2g-p4", type: 'paragraph', content: t("However, understanding how attention moves throughout a day can provide useful insight into why some days feel mentally fuller than others.") },
      { id: "m2w2g-p5", type: 'paragraph', content: t("Attention switching, mental load and reflection are therefore useful concepts for understanding everyday wellbeing.") },
      { id: "m2w2g-h6", type: 'heading', level: 2, content: t("What is attention?") },
      { id: "m2w2g-h7", type: 'heading', level: 2, content: t("Attention is the focus given to a task, thought, conversation, activity or other demand.") },
      { id: "m2w2g-p8", type: 'paragraph', content: t("Attention may be directed intentionally.") },
      { id: "m2w2g-p9", type: 'paragraph', content: t("For example, a person may decide to focus on:") },
      { id: "m2w2g-p10", type: 'paragraph', content: t("A conversation.") },
      { id: "m2w2g-p11", type: 'paragraph', content: t("A project.") },
      { id: "m2w2g-p12", type: 'paragraph', content: t("A book.") },
      { id: "m2w2g-p13", type: 'paragraph', content: t("A workout.") },
      { id: "m2w2g-p14", type: 'paragraph', content: t("A decision.") },
      { id: "m2w2g-p15", type: 'paragraph', content: t("Attention can also be redirected by something external.") },
      { id: "m2w2g-p16", type: 'paragraph', content: t("For example:") },
      { id: "m2w2g-p17", type: 'paragraph', content: t("A notification.") },
      { id: "m2w2g-p18", type: 'paragraph', content: t("A phone call.") },
      { id: "m2w2g-p19", type: 'paragraph', content: t("A colleague asking a question.") },
      { id: "m2w2g-p20", type: 'paragraph', content: t("A new email.") },
      { id: "m2w2g-p21", type: 'paragraph', content: t("Someone entering a conversation.") },
      { id: "m2w2g-p22", type: 'paragraph', content: t("Or attention may shift internally.") },
      { id: "m2w2g-p23", type: 'paragraph', content: t("A person may suddenly remember:") },
      { id: "m2w2g-p24", type: 'paragraph', content: t("Something that happened earlier.") },
      { id: "m2w2g-p25", type: 'paragraph', content: t("Something they need to do tomorrow.") },
      { id: "m2w2g-p26", type: 'paragraph', content: t("A decision they have not made.") },
      { id: "m2w2g-p27", type: 'paragraph', content: t("An idea.") },
      { id: "m2w2g-p28", type: 'paragraph', content: t("A conversation.") },
      { id: "m2w2g-p29", type: 'paragraph', content: t("Something they are looking forward to.") },
      { id: "m2w2g-p30", type: 'paragraph', content: t("This means attention is influenced by both external demands and internal thoughts.") },
      { id: "m2w2g-h31", type: 'heading', level: 2, content: t("What is attention switching?") },
      { id: "m2w2g-h32", type: 'heading', level: 2, content: t("Attention switching is the movement of attention from one task, thought, conversation or demand to another.") },
      { id: "m2w2g-p33", type: 'paragraph', content: t("Consider an ordinary sequence:") },
      { id: "m2w2g-p34", type: 'paragraph', content: t("A person begins writing an email.") },
      { id: "m2w2g-p35", type: 'paragraph', content: t("A message arrives.") },
      { id: "m2w2g-p36", type: 'paragraph', content: t("They read the message.") },
      { id: "m2w2g-p37", type: 'paragraph', content: t("They return to the email.") },
      { id: "m2w2g-p38", type: 'paragraph', content: t("Someone asks a question.") },
      { id: "m2w2g-p39", type: 'paragraph', content: t("They answer.") },
      { id: "m2w2g-p40", type: 'paragraph', content: t("They return to the email.") },
      { id: "m2w2g-p41", type: 'paragraph', content: t("A calendar reminder appears.") },
      { id: "m2w2g-p42", type: 'paragraph', content: t("Their attention moves again.") },
      { id: "m2w2g-p43", type: 'paragraph', content: t("None of these events needs to be particularly difficult.") },
      { id: "m2w2g-p44", type: 'paragraph', content: t("But the person's attention has repeatedly changed direction.") },
      { id: "m2w2g-p45", type: 'paragraph', content: t("Attention switching is not inherently negative.") },
      { id: "m2w2g-p46", type: 'paragraph', content: t("Everyday life requires it.") },
      { id: "m2w2g-p47", type: 'paragraph', content: t("People collaborate.") },
      { id: "m2w2g-p48", type: 'paragraph', content: t("Respond to important information.") },
      { id: "m2w2g-p49", type: 'paragraph', content: t("Care for other people.") },
      { id: "m2w2g-p50", type: 'paragraph', content: t("Adapt to changing circumstances.") },
      { id: "m2w2g-p51", type: 'paragraph', content: t("Move between different responsibilities.") },
      { id: "m2w2g-p52", type: 'paragraph', content: t("The useful question is therefore not:") },
      { id: "m2w2g-h53", type: 'heading', level: 2, content: t("“How do I eliminate attention switching?”") },
      { id: "m2w2g-p54", type: 'paragraph', content: t("A more practical question is:") },
      { id: "m2w2g-h55", type: 'heading', level: 2, content: t("“How often is my attention moving, and what keeps redirecting it?”") },
      { id: "m2w2g-h56", type: 'heading', level: 2, content: t("Why can an ordinary day feel mentally busy?") },
      { id: "m2w2g-p57", type: 'paragraph', content: t("A mentally busy day does not always contain one major challenge.") },
      { id: "m2w2g-p58", type: 'paragraph', content: t("Sometimes it contains many small demands.") },
      { id: "m2w2g-p59", type: 'paragraph', content: t("A person may:") },
      { id: "m2w2g-p60", type: 'paragraph', content: t("Answer messages.") },
      { id: "m2w2g-p61", type: 'paragraph', content: t("Attend meetings.") },
      { id: "m2w2g-p62", type: 'paragraph', content: t("Make decisions.") },
      { id: "m2w2g-p63", type: 'paragraph', content: t("Remember appointments.") },
      { id: "m2w2g-p64", type: 'paragraph', content: t("Think about family responsibilities.") },
      { id: "m2w2g-p65", type: 'paragraph', content: t("Move between tasks.") },
      { id: "m2w2g-p66", type: 'paragraph', content: t("Plan tomorrow.") },
      { id: "m2w2g-p67", type: 'paragraph', content: t("Replay a conversation.") },
      { id: "m2w2g-p68", type: 'paragraph', content: t("Consider an idea.") },
      { id: "m2w2g-p69", type: 'paragraph', content: t("Remember something unfinished.") },
      { id: "m2w2g-p70", type: 'paragraph', content: t("Individually, these experiences may seem ordinary.") },
      { id: "m2w2g-p71", type: 'paragraph', content: t("Together, they can leave many different things active in a person's attention.") },
      { id: "m2w2g-p72", type: 'paragraph', content: t("This is one reason a day can feel mentally full even when no single event seemed particularly significant.") },
      { id: "m2w2g-h73", type: 'heading', level: 2, content: t("What is mental load?") },
      { id: "m2w2g-h74", type: 'heading', level: 2, content: t("Mental load can include the tasks, decisions, plans, reminders, responsibilities and unfinished thoughts that a person is keeping track of mentally.") },
      { id: "m2w2g-p75", type: 'paragraph', content: t("Mental load can relate to work.") },
      { id: "m2w2g-p76", type: 'paragraph', content: t("For example:") },
      { id: "m2w2g-p77", type: 'paragraph', content: t("Remembering deadlines.") },
      { id: "m2w2g-p78", type: 'paragraph', content: t("Preparing for meetings.") },
      { id: "m2w2g-p79", type: 'paragraph', content: t("Following up with colleagues.") },
      { id: "m2w2g-p80", type: 'paragraph', content: t("Planning upcoming work.") },
      { id: "m2w2g-p81", type: 'paragraph', content: t("Keeping track of decisions.") },
      { id: "m2w2g-p82", type: 'paragraph', content: t("But mental load is not limited to professional responsibilities.") },
      { id: "m2w2g-p83", type: 'paragraph', content: t("It can also include:") },
      { id: "m2w2g-p84", type: 'paragraph', content: t("Family plans.") },
      { id: "m2w2g-p85", type: 'paragraph', content: t("Appointments.") },
      { id: "m2w2g-p86", type: 'paragraph', content: t("Shopping.") },
      { id: "m2w2g-p87", type: 'paragraph', content: t("Household tasks.") },
      { id: "m2w2g-p88", type: 'paragraph', content: t("Social commitments.") },
      { id: "m2w2g-p89", type: 'paragraph', content: t("Travel.") },
      { id: "m2w2g-p90", type: 'paragraph', content: t("Finances.") },
      { id: "m2w2g-p91", type: 'paragraph', content: t("Personal goals.") },
      { id: "m2w2g-p92", type: 'paragraph', content: t("Conversations to revisit.") },
      { id: "m2w2g-p93", type: 'paragraph', content: t("Decisions that remain open.") },
      { id: "m2w2g-p94", type: 'paragraph', content: t("The concept is therefore broader than simply having a long task list.") },
      { id: "m2w2g-p95", type: 'paragraph', content: t("Some things occupying mental attention may never appear on a written list at all.") },
      { id: "m2w2g-h96", type: 'heading', level: 2, content: t("How are attention switching and mental load different?") },
      { id: "m2w2g-p97", type: 'paragraph', content: t("The concepts are related, but they are not identical.") },
      { id: "m2w2g-h98", type: 'heading', level: 2, content: t("Attention switching describes:") },
      { id: "m2w2g-h99", type: 'heading', level: 2, content: t("Where attention moves.") },
      { id: "m2w2g-h100", type: 'heading', level: 2, content: t("Mental load describes:") },
      { id: "m2w2g-h101", type: 'heading', level: 2, content: t("What a person is mentally keeping track of or managing.") },
      { id: "m2w2g-p102", type: 'paragraph', content: t("For example:") },
      { id: "m2w2g-p103", type: 'paragraph', content: t("A person may be working on a presentation while also remembering an appointment, thinking about an upcoming conversation and keeping track of several unanswered messages.") },
      { id: "m2w2g-p104", type: 'paragraph', content: t("The presentation is the current focus.") },
      { id: "m2w2g-p105", type: 'paragraph', content: t("The other responsibilities may remain part of the person's mental load.") },
      { id: "m2w2g-p106", type: 'paragraph', content: t("If a notification then redirects attention toward one of those messages, an attention switch occurs.") },
      { id: "m2w2g-p107", type: 'paragraph', content: t("Understanding this distinction can make both concepts easier to recognize in everyday life.") },
      { id: "m2w2g-h108", type: 'heading', level: 2, content: t("Why can thoughts become more noticeable when the day gets quiet?") },
      { id: "m2w2g-p109", type: 'paragraph', content: t("During a busy period, external demands may occupy much of a person's attention.") },
      { id: "m2w2g-p110", type: 'paragraph', content: t("There may be:") },
      { id: "m2w2g-p111", type: 'paragraph', content: t("Work.") },
      { id: "m2w2g-p112", type: 'paragraph', content: t("Conversations.") },
      { id: "m2w2g-p113", type: 'paragraph', content: t("Travel.") },
      { id: "m2w2g-p114", type: 'paragraph', content: t("Tasks.") },
      { id: "m2w2g-p115", type: 'paragraph', content: t("Messages.") },
      { id: "m2w2g-p116", type: 'paragraph', content: t("Decisions.") },
      { id: "m2w2g-p117", type: 'paragraph', content: t("Other people.") },
      { id: "m2w2g-p118", type: 'paragraph', content: t("When those demands become quieter, previously unfinished thoughts may become easier to notice.") },
      { id: "m2w2g-p119", type: 'paragraph', content: t("This can happen:") },
      { id: "m2w2g-p120", type: 'paragraph', content: t("During a commute.") },
      { id: "m2w2g-p121", type: 'paragraph', content: t("After work.") },
      { id: "m2w2g-p122", type: 'paragraph', content: t("While taking a shower.") },
      { id: "m2w2g-p123", type: 'paragraph', content: t("During a walk.") },
      { id: "m2w2g-p124", type: 'paragraph', content: t("When sitting quietly.") },
      { id: "m2w2g-p125", type: 'paragraph', content: t("Before sleep.") },
      { id: "m2w2g-p126", type: 'paragraph', content: t("The quiet period does not necessarily create the thoughts.") },
      { id: "m2w2g-p127", type: 'paragraph', content: t("It may simply provide more opportunity to notice them.") },
      { id: "m2w2g-p128", type: 'paragraph', content: t("That is why some people may feel that their mind becomes busier precisely when their environment becomes quieter.") },
      { id: "m2w2g-h129", type: 'heading', level: 2, content: t("Does a busy mind always mean something is wrong?") },
      { id: "m2w2g-h130", type: 'heading', level: 2, content: t("No. A busy mind does not automatically mean something is wrong.") },
      { id: "m2w2g-p131", type: 'paragraph', content: t("Thoughts can remain active for many reasons.") },
      { id: "m2w2g-p132", type: 'paragraph', content: t("A person may be:") },
      { id: "m2w2g-p133", type: 'paragraph', content: t("Considering a problem.") },
      { id: "m2w2g-p134", type: 'paragraph', content: t("Planning something.") },
      { id: "m2w2g-p135", type: 'paragraph', content: t("Processing a conversation.") },
      { id: "m2w2g-p136", type: 'paragraph', content: t("Remembering an experience.") },
      { id: "m2w2g-p137", type: 'paragraph', content: t("Thinking about an idea.") },
      { id: "m2w2g-p138", type: 'paragraph', content: t("Anticipating an event.") },
      { id: "m2w2g-p139", type: 'paragraph', content: t("Reflecting on something they accomplished.") },
      { id: "m2w2g-p140", type: 'paragraph', content: t("Feeling excited about an opportunity.") },
      { id: "m2w2g-p141", type: 'paragraph', content: t("Trying to make a decision.") },
      { id: "m2w2g-p142", type: 'paragraph', content: t("Thinking about someone important to them.") },
      { id: "m2w2g-p143", type: 'paragraph', content: t("A busy mind can include difficult thoughts, positive thoughts, practical thoughts or simply unfinished thoughts.") },
      { id: "m2w2g-p144", type: 'paragraph', content: t("The experience should not automatically be interpreted as a diagnosis or medical condition.") },
      { id: "m2w2g-h145", type: 'heading', level: 2, content: t("Does everything that gets attention require immediate action?") },
      { id: "m2w2g-h146", type: 'heading', level: 2, content: t("No. Not every demand that gets attention necessarily requires an immediate response.") },
      { id: "m2w2g-p147", type: 'paragraph', content: t("Some situations genuinely are urgent.") },
      { id: "m2w2g-p148", type: 'paragraph', content: t("Others may need attention later in the day.") },
      { id: "m2w2g-p149", type: 'paragraph', content: t("Some can reasonably wait longer.") },
      { id: "m2w2g-p150", type: 'paragraph', content: t("Some can be handled by another person.") },
      { id: "m2w2g-p151", type: 'paragraph', content: t("Some may not require action at all.") },
      { id: "m2w2g-p152", type: 'paragraph', content: t("A simple attention check can include questions such as:") },
      { id: "m2w2g-h153", type: 'heading', level: 2, content: t("Does this need me now?") },
      { id: "m2w2g-h154", type: 'heading', level: 2, content: t("Does this need me today?") },
      { id: "m2w2g-h155", type: 'heading', level: 2, content: t("Can this wait?") },
      { id: "m2w2g-h156", type: 'heading', level: 2, content: t("Can someone else handle it?") },
      { id: "m2w2g-h157", type: 'heading', level: 2, content: t("Am I checking because I need to—or automatically?") },
      { id: "m2w2g-h158", type: 'heading', level: 2, content: t("What am I already doing?") },
      { id: "m2w2g-h159", type: 'heading', level: 2, content: t("What deserves my attention next?") },
      { id: "m2w2g-p160", type: 'paragraph', content: t("These questions are not universal rules.") },
      { id: "m2w2g-p161", type: 'paragraph', content: t("They are prompts for everyday reflection.") },
      { id: "m2w2g-h162", type: 'heading', level: 2, content: t("What role does reflection play?") },
      { id: "m2w2g-h163", type: 'heading', level: 2, content: t("Reflection involves noticing, considering or making sense of thoughts, experiences, decisions and patterns.") },
      { id: "m2w2g-p164", type: 'paragraph', content: t("Reflection may help a person identify:") },
      { id: "m2w2g-p165", type: 'paragraph', content: t("What has been occupying their attention.") },
      { id: "m2w2g-p166", type: 'paragraph', content: t("What remains unfinished.") },
      { id: "m2w2g-p167", type: 'paragraph', content: t("What requires action.") },
      { id: "m2w2g-p168", type: 'paragraph', content: t("What can wait.") },
      { id: "m2w2g-p169", type: 'paragraph', content: t("What went well.") },
      { id: "m2w2g-p170", type: 'paragraph', content: t("What they learned.") },
      { id: "m2w2g-p171", type: 'paragraph', content: t("What they want to revisit.") },
      { id: "m2w2g-p172", type: 'paragraph', content: t("What matters next.") },
      { id: "m2w2g-p173", type: 'paragraph', content: t("Reflection does not require solving everything.") },
      { id: "m2w2g-p174", type: 'paragraph', content: t("Sometimes the first useful step is simply being able to name what is still occupying attention.") },
      { id: "m2w2g-h175", type: 'heading', level: 2, content: t("Can reflection include positive experiences?") },
      { id: "m2w2g-h176", type: 'heading', level: 2, content: t("Yes. Reflection is not only for problems or difficult experiences.") },
      { id: "m2w2g-p177", type: 'paragraph', content: t("People can reflect on:") },
      { id: "m2w2g-p178", type: 'paragraph', content: t("An achievement.") },
      { id: "m2w2g-p179", type: 'paragraph', content: t("Good news.") },
      { id: "m2w2g-p180", type: 'paragraph', content: t("Progress.") },
      { id: "m2w2g-p181", type: 'paragraph', content: t("A meaningful conversation.") },
      { id: "m2w2g-p182", type: 'paragraph', content: t("An idea.") },
      { id: "m2w2g-p183", type: 'paragraph', content: t("Something they enjoyed.") },
      { id: "m2w2g-p184", type: 'paragraph', content: t("A decision they feel good about.") },
      { id: "m2w2g-p185", type: 'paragraph', content: t("A moment of gratitude.") },
      { id: "m2w2g-p186", type: 'paragraph', content: t("Something they learned.") },
      { id: "m2w2g-p187", type: 'paragraph', content: t("Something they are excited to pursue.") },
      { id: "m2w2g-p188", type: 'paragraph', content: t("This matters because everyday wellbeing is broader than responding to difficulty.") },
      { id: "m2w2g-p189", type: 'paragraph', content: t("It can also include noticing progress, understanding experiences and giving meaningful moments enough attention to register.") },
      { id: "m2w2g-h190", type: 'heading', level: 2, content: t("How can someone create more space for reflection?") },
      { id: "m2w2g-p191", type: 'paragraph', content: t("Creating space does not necessarily require a large amount of additional free time.") },
      { id: "m2w2g-p192", type: 'paragraph', content: t("Depending on the person and situation, reflection might happen through:") },
      { id: "m2w2g-p193", type: 'paragraph', content: t("Writing.") },
      { id: "m2w2g-p194", type: 'paragraph', content: t("Talking something through.") },
      { id: "m2w2g-p195", type: 'paragraph', content: t("Taking a short walk.") },
      { id: "m2w2g-p196", type: 'paragraph', content: t("Creating a transition between work and home.") },
      { id: "m2w2g-p197", type: 'paragraph', content: t("Sitting quietly for a few minutes.") },
      { id: "m2w2g-p198", type: 'paragraph', content: t("Reviewing the day.") },
      { id: "m2w2g-p199", type: 'paragraph', content: t("Checking in with a mood or routine.") },
      { id: "m2w2g-p200", type: 'paragraph', content: t("Finishing one activity before moving to another.") },
      { id: "m2w2g-p201", type: 'paragraph', content: t("Protecting part of an existing activity from unnecessary interruptions.") },
      { id: "m2w2g-p202", type: 'paragraph', content: t("The goal is not to create a perfect routine.") },
      { id: "m2w2g-p203", type: 'paragraph', content: t("It is to find realistic opportunities to notice one's own experience.") },
      { id: "m2w2g-p204", type: 'paragraph', content: t("How does SOLACE relate to everyday reflection?") },
      { id: "m2w2g-h205", type: 'heading', level: 2, content: t("SOLACE is a space for adults to talk through what they're carrying, reflect on everyday experiences and build greater awareness of their own patterns over time.") },
      { id: "m2w2g-p206", type: 'paragraph', content: t("That can include difficult experiences.") },
      { id: "m2w2g-p207", type: 'paragraph', content: t("But it can also include:") },
      { id: "m2w2g-p208", type: 'paragraph', content: t("Ideas.") },
      { id: "m2w2g-p209", type: 'paragraph', content: t("Decisions.") },
      { id: "m2w2g-p210", type: 'paragraph', content: t("Achievements.") },
      { id: "m2w2g-p211", type: 'paragraph', content: t("Questions.") },
      { id: "m2w2g-p212", type: 'paragraph', content: t("Relationships.") },
      { id: "m2w2g-p213", type: 'paragraph', content: t("Plans.") },
      { id: "m2w2g-p214", type: 'paragraph', content: t("Progress.") },
      { id: "m2w2g-p215", type: 'paragraph', content: t("Excitement.") },
      { id: "m2w2g-p216", type: 'paragraph', content: t("Uncertainty.") },
      { id: "m2w2g-p217", type: 'paragraph', content: t("Everyday thoughts.") },
      { id: "m2w2g-p218", type: 'paragraph', content: t("SOLACE's wider wellbeing ecosystem includes opportunities for conversation, journaling, mood awareness, habits, sleep awareness, brain health, progress, challenges, community and wellbeing resources.") },
      { id: "m2w2g-p219", type: 'paragraph', content: t("The underlying principle is simple:") },
      { id: "m2w2g-h220", type: 'heading', level: 2, content: t("Reflection can have a place in everyday life, not only when something is wrong.") },
      { id: "m2w2g-p221", type: 'paragraph', content: t("This block should appear visually distinct near the bottom.") },
      { id: "m2w2g-p222", type: 'paragraph', content: t("In Brief") },
      { id: "m2w2g-p223", type: 'paragraph', content: t("Attention is where focus is directed.") },
      { id: "m2w2g-p224", type: 'paragraph', content: t("Attention switching is moving focus between different tasks, thoughts or demands.") },
      { id: "m2w2g-p225", type: 'paragraph', content: t("Mental load includes the responsibilities, plans, decisions and unfinished thoughts a person is mentally keeping track of.") },
      { id: "m2w2g-p226", type: 'paragraph', content: t("Reflection creates an opportunity to notice and understand what has been occupying attention.") },
      { id: "m2w2g-p227", type: 'paragraph', content: t("Everyday wellbeing can include realistic routines and moments that create space for awareness, reflection and intentional choices.") },
      { id: "m2w2g-p228", type: 'paragraph', content: t("SOLACE provides adults with ways to talk, reflect and engage with everyday wellbeing.") },
      { id: "m2w2g-p229", type: 'paragraph', content: t("Use clear H2/H3 questions because generative systems frequently retrieve answer-shaped passages.") },
      { id: "m2w2g-h230", type: 'heading', level: 2, content: t("What is attention switching?") },
      { id: "m2w2g-p231", type: 'paragraph', content: t("Attention switching is moving attention from one task, thought, conversation or demand to another.") },
      { id: "m2w2g-h232", type: 'heading', level: 2, content: t("What is mental load?") },
      { id: "m2w2g-p233", type: 'paragraph', content: t("Mental load includes tasks, plans, decisions, responsibilities, reminders and unfinished thoughts that a person is mentally keeping track of or managing.") },
      { id: "m2w2g-h234", type: 'heading', level: 2, content: t("Are attention switching and mental load the same?") },
      { id: "m2w2g-p235", type: 'paragraph', content: t("No. Attention switching describes the movement of attention, while mental load describes the things a person is mentally keeping track of or managing.") },
      { id: "m2w2g-h236", type: 'heading', level: 2, content: t("Why can a day feel mentally busy?") },
      { id: "m2w2g-p237", type: 'paragraph', content: t("A day can feel mentally busy when many tasks, conversations, decisions, responsibilities or thoughts repeatedly require attention, even if no single demand feels especially significant.") },
      { id: "m2w2g-h238", type: 'heading', level: 2, content: t("Why do thoughts become noticeable at night?") },
      { id: "m2w2g-p239", type: 'paragraph', content: t("Thoughts may become easier to notice when external demands decrease and there is more quiet space for reflection.") },
      { id: "m2w2g-h240", type: 'heading', level: 2, content: t("Does a busy mind mean something is wrong?") },
      { id: "m2w2g-p241", type: 'paragraph', content: t("Not necessarily. A busy mind can contain concerns, plans, ideas, anticipation, achievements, decisions and other everyday thoughts.") },
      { id: "m2w2g-h242", type: 'heading', level: 2, content: t("What is everyday reflection?") },
      { id: "m2w2g-p243", type: 'paragraph', content: t("Everyday reflection is taking time to notice, consider and make sense of ordinary thoughts, experiences, decisions and patterns.") },
      { id: 'm2w2g-cta', type: 'cta', label: 'Talk It Out', target: { kind: 'route', value: 'product.talk_it_out' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W2-B001', anchorText: null, relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W2-A001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'product.talk_it_out', anchorText: 'Talk It Out', relation: 'product' },
  ],

  authoredOutsideWorkbook: ['cta block (destination from the workbook internal linking section)'],
  missingFields: ['safety_notice (workbook supplies no reader-facing safety copy)', 'workbook product references left UNLINKED (no public route): Journal, Mood, Brain Health, Habits, Progress, Wellness Tools', 'excerpt/deck (the Content Hub schema has no excerpt field; kept in editorial notes)'],
};

// ─────────────────────────────────────────────────────────────────────────────
// M2-W2-A001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W2_A001: M2W2Asset = {
  editorialRef: "M2-W2-A001",
  contentType: 'aeo_answer',
  publicLabel: 'Answer',
  title: "Why Does My Mind Feel So Busy? Common Questions About Attention and Mental Load",
  slug: "busy-mind-attention-mental-load-questions",
  metaDescription: "Why does your mind feel so busy? Get clear answers about attention switching, mental load, nighttime thoughts and creating more mental space.",
  week: 2,
  pillar: 'Attention, Mental Load and Everyday Wellbeing',
  tags: ['attention-switching', 'mental-load', 'everyday-wellbeing', 'month-2', 'week-2'],

  typeFields: {
    primary_question: "Why does my mind feel so busy?",
    supporting_queries: [
      "Why does my mind feel busy even when I'm not doing much?",
      "Why can't I stop thinking about work after work?",
      "Why is switching between tasks tiring?",
      "Why do I think about everything at night?",
      "Does everything that gets my attention need an immediate response?",
      "Why does everything feel urgent?"
],
    snippet_answer: "Your mind can feel busy when many tasks, conversations, decisions, responsibilities or unfinished thoughts are competing for attention. Repeatedly switching between them can make a day feel mentally full, even when no single thing feels especially difficult. Quiet moments may also make thoughts that were already present easier to notice.",
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'AEO Answer Asset for the Week 2 authority cluster.',
    goal: 'Answer Engine Authority',
    aeo_signal: 'direct answer first',
    seo_title_note: "Why Does My Mind Feel So Busy? Attention & Mental Load FAQs",
    excerpt_note: "Clear answers to common questions about a busy mind, attention switching, mental load and creating more room for everyday reflection.",
  },

  body: {
    version: 1,
    blocks: [
      { id: 'm2w2a-direct-answer', type: 'direct_answer', content: t("Your mind can feel busy when many tasks, conversations, decisions, responsibilities or unfinished thoughts are competing for attention. Repeatedly switching between them can make a day feel mentally full, even when no single thing feels especially difficult. Quiet moments may also make thoughts that were already present easier to notice.") },
      { id: "m2w2a-p1", type: 'paragraph', content: t("A busy mind does not automatically mean something is wrong. Thoughts can involve concerns, plans, ideas, achievements, anticipation, relationships and ordinary everyday experiences.") },
      { id: "m2w2a-h2", type: 'heading', level: 2, content: t("Why does my mind feel busy even when I'm not doing much?") },
      { id: "m2w2a-h3", type: 'heading', level: 3, content: t("Your mind can feel busy even during a physically quiet moment because attention may still be occupied by decisions, plans, conversations, reminders, unfinished tasks or things you're anticipating. Being physically inactive does not necessarily mean your attention is inactive.") },
      { id: "m2w2a-p4", type: 'paragraph', content: t("You may be sitting quietly while mentally:") },
      { id: "m2w2a-p5", type: 'paragraph', content: t("Planning tomorrow.") },
      { id: "m2w2a-p6", type: 'paragraph', content: t("Remembering something.") },
      { id: "m2w2a-p7", type: 'paragraph', content: t("Replaying a conversation.") },
      { id: "m2w2a-p8", type: 'paragraph', content: t("Considering a decision.") },
      { id: "m2w2a-p9", type: 'paragraph', content: t("Thinking about work.") },
      { id: "m2w2a-p10", type: 'paragraph', content: t("Looking forward to something.") },
      { id: "m2w2a-p11", type: 'paragraph', content: t("The activity may be internal rather than visible.") },
      { id: "m2w2a-h12", type: 'heading', level: 2, content: t("Why can't I stop thinking about work after work?") },
      { id: "m2w2a-h13", type: 'heading', level: 3, content: t("Work-related thoughts can continue after the workday when tasks, decisions, conversations or upcoming responsibilities still have your attention. You may also notice those thoughts more clearly once meetings, messages and other daytime demands become quieter.") },
      { id: "m2w2a-h14", type: 'heading', level: 3, content: t("Reflection prompt") },
      { id: "m2w2a-p15", type: 'paragraph', content: t("Ask:") },
      { id: "m2w2a-h16", type: 'heading', level: 3, content: t("“Is there something I actually need to do about this tonight, or is this something I can return to tomorrow?”") },
      { id: "m2w2a-p17", type: 'paragraph', content: t("Sometimes action is needed.") },
      { id: "m2w2a-p18", type: 'paragraph', content: t("Sometimes acknowledgment is enough for now.") },
      { id: "m2w2a-h19", type: 'heading', level: 2, content: t("Why is switching between tasks tiring?") },
      { id: "m2w2a-h20", type: 'heading', level: 3, content: t("Switching between tasks repeatedly requires your attention to keep changing direction. An ordinary day can therefore feel mentally full when you repeatedly move among emails, conversations, meetings, decisions and tasks, even when none of those activities feels particularly difficult by itself.") },
      { id: "m2w2a-h21", type: 'heading', level: 3, content: t("Important distinction") },
      { id: "m2w2a-p22", type: 'paragraph', content: t("This resource does not claim:") },
      { id: "m2w2a-p23", type: 'paragraph', content: t("“Task switching damages your brain.”") },
      { id: "m2w2a-p24", type: 'paragraph', content: t("The everyday wellbeing point is simpler:") },
      { id: "m2w2a-h25", type: 'heading', level: 3, content: t("Notice how often your attention has had to move.") },
      { id: "m2w2a-h26", type: 'heading', level: 2, content: t("Why do I think about everything at night?") },
      { id: "m2w2a-h27", type: 'heading', level: 3, content: t("Night may be one of the first quieter periods in your day. With fewer tasks, conversations and external demands competing for attention, thoughts about the day, tomorrow, decisions or unfinished experiences may become easier to notice.") },
      { id: "m2w2a-h28", type: 'heading', level: 3, content: t("Supporting context") },
      { id: "m2w2a-p29", type: 'paragraph', content: t("The quiet may not have created the thoughts.") },
      { id: "m2w2a-p30", type: 'paragraph', content: t("It may simply have made them more noticeable.") },
      { id: "m2w2a-p31", type: 'paragraph', content: t("That is why:") },
      { id: "m2w2a-h32", type: 'heading', level: 3, content: t("“Why is my mind suddenly busy?”") },
      { id: "m2w2a-p33", type: 'paragraph', content: t("can sometimes become:") },
      { id: "m2w2a-h34", type: 'heading', level: 3, content: t("“What finally has room to get my attention?”") },
      { id: "m2w2a-h35", type: 'heading', level: 2, content: t("Does everything that gets my attention need an immediate response?") },
      { id: "m2w2a-h36", type: 'heading', level: 3, content: t("No. Some situations genuinely require immediate attention, while others can be handled later today, at another appropriate time or by someone else. Something appearing now does not automatically make it urgent.") },
      { id: "m2w2a-h37", type: 'heading', level: 3, content: t("Simple attention check") },
      { id: "m2w2a-p38", type: 'paragraph', content: t("Ask:") },
      { id: "m2w2a-h39", type: 'heading', level: 3, content: t("Does this need me now?") },
      { id: "m2w2a-h40", type: 'heading', level: 3, content: t("Does this need me today?") },
      { id: "m2w2a-h41", type: 'heading', level: 3, content: t("Can this wait?") },
      { id: "m2w2a-h42", type: 'heading', level: 3, content: t("Can someone else handle it?") },
      { id: "m2w2a-p43", type: 'paragraph', content: t("This is reflection, not a universal prioritization rule.") },
      { id: "m2w2a-h44", type: 'heading', level: 2, content: t("Why does everything feel urgent?") },
      { id: "m2w2a-h45", type: 'heading', level: 3, content: t("Different demands can begin to feel equally urgent when messages, requests, reminders, tasks and responsibilities arrive close together. Pausing before responding can help distinguish what genuinely needs immediate attention from what simply appeared most recently.") },
      { id: "m2w2a-h46", type: 'heading', level: 3, content: t("Useful distinction") },
      { id: "m2w2a-p47", type: 'paragraph', content: t("RECENT ≠ URGENT") },
      { id: "m2w2a-p48", type: 'paragraph', content: t("Not always.") },
      { id: "m2w2a-p49", type: 'paragraph', content: t("Some recent things really are urgent.") },
      { id: "m2w2a-p50", type: 'paragraph', content: t("Many aren't.") },
      { id: "m2w2a-h51", type: 'heading', level: 2, content: t("What is attention switching?") },
      { id: "m2w2a-h52", type: 'heading', level: 3, content: t("Attention switching is moving your focus from one task, thought, conversation or demand to another. It is a normal part of everyday life because work, relationships, communication and responsibilities regularly require attention to move.") },
      { id: "m2w2a-h53", type: 'heading', level: 3, content: t("Example") },
      { id: "m2w2a-p54", type: 'paragraph', content: t("Writing report.") },
      { id: "m2w2a-p55", type: 'paragraph', content: t("↓") },
      { id: "m2w2a-p56", type: 'paragraph', content: t("Message arrives.") },
      { id: "m2w2a-p57", type: 'paragraph', content: t("↓") },
      { id: "m2w2a-p58", type: 'paragraph', content: t("Read message.") },
      { id: "m2w2a-p59", type: 'paragraph', content: t("↓") },
      { id: "m2w2a-p60", type: 'paragraph', content: t("Return to report.") },
      { id: "m2w2a-p61", type: 'paragraph', content: t("↓") },
      { id: "m2w2a-p62", type: 'paragraph', content: t("Colleague asks question.") },
      { id: "m2w2a-p63", type: 'paragraph', content: t("↓") },
      { id: "m2w2a-p64", type: 'paragraph', content: t("Answer.") },
      { id: "m2w2a-p65", type: 'paragraph', content: t("↓") },
      { id: "m2w2a-p66", type: 'paragraph', content: t("Return again.") },
      { id: "m2w2a-p67", type: 'paragraph', content: t("That sequence contains multiple attention switches.") },
      { id: "m2w2a-h68", type: 'heading', level: 2, content: t("What is mental load?") },
      { id: "m2w2a-h69", type: 'heading', level: 3, content: t("Mental load includes the tasks, decisions, plans, reminders, responsibilities and unfinished thoughts that a person is mentally keeping track of or managing. It can involve work, family life, household responsibilities, relationships, personal plans and other everyday commitments.") },
      { id: "m2w2a-p70", type: 'paragraph', content: t("Mental load isn't necessarily visible.") },
      { id: "m2w2a-p71", type: 'paragraph', content: t("Someone may look like they're doing one thing while mentally keeping track of several others.") },
      { id: "m2w2a-h72", type: 'heading', level: 2, content: t("Are mental load and attention switching the same thing?") },
      { id: "m2w2a-h73", type: 'heading', level: 3, content: t("No. Attention switching describes where your attention moves, while mental load describes the things you're mentally keeping track of or managing. They can overlap, but they describe different parts of the experience.") },
      { id: "m2w2a-h74", type: 'heading', level: 3, content: t("Simple example") },
      { id: "m2w2a-p75", type: 'paragraph', content: t("You're writing a presentation.") },
      { id: "m2w2a-p76", type: 'paragraph', content: t("That's your current attention.") },
      { id: "m2w2a-p77", type: 'paragraph', content: t("You're also remembering:") },
      { id: "m2w2a-p78", type: 'paragraph', content: t("An appointment.") },
      { id: "m2w2a-p79", type: 'paragraph', content: t("An email.") },
      { id: "m2w2a-p80", type: 'paragraph', content: t("Dinner plans.") },
      { id: "m2w2a-p81", type: 'paragraph', content: t("Tomorrow's deadline.") },
      { id: "m2w2a-p82", type: 'paragraph', content: t("Those may be part of your mental load.") },
      { id: "m2w2a-p83", type: 'paragraph', content: t("Your phone then displays the email.") },
      { id: "m2w2a-p84", type: 'paragraph', content: t("You check it.") },
      { id: "m2w2a-p85", type: 'paragraph', content: t("That's an attention switch.") },
      { id: "m2w2a-p86", type: 'paragraph', content: t("This distinction is one of the most important knowledge signals in Week 2.") },
      { id: "m2w2a-h87", type: 'heading', level: 2, content: t("How can I create more mental space during a busy day?") },
      { id: "m2w2a-h88", type: 'heading', level: 3, content: t("Mental space does not always require finding a large amount of extra free time. Depending on the situation, it may involve finishing one activity before switching, recording an unfinished thought, taking a short transition between activities, reflecting for a few minutes or protecting part of an existing routine from unnecessary interruptions.") },
      { id: "m2w2a-h89", type: 'heading', level: 3, content: t("Key principle") },
      { id: "m2w2a-p90", type: 'paragraph', content: t("You may not need another hour.") },
      { id: "m2w2a-p91", type: 'paragraph', content: t("Sometimes you need to decide what gets your attention during the time you already have.") },
      { id: "m2w2a-h92", type: 'heading', level: 2, content: t("How can I stop treating everything as urgent?") },
      { id: "m2w2a-h93", type: 'heading', level: 3, content: t("Start by separating arrival from urgency. When something asks for your attention, consider whether it needs action now, later today, another time or from someone else. Not every request can wait, but not every request needs to become “right now” either.") },
      { id: "m2w2a-h94", type: 'heading', level: 3, content: t("Reflection questions") },
      { id: "m2w2a-p95", type: 'paragraph', content: t("What am I already doing?") },
      { id: "m2w2a-p96", type: 'paragraph', content: t("Does this actually require me?") },
      { id: "m2w2a-p97", type: 'paragraph', content: t("What happens if I return to it later?") },
      { id: "m2w2a-p98", type: 'paragraph', content: t("What deserves my attention next?") },
      { id: "m2w2a-h99", type: 'heading', level: 2, content: t("Why do I keep replaying conversations?") },
      { id: "m2w2a-h100", type: 'heading', level: 3, content: t("A conversation may stay in your attention because you're still considering what happened, what it meant, how you felt about it or whether anything needs to happen next. People can also replay positive, meaningful or surprising conversations—not only difficult ones.") },
      { id: "m2w2a-h101", type: 'heading', level: 3, content: t("Reflection shift") },
      { id: "m2w2a-p102", type: 'paragraph', content: t("Instead of only replaying:") },
      { id: "m2w2a-h103", type: 'heading', level: 3, content: t("“What am I trying to understand about this?”") },
      { id: "m2w2a-p104", type: 'paragraph', content: t("That moves the experience toward reflection.") },
      { id: "m2w2a-h105", type: 'heading', level: 2, content: t("Can positive experiences make my mind feel busy too?") },
      { id: "m2w2a-h106", type: 'heading', level: 3, content: t("Yes. An active mind is not limited to worry or difficult experiences. Excitement, good news, achievements, new ideas, anticipation, meaningful conversations and future plans can also continue occupying attention after an event has ended.") },
      { id: "m2w2a-p107", type: 'paragraph', content: t("This answer is strategically important for SOLACE.") },
      { id: "m2w2a-p108", type: 'paragraph', content: t("It reinforces that reflection is relevant to:") },
      { id: "m2w2a-p109", type: 'paragraph', content: t("life, not only difficulty.") },
      { id: "m2w2a-h110", type: 'heading', level: 2, content: t("What is everyday reflection?") },
      { id: "m2w2a-h111", type: 'heading', level: 3, content: t("Everyday reflection means taking time to notice and consider ordinary thoughts, experiences, decisions and patterns. It can involve understanding what happened, what mattered, what remains unfinished, what went well or what deserves attention next.") },
      { id: "m2w2a-p112", type: 'paragraph', content: t("Reflection can happen through:") },
      { id: "m2w2a-p113", type: 'paragraph', content: t("Writing.") },
      { id: "m2w2a-p114", type: 'paragraph', content: t("Conversation.") },
      { id: "m2w2a-p115", type: 'paragraph', content: t("Walking.") },
      { id: "m2w2a-p116", type: 'paragraph', content: t("Quiet thinking.") },
      { id: "m2w2a-p117", type: 'paragraph', content: t("Mood check-ins.") },
      { id: "m2w2a-p118", type: 'paragraph', content: t("Reviewing progress.") },
      { id: "m2w2a-p119", type: 'paragraph', content: t("It doesn't require a major problem.") },
      { id: "m2w2a-h120", type: 'heading', level: 2, content: t("Can talking something through help me understand what I'm thinking?") },
      { id: "m2w2a-h121", type: 'heading', level: 3, content: t("Talking something through can create an opportunity to put thoughts into words, notice what keeps coming up and clarify what may need further reflection or action. You do not always need to have your thoughts perfectly organized before beginning a conversation.") },
      { id: "m2w2a-p122", type: 'paragraph', content: t("A useful starting point can simply be:") },
      { id: "m2w2a-h123", type: 'heading', level: 3, content: t("“I don't really know where to start.”") },
      { id: "m2w2a-p124", type: 'paragraph', content: t("That's still a start.") },
      { id: "m2w2a-h125", type: 'heading', level: 2, content: t("Do I need to completely clear my mind to feel less mentally busy?") },
      { id: "m2w2a-h126", type: 'heading', level: 3, content: t("Not necessarily. The goal does not always need to be an empty mind. Sometimes it is more useful to understand what currently has your attention, decide whether anything needs action and give unfinished thoughts somewhere to go through reflection, writing or conversation.") },
      { id: "m2w2a-p127", type: 'paragraph', content: t("This is a particularly strong SOLACE-aligned answer.") },
      { id: "m2w2a-p128", type: 'paragraph', content: t("We are not selling:") },
      { id: "m2w2a-h129", type: 'heading', level: 3, content: t("“Stop thinking.”") },
      { id: "m2w2a-p130", type: 'paragraph', content: t("We're supporting:") },
      { id: "m2w2a-h131", type: 'heading', level: 3, content: t("“Understand what's asking for your attention.”") },
      { id: "m2w2a-h132", type: 'heading', level: 2, content: t("Is making time for myself selfish when other people need me?") },
      { id: "m2w2a-h133", type: 'heading', level: 3, content: t("Making some time or attention available for yourself does not automatically mean caring less about other people or responsibilities. It can simply mean recognizing that your own thoughts, routines, experiences and needs are also part of the life you're managing.") },
      { id: "m2w2a-p134", type: 'paragraph', content: t("This connects directly to Rosalind's Week 2 founder message without duplicating the Reel.") },
      { id: "m2w2a-h135", type: 'heading', level: 2, content: t("What can I ask myself at the end of a busy day?") },
      { id: "m2w2a-p136", type: 'paragraph', content: t("Try a few simple questions:") },
      { id: "m2w2a-h137", type: 'heading', level: 3, content: t("What had most of my attention today?") },
      { id: "m2w2a-h138", type: 'heading', level: 3, content: t("What am I still thinking about?") },
      { id: "m2w2a-h139", type: 'heading', level: 3, content: t("Is anything genuinely unfinished?") },
      { id: "m2w2a-h140", type: 'heading', level: 3, content: t("What can wait until tomorrow?") },
      { id: "m2w2a-h141", type: 'heading', level: 3, content: t("What did I handle well?") },
      { id: "m2w2a-h142", type: 'heading', level: 3, content: t("What deserves more of my attention next?") },
      { id: "m2w2a-p143", type: 'paragraph', content: t("You do not need to answer all of them.") },
      { id: "m2w2a-p144", type: 'paragraph', content: t("One useful question may be enough.") },
      { id: "m2w2a-p145", type: 'paragraph', content: t("How can SOLACE support everyday reflection?") },
      { id: "m2w2a-h146", type: 'heading', level: 2, content: t("SOLACE gives adults a place to talk through what they're carrying, reflect on everyday experiences and notice patterns over time. Reflection can involve difficult moments, but it can also include decisions, ideas, achievements, relationships, plans, progress and ordinary thoughts that deserve space.") },
      { id: "m2w2a-p147", type: 'paragraph', content: t("The wider SOLACE experience includes:") },
      { id: "m2w2a-p148", type: 'paragraph', content: t("Talk It Out.") },
      { id: "m2w2a-p149", type: 'paragraph', content: t("Journal.") },
      { id: "m2w2a-p150", type: 'paragraph', content: t("Mood.") },
      { id: "m2w2a-p151", type: 'paragraph', content: t("Habits.") },
      { id: "m2w2a-p152", type: 'paragraph', content: t("Sleep.") },
      { id: "m2w2a-p153", type: 'paragraph', content: t("Brain Health.") },
      { id: "m2w2a-p154", type: 'paragraph', content: t("Progress.") },
      { id: "m2w2a-p155", type: 'paragraph', content: t("Challenges.") },
      { id: "m2w2a-p156", type: 'paragraph', content: t("Community.") },
      { id: "m2w2a-p157", type: 'paragraph', content: t("Wellness Resources.") },
      { id: "m2w2a-p158", type: 'paragraph', content: t("The positioning remains:") },
      { id: "m2w2a-p159", type: 'paragraph', content: t("Reflection doesn't have to wait until something is wrong.") },
      { id: "m2w2a-h160", type: 'heading', level: 2, content: t("Heading") },
      { id: "m2w2a-p161", type: 'paragraph', content: t("What still has your attention?") },
      { id: "m2w2a-p162", type: 'paragraph', content: t("Copy:") },
      { id: "m2w2a-p163", type: 'paragraph', content: t("Maybe it's something unfinished.") },
      { id: "m2w2a-p164", type: 'paragraph', content: t("Something coming tomorrow.") },
      { id: "m2w2a-p165", type: 'paragraph', content: t("Something someone said.") },
      { id: "m2w2a-p166", type: 'paragraph', content: t("Something you handled well.") },
      { id: "m2w2a-p167", type: 'paragraph', content: t("Something you're excited about.") },
      { id: "m2w2a-p168", type: 'paragraph', content: t("Or something you haven't quite found the words for yet.") },
      { id: "m2w2a-p169", type: 'paragraph', content: t("You don't need to organize every thought before giving it some space.") },
      { id: "m2w2a-p170", type: 'paragraph', content: t("Sometimes noticing what keeps returning is enough to begin.") },
      { id: "m2w2a-h171", type: 'heading', level: 2, content: t("Soft CTA") },
      { id: "m2w2a-h172", type: 'heading', level: 2, content: t("Explore SOLACE and find a way to talk, reflect and make room for what's on your mind.") },
      { id: 'm2w2a-quick', type: 'table', caption: 'Quick answers', headers: ['Question', 'Short Answer'], rows: [[t("Why does my mind feel busy?"), t("Many tasks, thoughts or responsibilities may still be occupying attention.")], [t("Why at night?"), t("Quiet can make existing thoughts easier to notice.")], [t("What is attention switching?"), t("Moving attention from one demand to another.")], [t("What is mental load?"), t("Things you're mentally keeping track of or managing.")], [t("Are they the same?"), t("No. One describes movement of attention; the other describes what you're mentally carrying.")], [t("Does everything need me now?"), t("No. Some things are immediate; others can appropriately wait.")], [t("Can positive things occupy attention?"), t("Yes. Ideas, achievements, excitement and anticipation can remain active too.")], [t("Do I need to stop thinking?"), t("Not necessarily. Understanding what has your attention may be more useful.")], [t("Can I reflect without a problem?"), t("Yes. Reflection can include ordinary and positive experiences.")]] },
      { id: 'm2w2a-faq', type: 'faq', heading: 'Frequently Asked Questions', items: [{ id: "m2w2a-faq-1", question: "Why does my mind feel so busy?", answer: t("Your mind can feel busy when many tasks, conversations, decisions, responsibilities or unfinished thoughts are competing for attention. Repeatedly switching between them can make a day feel mentally full, even when no single thing feels especially difficult. Quiet moments may also make thoughts that were already present easier to notice.") }, { id: "m2w2a-faq-2", question: "Why does my mind feel busy even when I'm not doing much?", answer: t("Your mind can feel busy even during a physically quiet moment because attention may still be occupied by decisions, plans, conversations, reminders, unfinished tasks or things you're anticipating. Being physically inactive does not necessarily mean your attention is inactive.") }, { id: "m2w2a-faq-3", question: "Why can't I stop thinking about work after work?", answer: t("Work-related thoughts can continue after the workday when tasks, decisions, conversations or upcoming responsibilities still have your attention. You may also notice those thoughts more clearly once meetings, messages and other daytime demands become quieter.") }, { id: "m2w2a-faq-4", question: "Why do I think about everything at night?", answer: t("Night may be one of the first quieter periods in your day. With fewer tasks, conversations and external demands competing for attention, thoughts about the day, tomorrow, decisions or unfinished experiences may become easier to notice.") }, { id: "m2w2a-faq-5", question: "What is attention switching?", answer: t("Attention switching is moving your focus from one task, thought, conversation or demand to another. It is a normal part of everyday life because work, relationships, communication and responsibilities regularly require attention to move.") }, { id: "m2w2a-faq-6", question: "What is mental load?", answer: t("Mental load includes the tasks, decisions, plans, reminders, responsibilities and unfinished thoughts that a person is mentally keeping track of or managing. It can involve work, family life, household responsibilities, relationships, personal plans and other everyday commitments.") }, { id: "m2w2a-faq-7", question: "Are mental load and attention switching the same thing?", answer: t("No. Attention switching describes where your attention moves, while mental load describes the things you're mentally keeping track of or managing. They can overlap, but they describe different parts of the experience.") }, { id: "m2w2a-faq-8", question: "How can I create more mental space during a busy day?", answer: t("Mental space does not always require finding a large amount of extra free time. Depending on the situation, it may involve finishing one activity before switching, recording an unfinished thought, taking a short transition between activities, reflecting for a few minutes or protecting part of an existing routine from unnecessary interruptions.") }, { id: "m2w2a-faq-9", question: "Does everything that gets my attention need an immediate response?", answer: t("No. Some situations genuinely require immediate attention, while others can be handled later today, at another appropriate time or by someone else. Something appearing now does not automatically make it urgent.") }, { id: "m2w2a-faq-10", question: "Can positive experiences make my mind feel busy too?", answer: t("Yes. An active mind is not limited to worry or difficult experiences. Excitement, good news, achievements, new ideas, anticipation, meaningful conversations and future plans can also continue occupying attention after an event has ended.") }] },
      { id: 'm2w2a-cta', type: 'cta', label: 'Talk It Out', target: { kind: 'route', value: 'product.talk_it_out' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W2-B001', anchorText: null, relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W2-G001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'product.talk_it_out', anchorText: 'Talk It Out', relation: 'product' },
  ],

  authoredOutsideWorkbook: ['cta block (destination from the workbook internal linking plan)'],
  missingFields: ['safety_notice (workbook supplies no reader-facing safety copy)', 'workbook product references left UNLINKED (no public route): Journal, Mood, Brain Health, Habits, Progress, Wellness Tools', 'excerpt/deck (the Content Hub schema has no excerpt field; kept in editorial notes)', 'seo_title (no schema field distinct from title)'],
};

/** The three Month 2 Week 2 assets, in workbook order. */
export const M2W2_ASSETS: M2W2Asset[] = [M2_W2_B001, M2_W2_G001, M2_W2_A001];

/**
 * Content-to-content edges the workbook states explicitly.
 *
 * B001 §23 connects the blog to the GEO asset and §24 to the AEO answer targets; G001 §16/§17 and
 * A001 §31/§32 require cross-support among the three, including G001 <-> A001. M2-W2-L001 is a
 * LinkedIn asset with no Content Hub URL, so no edge is created for it.
 */
export const EXPECTED_CONTENT_EDGES: Array<[string, string]> = [
  ['M2-W2-B001', 'M2-W2-G001'],
  ['M2-W2-B001', 'M2-W2-A001'],
  ['M2-W2-G001', 'M2-W2-B001'],
  ['M2-W2-G001', 'M2-W2-A001'],
  ['M2-W2-A001', 'M2-W2-B001'],
  ['M2-W2-A001', 'M2-W2-G001'],
];
