/**
 * Month 2 Week 3 workbook -> Content Hub mapping.
 *
 * SOURCE: `Month 2 Week 3 Operational Workbook.docx`. Weekly theme "That's Me" — everyday
 * overthinking, anticipation and mental attention.
 *
 * ============================================================================
 * EVERY STRING OF PROSE BELOW IS THE WORKBOOK'S OWN WORDING.
 * ============================================================================
 *
 * Transcribed mechanically by `scripts/content-hub/m2w3-generate.py`. Regenerating from the same
 * workbook reproduces this file byte for byte.
 *
 * EDITORIAL REFS. These are `M2-W3-*`. The bare `W3-*` refs belong to published Month 1 Week 3
 * content ("honest conversations with yourself") and are untouched by this module.
 *
 * A001 IS DUPLICATED IN THE SOURCE. The workbook repeats the entire A001 asset verbatim at lines
 * 1758-2350. Only the FIRST copy (1154-1746) is read; the generator never looks past 1457.
 *
 * SCAFFOLDING. Production instructions ("Suggested copy:", "One H1 only.", "Do not claim a
 * clinical mechanism.", "Do not say:", "Safety Rule", …) are excluded BY LINE NUMBER and each
 * exclusion is asserted against its expected text, so the word "Important" — which is genuine
 * reader copy in G001's summary list and A001's summary box — is never stripped by accident.
 *
 * DELIBERATELY ABSENT:
 *   - `safety_notice` on all three. The workbook's BRAND GUARDRAILS / SAFETY GUARDRAILS sections
 *     are Must/Must-Not instructions for writers, not reader-facing safety copy.
 *   - G001 `meta_description`. The workbook value is 165 characters, over the 160 limit. It is
 *     left null rather than truncated or rewritten; the original is preserved in editorial notes.
 *   - G001 `key_statements`. The workbook has no Key Statements section. PART 45 GEO KEY TERMS is
 *     a list of terms and PART 28's qualities are single words; neither is a statement, so none
 *     is manufactured. The resulting GEO checklist failure is expected.
 *   - Links to Journal, Mood and Progress (authenticated `/app/*` only) and to a "SOLACE Learning
 *     Hub", which has no registered public route.
 */

import type { Week1Asset, Week1LinkSpec } from '../week1/week1-content';
import type { ContentBody, InlineContent } from '@meetezri/shared';

/** A span of plain text. */
const t = (text: string): InlineContent => [{ text }];

/** Month 2 Week 3 reuses the Week 1 asset and link contracts EXACTLY. */
export type M2W3LinkSpec = Week1LinkSpec;
export type M2W3Asset = Week1Asset;

// ─────────────────────────────────────────────────────────────────────────────
// M2-W3-B001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W3_B001: M2W3Asset = {
  editorialRef: "M2-W3-B001",
  contentType: 'seo_blog',
  publicLabel: 'Article',
  title: "Why Do I Overthink Small Things? Everyday Reasons Some Moments Stay on Your Mind",
  slug: "why-do-i-overthink-small-things",
  metaDescription: "Why do small conversations, messages or decisions stay on your mind? Explore everyday reasons some moments receive more attention than expected.",
  week: 3,
  pillar: 'Everyday Wellbeing, Reflection and Self-Awareness',
  tags: ['everyday-overthinking', 'anticipation', 'mental-attention', 'month-2', 'week-3'],

  typeFields: {
    keywords: { primary: 'why do I overthink small things' },
    funnel_stage: 'Discovery',
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'SEO Authority Article — everyday search intent and organic discovery.',
    goal: 'Organic Search Traffic',
    // The workbook distinguishes the public H1 from the SEO title; the schema has no separate
    // SEO-title field, so the approved value is recorded rather than dropped.
    seo_title_note: "Why Do I Overthink Small Things? Everyday Reasons Explained | SOLACE",
  },

  body: {
    version: 1,
    blocks: [
      { id: "m3b-h1", type: 'heading', level: 2, content: t("What Does “Overthinking Small Things” Usually Mean?") },
      { id: "m3b-p2", type: 'paragraph', content: t("People often use the word “overthinking” when a small moment keeps returning to their attention.") },
      { id: "m3b-p3", type: 'paragraph', content: t("It might be:") },
      { id: "m3b-p4", type: 'paragraph', content: t("A message they sent.") },
      { id: "m3b-p5", type: 'paragraph', content: t("Something someone said.") },
      { id: "m3b-p6", type: 'paragraph', content: t("A short conversation.") },
      { id: "m3b-p7", type: 'paragraph', content: t("An upcoming appointment.") },
      { id: "m3b-p8", type: 'paragraph', content: t("A decision.") },
      { id: "m3b-p9", type: 'paragraph', content: t("A piece of work they already completed.") },
      { id: "m3b-p10", type: 'paragraph', content: t("An answer they are waiting for.") },
      { id: "m3b-p11", type: 'paragraph', content: t("The moment itself may be brief, but the thinking around it continues.") },
      { id: "m3b-p12", type: 'paragraph', content: t("That does not automatically mean the moment was objectively important.") },
      { id: "m3b-p13", type: 'paragraph', content: t("Sometimes it simply means there was something about it that your attention had not fully moved away from yet.") },
      { id: "m3b-h14", type: 'heading', level: 2, content: t("Why Can Small Moments Stay on Your Mind?") },
      { id: "m3b-p15", type: 'paragraph', content: t("There is rarely one single reason.") },
      { id: "m3b-p16", type: 'paragraph', content: t("Sometimes a small moment contains uncertainty.") },
      { id: "m3b-p17", type: 'paragraph', content: t("Sometimes it feels unfinished.") },
      { id: "m3b-p18", type: 'paragraph', content: t("Sometimes you are waiting for another person.") },
      { id: "m3b-p19", type: 'paragraph', content: t("Sometimes it matters because of what it represents rather than how long it takes.") },
      { id: "m3b-p20", type: 'paragraph', content: t("And sometimes it becomes noticeable only after the rest of the day becomes quiet.") },
      { id: "m3b-h21", type: 'heading', level: 2, content: t("1. Uncertainty Can Keep a Moment Mentally Open") },
      { id: "m3b-p22", type: 'paragraph', content: t("Examples:") },
      { id: "m3b-p23", type: 'paragraph', content: t("Did they understand what I meant?") },
      { id: "m3b-p24", type: 'paragraph', content: t("Was that email clear?") },
      { id: "m3b-p25", type: 'paragraph', content: t("What will they say?") },
      { id: "m3b-p26", type: 'paragraph', content: t("Should I have worded that differently?") },
      { id: "m3b-p27", type: 'paragraph', content: t("What happens next?") },
      { id: "m3b-p28", type: 'paragraph', content: t("When something has no clear answer yet, attention can return to it.") },
      { id: "m3b-p29", type: 'paragraph', content: t("The task may technically be finished.") },
      { id: "m3b-p30", type: 'paragraph', content: t("The uncertainty is not.") },
      { id: "m3b-h31", type: 'heading', level: 3, content: t("Important Tone") },
      { id: "m3b-p32", type: 'paragraph', content: t("Keep it observational.") },
      { id: "m3b-h33", type: 'heading', level: 2, content: t("2. Anticipation Can Last Longer Than the Event") },
      { id: "m3b-p34", type: 'paragraph', content: t("This connects directly to Week 3’s strongest theme.") },
      { id: "m3b-p35", type: 'paragraph', content: t("You may think about a phone call for hours, then finish it in five minutes.") },
      { id: "m3b-p36", type: 'paragraph', content: t("You may rehearse a conversation repeatedly, then receive a simple:") },
      { id: "m3b-p37", type: 'paragraph', content: t("“Sure.”") },
      { id: "m3b-p38", type: 'paragraph', content: t("“No problem.”") },
      { id: "m3b-p39", type: 'paragraph', content: t("“That works.”") },
      { id: "m3b-p40", type: 'paragraph', content: t("The difference between anticipation and reality can be surprisingly large.") },
      { id: "m3b-p41", type: 'paragraph', content: t("Sometimes the time spent thinking about a moment has very little relationship to how long the actual moment takes.") },
      { id: "m3b-h42", type: 'heading', level: 2, content: t("3. Unfinished Moments Can Keep Returning to Your Attention") },
      { id: "m3b-p43", type: 'paragraph', content: t("Examples:") },
      { id: "m3b-p44", type: 'paragraph', content: t("A message you still need to answer.") },
      { id: "m3b-p45", type: 'paragraph', content: t("A booking you need to make.") },
      { id: "m3b-p46", type: 'paragraph', content: t("A question you want to ask.") },
      { id: "m3b-p47", type: 'paragraph', content: t("Something waiting for approval.") },
      { id: "m3b-p48", type: 'paragraph', content: t("A decision you have not made.") },
      { id: "m3b-p49", type: 'paragraph', content: t("These moments can quietly follow you while you do other things.") },
      { id: "m3b-p50", type: 'paragraph', content: t("You may not be actively thinking about them every second.") },
      { id: "m3b-p51", type: 'paragraph', content: t("But they keep reappearing.") },
      { id: "m3b-h52", type: 'heading', level: 2, content: t("4. A Small Task Can Carry a Bigger Meaning") },
      { id: "m3b-p53", type: 'paragraph', content: t("A task can be short but still matter.") },
      { id: "m3b-p54", type: 'paragraph', content: t("For example:") },
      { id: "m3b-p55", type: 'paragraph', content: t("Sending an application.") },
      { id: "m3b-p56", type: 'paragraph', content: t("Asking for time off.") },
      { id: "m3b-p57", type: 'paragraph', content: t("Sharing finished work.") },
      { id: "m3b-p58", type: 'paragraph', content: t("Waiting for interview feedback.") },
      { id: "m3b-p59", type: 'paragraph', content: t("Telling someone good news.") },
      { id: "m3b-p60", type: 'paragraph', content: t("Having a conversation you care about.") },
      { id: "m3b-p61", type: 'paragraph', content: t("The action itself may be small.") },
      { id: "m3b-p62", type: 'paragraph', content: t("What it represents may not be.") },
      { id: "m3b-p63", type: 'paragraph', content: t("This distinction is useful because it keeps the article from dismissing people with:") },
      { id: "m3b-p64", type: 'paragraph', content: t("“It's only a small thing.”") },
      { id: "m3b-h65", type: 'heading', level: 2, content: t("5. Quiet Moments Can Make Other Thoughts Easier to Notice") },
      { id: "m3b-p66", type: 'paragraph', content: t("Sometimes you do not remember everything while you are busy.") },
      { id: "m3b-p67", type: 'paragraph', content: t("You remember it when you finally stop.") },
      { id: "m3b-p68", type: 'paragraph', content: t("You sit down.") },
      { id: "m3b-p69", type: 'paragraph', content: t("Get on the train.") },
      { id: "m3b-p70", type: 'paragraph', content: t("Finish work.") },
      { id: "m3b-p71", type: 'paragraph', content: t("Get into bed.") },
      { id: "m3b-p72", type: 'paragraph', content: t("And suddenly:") },
      { id: "m3b-p73", type: 'paragraph', content: t("The message.") },
      { id: "m3b-p74", type: 'paragraph', content: t("Tomorrow.") },
      { id: "m3b-p75", type: 'paragraph', content: t("The appointment.") },
      { id: "m3b-p76", type: 'paragraph', content: t("The thing you meant to look up.") },
      { id: "m3b-p77", type: 'paragraph', content: t("The conversation.") },
      { id: "m3b-p78", type: 'paragraph', content: t("The quiet did not necessarily create those thoughts.") },
      { id: "m3b-p79", type: 'paragraph', content: t("It may simply be the first moment you noticed them clearly.") },
      { id: "m3b-h80", type: 'heading', level: 2, content: t("6. Positive Moments Can Take Up Mental Space Too") },
      { id: "m3b-p81", type: 'paragraph', content: t("This section is mandatory.") },
      { id: "m3b-p82", type: 'paragraph', content: t("Not everything that stays on your mind is difficult.") },
      { id: "m3b-p83", type: 'paragraph', content: t("You might keep thinking about:") },
      { id: "m3b-p84", type: 'paragraph', content: t("Good news you are waiting to share.") },
      { id: "m3b-p85", type: 'paragraph', content: t("Something you are proud of.") },
      { id: "m3b-p86", type: 'paragraph', content: t("An upcoming trip.") },
      { id: "m3b-p87", type: 'paragraph', content: t("A new opportunity.") },
      { id: "m3b-p88", type: 'paragraph', content: t("A conversation you are excited to have.") },
      { id: "m3b-p89", type: 'paragraph', content: t("Something someone said that made you smile.") },
      { id: "m3b-p90", type: 'paragraph', content: t("The mind can return to anticipation, excitement, gratitude and possibility just as easily as it returns to uncertainty.") },
      { id: "m3b-p91", type: 'paragraph', content: t("That is why reflection should not only ask:") },
      { id: "m3b-h92", type: 'heading', level: 3, content: t("“What is bothering me?”") },
      { id: "m3b-p93", type: 'paragraph', content: t("It can also ask:") },
      { id: "m3b-p94", type: 'paragraph', content: t("“What am I holding onto because it matters to me?”") },
      { id: "m3b-h95", type: 'heading', level: 2, content: t("When Is Reflection Useful?") },
      { id: "m3b-p96", type: 'paragraph', content: t("Reflection can be useful when it helps you notice where your attention keeps returning.") },
      { id: "m3b-p97", type: 'paragraph', content: t("Not because every recurring thought needs to be solved.") },
      { id: "m3b-p98", type: 'paragraph', content: t("Sometimes noticing the pattern is enough to understand what has been occupying part of your day.") },
      { id: "m3b-p99", type: 'paragraph', content: t("A useful question might be:") },
      { id: "m3b-h100", type: 'heading', level: 3, content: t("What keeps coming back to mind, even when I am doing something else?") },
      { id: "m3b-p101", type: 'paragraph', content: t("Then:") },
      { id: "m3b-h102", type: 'heading', level: 3, content: t("Is it unfinished, uncertain, important—or simply something I care about?") },
      { id: "m3b-h103", type: 'heading', level: 2, content: t("Simple Questions to Help You Notice the Pattern") },
      { id: "m3b-list104", type: 'list', style: 'bullet', items: [t("What have I returned to in my thoughts more than once today?"), t("Is there something I am waiting for?"), t("Is there a conversation I keep rehearsing?"), t("Is something unfinished?"), t("Is there something I am excited about?"), t("Did the anticipation last longer than the actual moment?"), t("What would I like to give less attention to?"), t("What is actually worth holding onto?")] },
      { id: "m3b-p105", type: 'paragraph', content: t("These questions should feel reflective, not diagnostic.") },
      { id: "m3b-p106", type: 'paragraph', content: t("SOLACE is built around creating space for everyday reflection like this—not only during difficult moments, but also around work, decisions, routines, relationships, progress, excitement and the small experiences that stay with us longer than expected.") },
      { id: "m3b-p107", type: 'paragraph', content: t("What has been taking up more attention than you expected?") },
      { id: "m3b-p108", type: 'paragraph', content: t("Sometimes naming the moment is enough to understand why it has stayed with you.") },
      { id: 'm3b-cta', type: 'cta', label: "Explore SOLACE’s everyday reflection tools.", target: { kind: 'route', value: 'resource_library' } },
      { id: 'm3b-faq', type: 'faq', heading: 'Frequently Asked Questions', items: [{ id: "m3b-faq-1", question: "Why do I overthink small conversations?", answer: t("A short conversation can stay in your thoughts when the outcome, wording or other person’s response matters to you. The conversation may be brief, while uncertainty around it lasts longer.") }, { id: "m3b-faq-2", question: "Why do I replay messages after I send them?", answer: t("You may revisit a message because you are thinking about how it was understood or what response might come next. The action of sending is complete, but the social outcome may still feel open.") }, { id: "m3b-faq-3", question: "Why do I think about something all day when it only takes a few minutes?", answer: t("Anticipation can take up much more time than the event itself. You may mentally prepare for a conversation, call, appointment or decision long before it happens.") }, { id: "m3b-faq-4", question: "Why do I suddenly remember things when I finally relax?", answer: t("When your attention is no longer occupied by the activity in front of you, other unfinished thoughts and reminders may become easier to notice.") }, { id: "m3b-faq-5", question: "Is it normal to think a lot about positive things too?", answer: t("Yes. Excitement, good news, anticipation, pride and meaningful moments can also stay in your thoughts. Reflection is not only about difficult experiences.") }, { id: "m3b-faq-6", question: "How can I reflect without overcomplicating it?", answer: t("Try identifying one thing that kept returning to your attention and ask what made it feel unfinished, uncertain, important or worth remembering. You do not need to turn every thought into a problem to solve.") }] },
      { id: "m3b-h109", type: 'heading', level: 2, content: t("Sometimes the Smallest Moments Stay the Longest") },
      { id: "m3b-p110", type: 'paragraph', content: t("A moment does not need to be dramatic to stay with you.") },
      { id: "m3b-p111", type: 'paragraph', content: t("Sometimes it is one line in an email.") },
      { id: "m3b-p112", type: 'paragraph', content: t("A short conversation.") },
      { id: "m3b-p113", type: 'paragraph', content: t("A decision.") },
      { id: "m3b-p114", type: 'paragraph', content: t("A question.") },
      { id: "m3b-p115", type: 'paragraph', content: t("A wait.") },
      { id: "m3b-p116", type: 'paragraph', content: t("Or a piece of good news you are still carrying around.") },
      { id: "m3b-p117", type: 'paragraph', content: t("The useful part is not judging yourself for thinking about it.") },
      { id: "m3b-p118", type: 'paragraph', content: t("It is simply noticing:") },
      { id: "m3b-p119", type: 'paragraph', content: t("“This has been taking up some of my attention.”") },
      { id: "m3b-p120", type: 'paragraph', content: t("From there, you can decide whether it needs action, reflection—or whether it is simply something worth acknowledging.") },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W3-G001', anchorText: 'anticipation and everyday mental attention', relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W3-A001', anchorText: 'common questions about why small things stay on your mind', relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'resource_library', anchorText: "Explore SOLACE's everyday reflection tools.", relation: 'resource_library' },
  ],

  authoredOutsideWorkbook: ['cta block (anchor and destination from the workbook PART 26 CTA block)'],
  missingFields: ['safety_notice (workbook supplies no reader-facing safety copy)', 'workbook references left UNLINKED (no public route): Journal, Mood, Progress (/app/* authenticated), SOLACE Learning Hub (no registered route)', 'seo_title (no schema field distinct from title)'],
};

// ─────────────────────────────────────────────────────────────────────────────
// M2-W3-G001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W3_G001: M2W3Asset = {
  editorialRef: "M2-W3-G001",
  contentType: 'geo_article',
  publicLabel: 'Insight',
  title: "Anticipation and Mental Attention: Why Small Moments Can Stay on Your Mind",
  slug: "anticipation-and-mental-attention",
  metaDescription: null,
  week: 3,
  pillar: 'Everyday Wellbeing, Reflection and Self-Awareness',
  tags: ['everyday-overthinking', 'anticipation', 'mental-attention', 'month-2', 'week-3'],

  typeFields: {
    core_concept: "Anticipation, Everyday Thoughts and Mental Attention",
    citation_summary: "Anticipation can make a small moment occupy attention for much longer than the event itself. This may happen when the situation feels uncertain, unfinished, important or exciting. Waiting for a response, preparing for a conversation or looking forward to good news can all keep a moment mentally active before it happens.",
    // key_statements is intentionally ABSENT: the workbook supplies no Key Statements section and
    // none is manufactured. This is a known, reported publish blocker.
    topics: {
      primary: 'Anticipation',
      secondary: ['Mental Attention', 'Everyday Wellbeing'],
    },
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'GEO knowledge resource supporting B001 and A001.',
    goal: 'AI Search Authority',
    geo_focus: 'AI Retrieval',
    // 165 characters — over the 160-character limit, so it is NOT stored as meta_description.
    // Preserved verbatim here for manual correction in Admin.
    meta_description_oversize_note: "",
  },

  body: {
    version: 1,
    blocks: [
      { id: "m3g-p1", type: 'paragraph', content: t("What is anticipation in everyday life?") },
      { id: "m3g-p2", type: 'paragraph', content: t("Anticipation is the period of thought, expectation or preparation that can happen before a moment, decision or response.") },
      { id: "m3g-p3", type: 'paragraph', content: t("In everyday life, anticipation might involve:") },
      { id: "m3g-p4", type: 'paragraph', content: t("Thinking about a conversation before it happens.") },
      { id: "m3g-p5", type: 'paragraph', content: t("Waiting for an email or message.") },
      { id: "m3g-p6", type: 'paragraph', content: t("Preparing to ask a question.") },
      { id: "m3g-p7", type: 'paragraph', content: t("Thinking about an appointment.") },
      { id: "m3g-p8", type: 'paragraph', content: t("Looking forward to good news.") },
      { id: "m3g-p9", type: 'paragraph', content: t("Waiting to share something exciting.") },
      { id: "m3g-p10", type: 'paragraph', content: t("The actual event may be brief, while the anticipation surrounding it lasts much longer.") },
      { id: "m3g-p11", type: 'paragraph', content: t("In simple terms") },
      { id: "m3g-p12", type: 'paragraph', content: t("Small moments can stay in your attention when they feel:") },
      { id: "m3g-h13", type: 'heading', level: 3, content: t("Uncertain") },
      { id: "m3g-h14", type: 'heading', level: 3, content: t("Unfinished") },
      { id: "m3g-h15", type: 'heading', level: 3, content: t("Important") },
      { id: "m3g-h16", type: 'heading', level: 3, content: t("Anticipated") },
      { id: "m3g-h17", type: 'heading', level: 3, content: t("Emotionally meaningful") },
      { id: "m3g-p18", type: 'paragraph', content: t("or simply:") },
      { id: "m3g-p19", type: 'paragraph', content: t("worth remembering") },
      { id: "m3g-p20", type: 'paragraph', content: t("That applies to both difficult and positive experiences.") },
      { id: "m3g-h21", type: 'heading', level: 2, content: t("What Is Anticipation?") },
      { id: "m3g-p22", type: 'paragraph', content: t("Anticipation is the period before something happens when your attention may return to what is coming next.") },
      { id: "m3g-p23", type: 'paragraph', content: t("It can happen around large events.") },
      { id: "m3g-p24", type: 'paragraph', content: t("But it can also happen around very small moments.") },
      { id: "m3g-p25", type: 'paragraph', content: t("Examples:") },
      { id: "m3g-p26", type: 'paragraph', content: t("A short phone call.") },
      { id: "m3g-p27", type: 'paragraph', content: t("A message you are waiting for.") },
      { id: "m3g-p28", type: 'paragraph', content: t("A question you plan to ask.") },
      { id: "m3g-p29", type: 'paragraph', content: t("A meeting.") },
      { id: "m3g-p30", type: 'paragraph', content: t("An appointment.") },
      { id: "m3g-p31", type: 'paragraph', content: t("Sharing something you finished.") },
      { id: "m3g-p32", type: 'paragraph', content: t("Waiting to tell someone good news.") },
      { id: "m3g-p33", type: 'paragraph', content: t("Anticipation does not automatically mean fear or stress.") },
      { id: "m3g-p34", type: 'paragraph', content: t("It can include:") },
      { id: "m3g-p35", type: 'paragraph', content: t("Curiosity.") },
      { id: "m3g-p36", type: 'paragraph', content: t("Excitement.") },
      { id: "m3g-p37", type: 'paragraph', content: t("Uncertainty.") },
      { id: "m3g-p38", type: 'paragraph', content: t("Hope.") },
      { id: "m3g-p39", type: 'paragraph', content: t("Preparation.") },
      { id: "m3g-p40", type: 'paragraph', content: t("Interest.") },
      { id: "m3g-h41", type: 'heading', level: 2, content: t("Why Can Small Moments Take Up So Much Attention?") },
      { id: "m3g-p42", type: 'paragraph', content: t("The amount of attention a moment receives is not always related to how long the moment itself lasts.") },
      { id: "m3g-p43", type: 'paragraph', content: t("A two-minute conversation may receive hours of thought.") },
      { id: "m3g-p44", type: 'paragraph', content: t("A single email may be rewritten several times.") },
      { id: "m3g-p45", type: 'paragraph', content: t("A one-line response may be checked repeatedly while someone waits.") },
      { id: "m3g-p46", type: 'paragraph', content: t("This can happen because the moment still feels open in some way.") },
      { id: "m3g-p47", type: 'paragraph', content: t("There may be uncertainty.") },
      { id: "m3g-p48", type: 'paragraph', content: t("A response may still be coming.") },
      { id: "m3g-p49", type: 'paragraph', content: t("A decision may still be unfinished.") },
      { id: "m3g-p50", type: 'paragraph', content: t("The moment may simply matter to you.") },
      { id: "m3g-h51", type: 'heading', level: 2, content: t("Uncertainty Can Keep Attention Returning") },
      { id: "m3g-p52", type: 'paragraph', content: t("Examples:") },
      { id: "m3g-p53", type: 'paragraph', content: t("What will they say?") },
      { id: "m3g-p54", type: 'paragraph', content: t("Did I explain that clearly?") },
      { id: "m3g-p55", type: 'paragraph', content: t("Will they agree?") },
      { id: "m3g-p56", type: 'paragraph', content: t("Is this the right time?") },
      { id: "m3g-p57", type: 'paragraph', content: t("What happens next?") },
      { id: "m3g-p58", type: 'paragraph', content: t("When there is no clear outcome yet, attention may return to the situation.") },
      { id: "m3g-p59", type: 'paragraph', content: t("This does not automatically mean the person is doing anything wrong.") },
      { id: "m3g-p60", type: 'paragraph', content: t("It simply describes one way everyday attention can behave around uncertainty.") },
      { id: "m3g-h61", type: 'heading', level: 2, content: t("Unfinished Moments Can Stay Active in Your Thoughts") },
      { id: "m3g-p62", type: 'paragraph', content: t("Common examples:") },
      { id: "m3g-p63", type: 'paragraph', content: t("An unanswered message.") },
      { id: "m3g-p64", type: 'paragraph', content: t("A booking that still needs to be made.") },
      { id: "m3g-p65", type: 'paragraph', content: t("A decision.") },
      { id: "m3g-p66", type: 'paragraph', content: t("A question that still needs asking.") },
      { id: "m3g-p67", type: 'paragraph', content: t("Something waiting for approval.") },
      { id: "m3g-p68", type: 'paragraph', content: t("A task you have technically finished but have not yet submitted.") },
      { id: "m3g-p69", type: 'paragraph', content: t("A piece of news you have not shared.") },
      { id: "m3g-p70", type: 'paragraph', content: t("These are ordinary moments.") },
      { id: "m3g-p71", type: 'paragraph', content: t("They can remain mentally noticeable because they are not fully complete yet.") },
      { id: "m3g-h72", type: 'heading', level: 2, content: t("Anticipation Can Last Longer Than the Actual Event") },
      { id: "m3g-p73", type: 'paragraph', content: t("This is a key Week 3 idea.") },
      { id: "m3g-p74", type: 'paragraph', content: t("The actual moment may be very short.") },
      { id: "m3g-p75", type: 'paragraph', content: t("The period leading up to it may be much longer.") },
      { id: "m3g-p76", type: 'paragraph', content: t("For example:") },
      { id: "m3g-p77", type: 'paragraph', content: t("You think about a conversation all afternoon.") },
      { id: "m3g-p78", type: 'paragraph', content: t("The conversation lasts one minute.") },
      { id: "m3g-p79", type: 'paragraph', content: t("You prepare to make a phone call.") },
      { id: "m3g-p80", type: 'paragraph', content: t("The call is finished quickly.") },
      { id: "m3g-p81", type: 'paragraph', content: t("You check a document repeatedly.") },
      { id: "m3g-p82", type: 'paragraph', content: t("Sending it takes one click.") },
      { id: "m3g-p83", type: 'paragraph', content: t("This difference between anticipation and the event itself is one reason small moments can feel larger in our attention than they are in time.") },
      { id: "m3g-h84", type: 'heading', level: 2, content: t("Quiet Moments Can Make Other Thoughts Easier to Notice") },
      { id: "m3g-p85", type: 'paragraph', content: t("Many people notice unfinished thoughts when activity slows down.") },
      { id: "m3g-p86", type: 'paragraph', content: t("Examples:") },
      { id: "m3g-p87", type: 'paragraph', content: t("After work.") },
      { id: "m3g-p88", type: 'paragraph', content: t("On a commute.") },
      { id: "m3g-p89", type: 'paragraph', content: t("When sitting down.") },
      { id: "m3g-p90", type: 'paragraph', content: t("When waiting somewhere.") },
      { id: "m3g-p91", type: 'paragraph', content: t("Before bed.") },
      { id: "m3g-p92", type: 'paragraph', content: t("After finishing a task.") },
      { id: "m3g-p93", type: 'paragraph', content: t("This does not necessarily mean the quiet moment created the thoughts.") },
      { id: "m3g-p94", type: 'paragraph', content: t("It may simply be the first time there is enough space to notice what has been sitting in the background.") },
      { id: "m3g-h95", type: 'heading', level: 2, content: t("Positive Anticipation Matters Too") },
      { id: "m3g-p96", type: 'paragraph', content: t("This section is mandatory.") },
      { id: "m3g-p97", type: 'paragraph', content: t("Anticipation is not only about difficult moments.") },
      { id: "m3g-p98", type: 'paragraph', content: t("People may also repeatedly think about:") },
      { id: "m3g-p99", type: 'paragraph', content: t("Good news.") },
      { id: "m3g-p100", type: 'paragraph', content: t("An upcoming trip.") },
      { id: "m3g-p101", type: 'paragraph', content: t("A promotion.") },
      { id: "m3g-p102", type: 'paragraph', content: t("A celebration.") },
      { id: "m3g-p103", type: 'paragraph', content: t("Seeing someone.") },
      { id: "m3g-p104", type: 'paragraph', content: t("Sharing something they are proud of.") },
      { id: "m3g-p105", type: 'paragraph', content: t("Starting a new opportunity.") },
      { id: "m3g-p106", type: 'paragraph', content: t("Receiving an answer they hope for.") },
      { id: "m3g-p107", type: 'paragraph', content: t("The same pattern can appear:") },
      { id: "m3g-p108", type: 'paragraph', content: t("The moment is still ahead.") },
      { id: "m3g-p109", type: 'paragraph', content: t("The mind keeps returning to it.") },
      { id: "m3g-p110", type: 'paragraph', content: t("The difference is that the emotional tone may be excitement, hope, curiosity or joy.") },
      { id: "m3g-h111", type: 'heading', level: 2, content: t("Everyday Examples") },
      { id: "m3g-p112", type: 'paragraph', content: t("This improves machine-readable structure and human clarity.") },
      { id: "m3g-h113", type: 'heading', level: 2, content: t("Anticipation at Work") },
      { id: "m3g-p114", type: 'paragraph', content: t("At work, anticipation may appear around:") },
      { id: "m3g-p115", type: 'paragraph', content: t("Client calls.") },
      { id: "m3g-p116", type: 'paragraph', content: t("Presentations.") },
      { id: "m3g-p117", type: 'paragraph', content: t("Asking for feedback.") },
      { id: "m3g-p118", type: 'paragraph', content: t("Submitting work.") },
      { id: "m3g-p119", type: 'paragraph', content: t("Waiting for approval.") },
      { id: "m3g-p120", type: 'paragraph', content: t("Talking to a manager.") },
      { id: "m3g-p121", type: 'paragraph', content: t("Starting a new role.") },
      { id: "m3g-p122", type: 'paragraph', content: t("Sharing an idea.") },
      { id: "m3g-p123", type: 'paragraph', content: t("Receiving good news.") },
      { id: "m3g-p124", type: 'paragraph', content: t("The point is not that work is inherently stressful.") },
      { id: "m3g-p125", type: 'paragraph', content: t("It is that professional life contains many moments where the next response or outcome is not fully known yet.") },
      { id: "m3g-h126", type: 'heading', level: 2, content: t("Anticipation Outside Work") },
      { id: "m3g-p127", type: 'paragraph', content: t("Examples:") },
      { id: "m3g-p128", type: 'paragraph', content: t("Appointments.") },
      { id: "m3g-p129", type: 'paragraph', content: t("Family conversations.") },
      { id: "m3g-p130", type: 'paragraph', content: t("Plans.") },
      { id: "m3g-p131", type: 'paragraph', content: t("Travel.") },
      { id: "m3g-p132", type: 'paragraph', content: t("Messages.") },
      { id: "m3g-p133", type: 'paragraph', content: t("Personal decisions.") },
      { id: "m3g-p134", type: 'paragraph', content: t("Waiting for news.") },
      { id: "m3g-p135", type: 'paragraph', content: t("Social events.") },
      { id: "m3g-p136", type: 'paragraph', content: t("Purchases.") },
      { id: "m3g-p137", type: 'paragraph', content: t("Celebrations.") },
      { id: "m3g-p138", type: 'paragraph', content: t("Small everyday responsibilities.") },
      { id: "m3g-p139", type: 'paragraph', content: t("This keeps the resource broader than workplace-only content.") },
      { id: "m3g-h140", type: 'heading', level: 2, content: t("What Is Mental Attention in This Context?") },
      { id: "m3g-p141", type: 'paragraph', content: t("Here, “mental attention” means the thoughts or moments that keep returning to awareness during the day.") },
      { id: "m3g-p142", type: 'paragraph', content: t("It does not mean a clinical assessment of attention.") },
      { id: "m3g-p143", type: 'paragraph', content: t("It simply refers to where part of a person’s thinking keeps going.") },
      { id: "m3g-p144", type: 'paragraph', content: t("For example:") },
      { id: "m3g-p145", type: 'paragraph', content: t("A conversation that keeps replaying.") },
      { id: "m3g-p146", type: 'paragraph', content: t("A task that keeps coming back to mind.") },
      { id: "m3g-p147", type: 'paragraph', content: t("An answer being waited for.") },
      { id: "m3g-p148", type: 'paragraph', content: t("Something exciting coming up.") },
      { id: "m3g-h149", type: 'heading', level: 2, content: t("Reflection Can Help You Notice the Pattern") },
      { id: "m3g-p150", type: 'paragraph', content: t("Reflection does not need to mean analysing every thought.") },
      { id: "m3g-p151", type: 'paragraph', content: t("A useful starting point can be simply noticing:") },
      { id: "m3g-p152", type: 'paragraph', content: t("What keeps returning?") },
      { id: "m3g-p153", type: 'paragraph', content: t("Is it unfinished?") },
      { id: "m3g-p154", type: 'paragraph', content: t("Is it uncertain?") },
      { id: "m3g-p155", type: 'paragraph', content: t("Is it important?") },
      { id: "m3g-p156", type: 'paragraph', content: t("Am I waiting for something?") },
      { id: "m3g-p157", type: 'paragraph', content: t("Am I looking forward to something?") },
      { id: "m3g-p158", type: 'paragraph', content: t("Sometimes identifying the reason a moment keeps returning can make the pattern easier to understand.") },
      { id: "m3g-list159", type: 'list', style: 'bullet', items: [t("What has returned to my attention more than once today?"), t("Am I waiting for an answer?"), t("Is there something unfinished?"), t("Is there a conversation I keep rehearsing?"), t("Is there something I am looking forward to?"), t("Is there something I already completed but keep checking?"), t("Is the actual moment likely to be shorter than the anticipation?"), t("Is there something positive I want to hold onto?")] },
      { id: "m3g-h160", type: 'heading', level: 2, content: t("What Anticipation Does Not Automatically Mean") },
      { id: "m3g-p161", type: 'paragraph', content: t("This section is important for safety and clarity.") },
      { id: "m3g-p162", type: 'paragraph', content: t("Anticipation does not automatically mean that someone is:") },
      { id: "m3g-p163", type: 'paragraph', content: t("Anxious.") },
      { id: "m3g-p164", type: 'paragraph', content: t("Unwell.") },
      { id: "m3g-p165", type: 'paragraph', content: t("Unable to cope.") },
      { id: "m3g-p166", type: 'paragraph', content: t("Experiencing a disorder.") },
      { id: "m3g-p167", type: 'paragraph', content: t("“Overthinking” in a clinical sense.") },
      { id: "m3g-p168", type: 'paragraph', content: t("Everyday anticipation can simply be part of caring about an outcome, waiting for information, preparing for something or thinking about what comes next.") },
      { id: "m3g-h169", type: 'heading', level: 2, content: t("Why the Same Moment Can Feel Different for Different People") },
      { id: "m3g-p170", type: 'paragraph', content: t("The same event can receive different amounts of attention depending on:") },
      { id: "m3g-p171", type: 'paragraph', content: t("How important it feels.") },
      { id: "m3g-p172", type: 'paragraph', content: t("Whether there is uncertainty.") },
      { id: "m3g-p173", type: 'paragraph', content: t("Whether another person’s response matters.") },
      { id: "m3g-p174", type: 'paragraph', content: t("Whether it is unfinished.") },
      { id: "m3g-p175", type: 'paragraph', content: t("Whether it represents something bigger.") },
      { id: "m3g-p176", type: 'paragraph', content: t("Whether the person is excited about it.") },
      { id: "m3g-p177", type: 'paragraph', content: t("This keeps the content nuanced without making unsupported psychological claims.") },
      { id: "m3g-p178", type: 'paragraph', content: t("Key Takeaway") },
      { id: "m3g-p179", type: 'paragraph', content: t("Anticipation can make a short event occupy attention for much longer than the event itself.") },
      { id: "m3g-p180", type: 'paragraph', content: t("Common reasons include:") },
      { id: "m3g-h181", type: 'heading', level: 3, content: t("Uncertainty") },
      { id: "m3g-h182", type: 'heading', level: 3, content: t("Waiting") },
      { id: "m3g-h183", type: 'heading', level: 3, content: t("Unfinished action") },
      { id: "m3g-h184", type: 'heading', level: 3, content: t("Importance") },
      { id: "m3g-h185", type: 'heading', level: 3, content: t("Excitement") },
      { id: "m3g-h186", type: 'heading', level: 3, content: t("Expectation") },
      { id: "m3g-p187", type: 'paragraph', content: t("A useful first step is simply noticing what keeps returning to mind and what may be keeping it there.") },
      { id: 'm3g-faq', type: 'faq', heading: 'Frequently Asked Questions', items: [{ id: "m3g-faq-1", question: "What is anticipation?", answer: t("Anticipation is the period of thought or expectation before something happens. It can involve uncertainty, preparation, excitement, hope or curiosity.") }, { id: "m3g-faq-2", question: "Why do I keep thinking about a conversation before it happens?", answer: t("A conversation can stay in your attention when you are thinking about what to say, how the other person may respond or what the outcome might be.") }, { id: "m3g-faq-3", question: "Why does waiting for a reply take so much attention?", answer: t("Waiting leaves the outcome unfinished. Your attention may return to the message because the next part of the situation has not happened yet.") }, { id: "m3g-faq-4", question: "Why do I think about a task after I already finished it?", answer: t("The action may be complete while uncertainty remains—for example, whether the work is ready, how it will be received or what happens next.") }, { id: "m3g-faq-5", question: "Can anticipation be positive?", answer: t("Yes. People can anticipate good news, celebrations, opportunities, travel, time with others or something they are proud to share.") }, { id: "m3g-faq-6", question: "Why do I remember things when I finally stop being busy?", answer: t("When activity slows down, other thoughts and unfinished reminders may simply become easier to notice.") }, { id: "m3g-faq-7", question: "Is anticipation the same as overthinking?", answer: t("Not necessarily. Anticipation simply means thinking ahead to something that has not happened yet. It may be brief or long, positive or difficult, and does not automatically indicate a problem.") }, { id: "m3g-faq-8", question: "How can I reflect on what is taking up my attention?", answer: t("Start by identifying one thought or situation that keeps returning and ask whether it feels unfinished, uncertain, important, exciting or connected to an outcome you are waiting for.") }] },
      { id: 'm3g-cta', type: 'cta', label: 'Explore more everyday reflection resources from SOLACE.', target: { kind: 'route', value: 'resource_library' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W3-B001', anchorText: null, relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W3-A001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'resource_library', anchorText: 'Explore more everyday reflection resources from SOLACE.', relation: 'resource_library' },
  ],

  authoredOutsideWorkbook: ['cta block (anchor and destination from the workbook PART 51 optional CTA)'],
  missingFields: ['safety_notice (workbook supplies no reader-facing safety copy)', 'meta_description (workbook value is 165 chars, over the 160 limit; left null by editorial decision)', 'key_statements (the workbook has no Key Statements section; none manufactured)', 'workbook references left UNLINKED (no public route): Journal, Mood, Progress (/app/* authenticated), SOLACE Learning Hub (no registered route)'],
};

// ─────────────────────────────────────────────────────────────────────────────
// M2-W3-A001
// ─────────────────────────────────────────────────────────────────────────────

const M2_W3_A001: M2W3Asset = {
  editorialRef: "M2-W3-A001",
  contentType: 'aeo_answer',
  publicLabel: 'Answer',
  title: "Why Do I Keep Thinking About Small Things? Common Questions About Everyday Overthinking",
  slug: "why-do-i-keep-thinking-about-small-things",
  metaDescription: "Why do conversations, messages and small decisions stay on your mind? Find clear answers to common questions about everyday overthinking and attention.",
  week: 3,
  pillar: 'Everyday Wellbeing, Reflection and Self-Awareness',
  tags: ['everyday-overthinking', 'anticipation', 'mental-attention', 'month-2', 'week-3'],

  typeFields: {
    primary_question: "Why do I keep thinking about small things?",
    supporting_queries: [
      "Why Do I Overthink Conversations After They Happen?",
      "Why Do I Rehearse Conversations Before They Happen?",
      "Why Do I Keep Thinking About an Email After I Send It?",
      "Why Do I Check Something I Already Finished?",
      "Why Does Waiting for a Reply Take So Much Attention?",
      "Why Do I Think About a Small Task for Hours Before Doing It?"
],
    snippet_answer: "Small moments can stay in your thoughts when they feel unfinished, uncertain, important or connected to an outcome you are still waiting for. Sometimes the moment itself is brief, while anticipation or reflection around it lasts much longer.",
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'AEO answer resource for the Week 3 authority cluster.',
    goal: 'Answer Engine Authority',
    aeo_signal: 'direct answer first',
    seo_title_note: "Why Do I Keep Thinking About Small Things? | SOLACE",
  },

  body: {
    version: 1,
    blocks: [
      { id: 'm3a-direct-answer', type: 'direct_answer', content: t("Small moments can stay in your thoughts when they feel unfinished, uncertain, important or connected to an outcome you are still waiting for. Sometimes the moment itself is brief, while anticipation or reflection around it lasts much longer.") },
      { id: "m3a-p1", type: 'paragraph', content: t("Sometimes a very small moment can stay in your thoughts for much longer than expected.") },
      { id: "m3a-p2", type: 'paragraph', content: t("A short conversation.") },
      { id: "m3a-p3", type: 'paragraph', content: t("A message.") },
      { id: "m3a-p4", type: 'paragraph', content: t("An email.") },
      { id: "m3a-p5", type: 'paragraph', content: t("A decision.") },
      { id: "m3a-p6", type: 'paragraph', content: t("Something you are waiting for.") },
      { id: "m3a-p7", type: 'paragraph', content: t("Or even something good you are excited to share.") },
      { id: "m3a-p8", type: 'paragraph', content: t("Below are clear answers to common questions about why everyday moments sometimes receive more attention than the moment itself seems to require.") },
      { id: "m3a-h9", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About Small Things?") },
      { id: "m3a-h10", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p11", type: 'paragraph', content: t("Small things can stay in your thoughts when they feel unfinished, uncertain, personally important or connected to something that has not happened yet.") },
      { id: "m3a-p12", type: 'paragraph', content: t("The event may be short, but your attention can return to it while you wait, prepare or think about what it means.") },
      { id: "m3a-h13", type: 'heading', level: 3, content: t("Example") },
      { id: "m3a-p14", type: 'paragraph', content: t("You send a short email.") },
      { id: "m3a-p15", type: 'paragraph', content: t("The action is complete.") },
      { id: "m3a-p16", type: 'paragraph', content: t("But you keep thinking about how it will be received.") },
      { id: "m3a-h17", type: 'heading', level: 2, content: t("Why Do I Overthink Conversations After They Happen?") },
      { id: "m3a-h18", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p19", type: 'paragraph', content: t("A conversation may stay in your thoughts when you are still considering what was said, how you came across or what the other person meant.") },
      { id: "m3a-p20", type: 'paragraph', content: t("The conversation may be over, while your interpretation of it continues.") },
      { id: "m3a-h21", type: 'heading', level: 3, content: t("Example") },
      { id: "m3a-p22", type: 'paragraph', content: t("The conversation lasted two minutes.") },
      { id: "m3a-p23", type: 'paragraph', content: t("You replay one sentence several times afterward.") },
      { id: "m3a-h24", type: 'heading', level: 2, content: t("Why Do I Rehearse Conversations Before They Happen?") },
      { id: "m3a-h25", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p26", type: 'paragraph', content: t("People often mentally prepare for conversations when they care about what they want to say or do not know exactly how the other person will respond.") },
      { id: "m3a-p27", type: 'paragraph', content: t("Rehearsing can be part of preparing for an uncertain or meaningful moment.") },
      { id: "m3a-h28", type: 'heading', level: 3, content: t("Week 3 Connection") },
      { id: "m3a-p29", type: 'paragraph', content: t("This aligns directly with R004:") },
      { id: "m3a-h30", type: 'heading', level: 3, content: t("You Practiced the Conversation 12 Times. It Lasted 40 Seconds.") },
      { id: "m3a-h31", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About an Email After I Send It?") },
      { id: "m3a-h32", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p33", type: 'paragraph', content: t("Sending the email finishes the action, but it may not finish the situation.") },
      { id: "m3a-p34", type: 'paragraph', content: t("You may still be waiting for a response, wondering how the message was understood or thinking about what happens next.") },
      { id: "m3a-h35", type: 'heading', level: 2, content: t("Why Do I Check Something I Already Finished?") },
      { id: "m3a-h36", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p37", type: 'paragraph', content: t("You may return to finished work when you are still thinking about whether it is ready, complete or likely to be received well.") },
      { id: "m3a-p38", type: 'paragraph', content: t("The task may technically be finished while uncertainty about the outcome remains.") },
      { id: "m3a-h39", type: 'heading', level: 2, content: t("Why Does Waiting for a Reply Take So Much Attention?") },
      { id: "m3a-h40", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p41", type: 'paragraph', content: t("Waiting leaves part of the situation unresolved.") },
      { id: "m3a-p42", type: 'paragraph', content: t("Because the next step depends on information you do not have yet, your attention may keep returning to the message or response you are waiting for.") },
      { id: "m3a-h43", type: 'heading', level: 2, content: t("Why Do I Think About a Small Task for Hours Before Doing It?") },
      { id: "m3a-h44", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p45", type: 'paragraph', content: t("A small task can receive a lot of thought when it involves uncertainty, a decision, another person’s response or something you care about.") },
      { id: "m3a-p46", type: 'paragraph', content: t("The anticipation may last much longer than the task itself.") },
      { id: "m3a-h47", type: 'heading', level: 3, content: t("Example") },
      { id: "m3a-p48", type: 'paragraph', content: t("Thinking about making the call:") },
      { id: "m3a-p49", type: 'paragraph', content: t("Two hours.") },
      { id: "m3a-p50", type: 'paragraph', content: t("Making the call:") },
      { id: "m3a-p51", type: 'paragraph', content: t("Four minutes.") },
      { id: "m3a-h52", type: 'heading', level: 2, content: t("Why Do I Remember Everything When I Finally Sit Down?") },
      { id: "m3a-h53", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p54", type: 'paragraph', content: t("When activity slows down, other reminders and unfinished thoughts may simply become easier to notice.") },
      { id: "m3a-p55", type: 'paragraph', content: t("The quiet moment may not have created those thoughts—it may just be when your attention finally has room to notice them.") },
      { id: "m3a-h56", type: 'heading', level: 3, content: t("Week 3 Connection") },
      { id: "m3a-p57", type: 'paragraph', content: t("Directly supports R006.") },
      { id: "m3a-h58", type: 'heading', level: 2, content: t("Why Do I Walk Into a Room and Forget What I Needed?") },
      { id: "m3a-h59", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p60", type: 'paragraph', content: t("Sometimes attention shifts between one action and the next, and the original intention briefly drops out of focus.") },
      { id: "m3a-p61", type: 'paragraph', content: t("This can happen during ordinary daily activity and does not automatically mean there is a memory problem.") },
      { id: "m3a-h62", type: 'heading', level: 2, content: t("Why Do I Open My Phone and Forget Why I Opened It?") },
      { id: "m3a-h63", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p64", type: 'paragraph', content: t("A phone contains many competing cues, notifications and possible actions, so attention can move away from the original reason you picked it up.") },
      { id: "m3a-p65", type: 'paragraph', content: t("It can be a simple everyday attention shift.") },
      { id: "m3a-h66", type: 'heading', level: 2, content: t("Why Do I Think I Replied to a Message When I Didn’t?") },
      { id: "m3a-h67", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p68", type: 'paragraph', content: t("Sometimes you mentally compose the response so clearly that the intention to reply can feel almost like the action already happened.") },
      { id: "m3a-p69", type: 'paragraph', content: t("Later, you may realize the message was never actually sent.") },
      { id: "m3a-h70", type: 'heading', level: 3, content: t("Week 3 Connection") },
      { id: "m3a-p71", type: 'paragraph', content: t("Direct support for R002.") },
      { id: "m3a-h72", type: 'heading', level: 2, content: t("Why Do Small Decisions Stay on My Mind?") },
      { id: "m3a-h73", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p74", type: 'paragraph', content: t("A small decision can stay mentally active when the choice is still open or when the outcome matters to you.") },
      { id: "m3a-p75", type: 'paragraph', content: t("The decision may not take long to make, but uncertainty around it can keep bringing it back to attention.") },
      { id: "m3a-h76", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About Something Someone Said?") },
      { id: "m3a-h77", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p78", type: 'paragraph', content: t("A comment can stay in your thoughts when it feels meaningful, surprising, unclear or connected to something you care about.") },
      { id: "m3a-p79", type: 'paragraph', content: t("Sometimes the words are brief, but the meaning you attach to them continues to unfold afterward.") },
      { id: "m3a-h80", type: 'heading', level: 2, content: t("Why Does an Appointment Stay on My Mind All Day?") },
      { id: "m3a-h81", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p82", type: 'paragraph', content: t("An upcoming appointment can stay in your attention because it is a scheduled moment you are still waiting to reach.") },
      { id: "m3a-p83", type: 'paragraph', content: t("You may also be thinking about timing, preparation or what will happen once you get there.") },
      { id: "m3a-h84", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About Good News?") },
      { id: "m3a-h85", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p86", type: 'paragraph', content: t("Positive experiences can stay in your thoughts too.") },
      { id: "m3a-p87", type: 'paragraph', content: t("Excitement, anticipation, pride and the desire to share something meaningful can keep good news active in your attention long after the first moment.") },
      { id: "m3a-p88", type: 'paragraph', content: t("This question is mandatory because it protects SOLACE from becoming exclusively difficult-emotion content.") },
      { id: "m3a-h89", type: 'heading', level: 2, content: t("Can Excitement Make Me Think About Something All Day?") },
      { id: "m3a-h90", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p91", type: 'paragraph', content: t("Yes.") },
      { id: "m3a-p92", type: 'paragraph', content: t("Something you are looking forward to can return to your thoughts throughout the day because it feels meaningful, enjoyable or important.") },
      { id: "m3a-p93", type: 'paragraph', content: t("Anticipation can be positive as well as uncertain.") },
      { id: "m3a-h94", type: 'heading', level: 2, content: t("Why Do I Keep Thinking About Something I’m Proud Of?") },
      { id: "m3a-h95", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p96", type: 'paragraph', content: t("A meaningful achievement can stay with you because it represents effort, progress or something you care about.") },
      { id: "m3a-p97", type: 'paragraph', content: t("Not every recurring thought needs to be reduced or solved; some experiences are simply worth noticing and holding onto.") },
      { id: "m3a-h98", type: 'heading', level: 2, content: t("Is Thinking About Something Repeatedly Always a Problem?") },
      { id: "m3a-h99", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p100", type: 'paragraph', content: t("No.") },
      { id: "m3a-p101", type: 'paragraph', content: t("People can return to thoughts for many ordinary reasons, including unfinished actions, uncertainty, excitement, reflection, anticipation or personal importance.") },
      { id: "m3a-p102", type: 'paragraph', content: t("Context matters more than the fact that a thought returned more than once.") },
      { id: "m3a-h103", type: 'heading', level: 2, content: t("Is Anticipation the Same as Overthinking?") },
      { id: "m3a-h104", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p105", type: 'paragraph', content: t("Not necessarily.") },
      { id: "m3a-p106", type: 'paragraph', content: t("Anticipation means thinking ahead to something that has not happened yet, while “overthinking” is a broad everyday term people often use when a thought feels repetitive or receives more attention than expected.") },
      { id: "m3a-p107", type: 'paragraph', content: t("The two can overlap, but they are not automatically the same thing.") },
      { id: "m3a-h108", type: 'heading', level: 2, content: t("How Can I Tell What Is Taking Up My Attention?") },
      { id: "m3a-h109", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p110", type: 'paragraph', content: t("Start by noticing what keeps returning to mind during the day.") },
      { id: "m3a-p111", type: 'paragraph', content: t("Then ask whether it feels unfinished, uncertain, important, exciting or connected to something you are waiting for.") },
      { id: "m3a-p112", type: 'paragraph', content: t("You do not need to judge the thought before understanding why it may be returning.") },
      { id: "m3a-h113", type: 'heading', level: 2, content: t("What Can I Ask Myself When I Keep Thinking About Something?") },
      { id: "m3a-h114", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p115", type: 'paragraph', content: t("Try simple questions such as:") },
      { id: "m3a-list116", type: 'list', style: 'bullet', items: [t("Is something unfinished?"), t("Am I waiting for an answer?"), t("Is this important to me?"), t("Am I excited about what happens next?"), t("Did the anticipation last longer than the actual event?"), t("Does this need action, reflection or simply acknowledgment?")] },
      { id: "m3a-h117", type: 'heading', level: 2, content: t("How Can Reflection Help With Everyday Overthinking?") },
      { id: "m3a-h118", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p119", type: 'paragraph', content: t("Reflection can help you identify what your attention keeps returning to and why it may matter.") },
      { id: "m3a-p120", type: 'paragraph', content: t("The goal does not have to be stopping the thought; sometimes understanding what is keeping it active is useful on its own.") },
      { id: "m3a-h121", type: 'heading', level: 2, content: t("Should I Try to Stop Every Repetitive Thought?") },
      { id: "m3a-h122", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p123", type: 'paragraph', content: t("Not every recurring thought needs to be treated as a problem.") },
      { id: "m3a-p124", type: 'paragraph', content: t("Some thoughts may point to unfinished actions, meaningful experiences, excitement or something you simply want to remember.") },
      { id: "m3a-p125", type: 'paragraph', content: t("A useful first step is noticing what the thought represents.") },
      { id: "m3a-h126", type: 'heading', level: 2, content: t("Why Can Small Moments Feel Bigger Than They Look?") },
      { id: "m3a-h127", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p128", type: 'paragraph', content: t("The amount of time a moment takes does not always match how meaningful or uncertain it feels.") },
      { id: "m3a-p129", type: 'paragraph', content: t("A short conversation, one email or a small decision can represent something much larger, such as approval, connection, progress, responsibility or good news.") },
      { id: "m3a-h130", type: 'heading', level: 2, content: t("Why Does My Mind Feel Busy Even When I’m Not Doing Much?") },
      { id: "m3a-h131", type: 'heading', level: 3, content: t("Direct Answer") },
      { id: "m3a-p132", type: 'paragraph', content: t("A quiet moment can still contain unfinished reminders, upcoming plans, decisions, messages and other thoughts that remain mentally active.") },
      { id: "m3a-p133", type: 'paragraph', content: t("The amount happening externally does not always match how many things are currently occupying attention internally.") },
      { id: "m3a-p134", type: 'paragraph', content: t("Quick Answer") },
      { id: "m3a-p135", type: 'paragraph', content: t("Small moments can stay in your thoughts because they are:") },
      { id: "m3a-h136", type: 'heading', level: 3, content: t("Unfinished") },
      { id: "m3a-h137", type: 'heading', level: 3, content: t("Uncertain") },
      { id: "m3a-h138", type: 'heading', level: 3, content: t("Important") },
      { id: "m3a-h139", type: 'heading', level: 3, content: t("Anticipated") },
      { id: "m3a-h140", type: 'heading', level: 3, content: t("Connected to another person") },
      { id: "m3a-h141", type: 'heading', level: 3, content: t("Exciting") },
      { id: "m3a-p142", type: 'paragraph', content: t("or simply:") },
      { id: "m3a-h143", type: 'heading', level: 3, content: t("Worth remembering") },
      { id: "m3a-p144", type: 'paragraph', content: t("The event itself may be short while the attention around it lasts much longer.") },
      { id: 'm3a-faq', type: 'faq', heading: 'Frequently Asked Questions', items: [{ id: "m3a-faq-1", question: "Why Do I Keep Thinking About Small Things?", answer: t("Small things can stay in your thoughts when they feel unfinished, uncertain, personally important or connected to something that has not happened yet.") }, { id: "m3a-faq-2", question: "Why Do I Overthink Conversations After They Happen?", answer: t("A conversation may stay in your thoughts when you are still considering what was said, how you came across or what the other person meant.") }, { id: "m3a-faq-3", question: "Why Do I Keep Thinking About an Email After I Send It?", answer: t("Sending the email finishes the action, but it may not finish the situation.") }, { id: "m3a-faq-4", question: "Why Do I Remember Everything When I Finally Sit Down?", answer: t("When activity slows down, other reminders and unfinished thoughts may simply become easier to notice.") }, { id: "m3a-faq-5", question: "Why Does Waiting for a Reply Take So Much Attention?", answer: t("Waiting leaves part of the situation unresolved.") }, { id: "m3a-faq-6", question: "Is Anticipation the Same as Overthinking?", answer: t("Not necessarily.") }] },
      { id: 'm3a-cta', type: 'cta', label: 'Explore more everyday reflection resources from SOLACE.', target: { kind: 'route', value: 'resource_library' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'M2-W3-B001', anchorText: null, relation: 'related_content' },
    { targetKind: 'content', targetRef: 'M2-W3-G001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'resource_library', anchorText: 'Explore more everyday reflection resources from SOLACE.', relation: 'resource_library' },
  ],

  authoredOutsideWorkbook: ['cta block (anchor and destination from the workbook PART 44 optional CTA)'],
  missingFields: ['safety_notice (workbook supplies no reader-facing safety copy)', 'workbook references left UNLINKED (no public route): Journal, Mood, Progress (/app/* authenticated), SOLACE Learning Hub (no registered route)', 'seo_title (no schema field distinct from title)'],
};

/** The three Month 2 Week 3 assets, in workbook order. */
export const M2W3_ASSETS: M2W3Asset[] = [M2_W3_B001, M2_W3_G001, M2_W3_A001];

/**
 * Content-to-content edges the workbook states explicitly.
 *
 * B001 PART 36 names links to G001 and A001 with anchors; G001 PART 40 names "To B001" and
 * "To A001"; A001 PART 40 names the same pair back. No edge is inferred from shared-week
 * membership alone.
 */
export const EXPECTED_CONTENT_EDGES: Array<[string, string]> = [
  ['M2-W3-B001', 'M2-W3-G001'],
  ['M2-W3-B001', 'M2-W3-A001'],
  ['M2-W3-G001', 'M2-W3-B001'],
  ['M2-W3-G001', 'M2-W3-A001'],
  ['M2-W3-A001', 'M2-W3-B001'],
  ['M2-W3-A001', 'M2-W3-G001'],
];
