/**
 * Week 2 workbook -> Content Hub mapping.
 *
 * SOURCE: `SOLACE  Week 2nd Operational Workbook.docx`, assets W2-B001, W2-G001, W2-A001.
 *
 * ============================================================================
 * EVERY STRING OF PROSE BELOW IS THE WORKBOOK'S OWN WORDING.
 * ============================================================================
 *
 * The body text was transcribed mechanically from the .docx by
 * `scripts/content-hub/w2-generate.py`, so no sentence has been rewritten, shortened, expanded or
 * restyled, and no statistic, clinical claim or source was added. Regenerating from the same
 * workbook reproduces this file byte for byte.
 *
 * DEDUPLICATION (the workbook's one known defect):
 *   W2-B001 contains its opening section TWICE. Paragraphs 147-276 of the document reappear
 *   verbatim as 277-406 — 130 paragraphs, from the H1 "Why Do We Keep Things To Ourselves?"
 *   through "...And maybe they deserve conversations too." The FIRST copy is imported and the
 *   second is dropped. The article then continues from "The Cost of Carrying Everything Alone".
 *   No other duplication exists anywhere in the workbook: an 8-paragraph sliding-window scan over
 *   all 1,694 paragraphs found exactly this one repeated region.
 *
 * AUTHORED OUTSIDE WORKBOOK (each one is recorded on its asset):
 *   1. W2-A001 `title` — the workbook gives the AEO page no H1. Derived from its own SEO Title by
 *      dropping the " | SOLACE" brand suffix.
 *   2. One `cta` block per asset, built from the workbook's Internal Linking Strategy: the target
 *      is the destination it names (Talk It Out) and the label is the anchor text it specifies.
 *
 * DELIBERATELY ABSENT:
 *   - A `safety_notice` block on all three assets. The Week 2 workbook contains no crisis,
 *     disclaimer or professional-support wording of any kind, and inventing clinical language is
 *     not something an importer should do. All three therefore carry a publish blocker until an
 *     editor adds one.
 *
 * Block ids are stable and human-readable, so a re-run updates the same blocks rather than
 * churning revisions.
 */

import type { Week1Asset, Week1LinkSpec } from '../week1/week1-content';
import type { ContentBody, InlineContent } from '@meetezri/shared';

/** A span of plain text. The workbook contains no inline formatting. */
const t = (text: string): InlineContent => [{ text }];

/**
 * Week 2 reuses the Week 1 asset and link contracts EXACTLY — same fields, same link spec, same
 * importer helpers. Aliasing rather than redeclaring is deliberate: if the two ever drift, this
 * file stops compiling instead of quietly importing against a stale shape.
 */
export type Week2LinkSpec = Week1LinkSpec;
export type Week2Asset = Week1Asset;

// ─────────────────────────────────────────────────────────────────────────────
// W2-B001
// ─────────────────────────────────────────────────────────────────────────────

const W2_B001: Week2Asset = {
  editorialRef: "W2-B001",
  contentType: 'seo_blog',
  publicLabel: 'Article',
  title: "Why Do We Keep Things To Ourselves?",
  slug: "why-do-we-keep-things-to-ourselves",
  metaDescription: "Discover why people keep thoughts, achievements and everyday moments to themselves, and how meaningful conversations can strengthen connection.",
  week: 2,
  pillar: 'Someone To Talk To',
  tags: ['someone-to-talk-to', 'week-2'],

  typeFields: {
    keywords: {
      primary: 'someone to talk to',
      secondary: [
        'why do people keep things to themselves',
        'everyday conversations',
        'meaningful conversations',
        'emotional wellbeing',
        'talking through your thoughts',
        'feeling understood',
        'human connection',
        "why we don't open up",
        'overthinking conversations',
      ],
    },
    word_count_target: '2,500-3,000 words',
    funnel_stage: 'Awareness',
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'Establish SOLACE as an authority on everyday conversations and emotional wellbeing while building long-term search visibility.',
    strategy: 'Begin with something almost everyone has experienced rather than with stress, anxiety or depression, so the article is relatable before it introduces deeper ideas.',
    search_intent: 'Informational',
    user_state: 'Reflective, curious, often independent, sometimes isolated, not necessarily in crisis',
    goal: 'Organic Traffic',
    business_goal: 'Establish SOLACE as an authority on everyday conversations and emotional wellbeing while building long-term search visibility.',
    primary_kpi: 'Organic Traffic',
    secondary_kpi: 'Time on Page',
  },

  body: {
    version: 1,
    blocks: [
      { id: "b2-h1", type: 'heading', level: 2, content: t("The Everyday Habit We Rarely Notice") },
      { id: "b2-p2", type: 'paragraph', content: t("Have you ever picked up your phone because you wanted to tell someone something...") },
      { id: "b2-p3", type: 'paragraph', content: t("...then quietly put it back down?") },
      { id: "b2-p4", type: 'paragraph', content: t("Maybe it was good news.") },
      { id: "b2-p5", type: 'paragraph', content: t("Maybe something made you laugh.") },
      { id: "b2-p6", type: 'paragraph', content: t("Maybe you watched a beautiful sunset on the drive home.") },
      { id: "b2-p7", type: 'paragraph', content: t("Maybe you finally finished something you'd been working towards for months.") },
      { id: "b2-p8", type: 'paragraph', content: t("Or maybe it was simply a random thought that felt worth sharing for a brief moment.") },
      { id: "b2-p9", type: 'paragraph', content: t("Then, almost without thinking, you told yourself:") },
      { id: "b2-p10", type: 'paragraph', content: t("\"It's probably not important.\"") },
      { id: "b2-p11", type: 'paragraph', content: t("\"I'll mention it later.\"") },
      { id: "b2-p12", type: 'paragraph', content: t("\"They're probably busy.\"") },
      { id: "b2-p13", type: 'paragraph', content: t("\"It doesn't really matter.\"") },
      { id: "b2-p14", type: 'paragraph', content: t("Most of us have experienced moments like these.") },
      { id: "b2-p15", type: 'paragraph', content: t("They're so ordinary that we rarely stop to think about them.") },
      { id: "b2-p16", type: 'paragraph', content: t("But together, these tiny decisions reveal something much bigger about how many of us experience conversations.") },
      { id: "b2-p17", type: 'paragraph', content: t("We often assume that conversations are for significant events.") },
      { id: "b2-p18", type: 'paragraph', content: t("When something goes wrong.") },
      { id: "b2-p19", type: 'paragraph', content: t("When we need advice.") },
      { id: "b2-p20", type: 'paragraph', content: t("When we're overwhelmed.") },
      { id: "b2-p21", type: 'paragraph', content: t("When we're celebrating something huge.") },
      { id: "b2-p22", type: 'paragraph', content: t("Everything else quietly stays inside.") },
      { id: "b2-p23", type: 'paragraph', content: t("Over time, that becomes normal.") },
      { id: "b2-p24", type: 'paragraph', content: t("Not because we choose silence.") },
      { id: "b2-p25", type: 'paragraph', content: t("Because we've learned to treat our everyday thoughts as if they aren't important enough to share.") },
      { id: "b2-p26", type: 'paragraph', content: t("And perhaps that's one of the most overlooked parts of being human.") },
      { id: "b2-h27", type: 'heading', level: 2, content: t("The Quiet Habit We Don't Realise We're Building") },
      { id: "b2-p28", type: 'paragraph', content: t("If someone asked why you didn't send that message, you probably wouldn't have a dramatic answer.") },
      { id: "b2-p29", type: 'paragraph', content: t("You might simply say:") },
      { id: "b2-p30", type: 'paragraph', content: t("\"I don't know.\"") },
      { id: "b2-p31", type: 'paragraph', content: t("That's because this habit isn't usually intentional.") },
      { id: "b2-p32", type: 'paragraph', content: t("It develops slowly.") },
      { id: "b2-p33", type: 'paragraph', content: t("One ordinary moment at a time.") },
      { id: "b2-p34", type: 'paragraph', content: t("You think about texting a friend.") },
      { id: "b2-p35", type: 'paragraph', content: t("You decide you'll do it later.") },
      { id: "b2-p36", type: 'paragraph', content: t("Later never comes.") },
      { id: "b2-p37", type: 'paragraph', content: t("You remember something funny.") },
      { id: "b2-p38", type: 'paragraph', content: t("By the time you see someone again, you've forgotten.") },
      { id: "b2-p39", type: 'paragraph', content: t("You have an exciting idea.") },
      { id: "b2-p40", type: 'paragraph', content: t("You assume no one else would find it interesting.") },
      { id: "b2-p41", type: 'paragraph', content: t("You achieve a personal goal.") },
      { id: "b2-p42", type: 'paragraph', content: t("You smile to yourself instead.") },
      { id: "b2-p43", type: 'paragraph', content: t("None of these moments feels important on its own.") },
      { id: "b2-p44", type: 'paragraph', content: t("But together they create a pattern.") },
      { id: "b2-p45", type: 'paragraph', content: t("A pattern of editing ourselves before anyone else ever has the chance to hear us.") },
      { id: "b2-p46", type: 'paragraph', content: t("What's interesting is that this habit isn't limited to people going through difficult times.") },
      { id: "b2-p47", type: 'paragraph', content: t("It happens to students.") },
      { id: "b2-p48", type: 'paragraph', content: t("Parents.") },
      { id: "b2-p49", type: 'paragraph', content: t("Professionals.") },
      { id: "b2-p50", type: 'paragraph', content: t("Business owners.") },
      { id: "b2-p51", type: 'paragraph', content: t("Retirees.") },
      { id: "b2-p52", type: 'paragraph', content: t("People surrounded by others.") },
      { id: "b2-p53", type: 'paragraph', content: t("People living alone.") },
      { id: "b2-p54", type: 'paragraph', content: t("People with large social circles.") },
      { id: "b2-p55", type: 'paragraph', content: t("People with very small ones.") },
      { id: "b2-p56", type: 'paragraph', content: t("It isn't necessarily about loneliness.") },
      { id: "b2-p57", type: 'paragraph', content: t("It's about deciding, often without realising it, that a thought isn't worth turning into a conversation.") },
      { id: "b2-h58", type: 'heading', level: 2, content: t("We Don't Only Keep Pain Inside") },
      { id: "b2-p59", type: 'paragraph', content: t("When people think about emotional wellbeing, the conversation usually starts with struggle.") },
      { id: "b2-p60", type: 'paragraph', content: t("Stress.") },
      { id: "b2-p61", type: 'paragraph', content: t("Burnout.") },
      { id: "b2-p62", type: 'paragraph', content: t("Anxiety.") },
      { id: "b2-p63", type: 'paragraph', content: t("Loss.") },
      { id: "b2-p64", type: 'paragraph', content: t("Those experiences deserve attention.") },
      { id: "b2-p65", type: 'paragraph', content: t("But they aren't the whole story.") },
      { id: "b2-p66", type: 'paragraph', content: t("Think about the past week.") },
      { id: "b2-p67", type: 'paragraph', content: t("What have you carried that wasn't painful?") },
      { id: "b2-p68", type: 'paragraph', content: t("Maybe it was excitement about an upcoming trip.") },
      { id: "b2-p69", type: 'paragraph', content: t("Pride after completing a difficult project.") },
      { id: "b2-p70", type: 'paragraph', content: t("Gratitude for a quiet evening.") },
      { id: "b2-p71", type: 'paragraph', content: t("Curiosity about something you read.") },
      { id: "b2-p72", type: 'paragraph', content: t("A memory that unexpectedly made you smile.") },
      { id: "b2-p73", type: 'paragraph', content: t("An idea that arrived during your morning walk.") },
      { id: "b2-p74", type: 'paragraph', content: t("A conversation you imagined having but never did.") },
      { id: "b2-p75", type: 'paragraph', content: t("These moments rarely make headlines.") },
      { id: "b2-p76", type: 'paragraph', content: t("Yet they're woven into everyday life.") },
      { id: "b2-p77", type: 'paragraph', content: t("The truth is, people don't only carry difficult emotions.") },
      { id: "b2-p78", type: 'paragraph', content: t("They carry experiences.") },
      { id: "b2-p79", type: 'paragraph', content: t("Thoughts.") },
      { id: "b2-p80", type: 'paragraph', content: t("Questions.") },
      { id: "b2-p81", type: 'paragraph', content: t("Dreams.") },
      { id: "b2-p82", type: 'paragraph', content: t("Moments.") },
      { id: "b2-p83", type: 'paragraph', content: t("And often, those moments remain entirely private.") },
      { id: "b2-p84", type: 'paragraph', content: t("Not because they have to.") },
      { id: "b2-p85", type: 'paragraph', content: t("Because we've become accustomed to carrying them alone.") },
      { id: "b2-h86", type: 'heading', level: 2, content: t("Why Our Own Thoughts Often Feel \"Too Small\"") },
      { id: "b2-p87", type: 'paragraph', content: t("One of the most common phrases people say to themselves is surprisingly simple:") },
      { id: "b2-p88", type: 'paragraph', content: t("\"It's probably not important.\"") },
      { id: "b2-p89", type: 'paragraph', content: t("It's easy to dismiss our own experiences because we're living inside them every day.") },
      { id: "b2-p90", type: 'paragraph', content: t("What feels ordinary to us may actually be meaningful.") },
      { id: "b2-p91", type: 'paragraph', content: t("Imagine telling a close friend:") },
      { id: "b2-p92", type: 'paragraph', content: t("\"I finally finished something I've been working on for months.\"") },
      { id: "b2-p93", type: 'paragraph', content: t("Or:") },
      { id: "b2-p94", type: 'paragraph', content: t("\"I saw something today that reminded me of you.\"") },
      { id: "b2-p95", type: 'paragraph', content: t("Neither conversation would change the world.") },
      { id: "b2-p96", type: 'paragraph', content: t("But both could strengthen a relationship.") },
      { id: "b2-p97", type: 'paragraph', content: t("Meaning isn't created only through extraordinary events.") },
      { id: "b2-p98", type: 'paragraph', content: t("It's created through consistent human connection.") },
      { id: "b2-p99", type: 'paragraph', content: t("Many of the relationships we value most weren't built through one life-changing conversation.") },
      { id: "b2-p100", type: 'paragraph', content: t("They were built through hundreds of ordinary ones.") },
      { id: "b2-p101", type: 'paragraph', content: t("The funny observation.") },
      { id: "b2-p102", type: 'paragraph', content: t("The unexpected compliment.") },
      { id: "b2-p103", type: 'paragraph', content: t("The shared memory.") },
      { id: "b2-p104", type: 'paragraph', content: t("The small celebration.") },
      { id: "b2-p105", type: 'paragraph', content: t("The simple question.") },
      { id: "b2-p106", type: 'paragraph', content: t("The \"I thought of you today.\"") },
      { id: "b2-p107", type: 'paragraph', content: t("These conversations don't always feel important in the moment.") },
      { id: "b2-p108", type: 'paragraph', content: t("Looking back, they're often the ones we remember most.") },
      { id: "b2-h109", type: 'heading', level: 2, content: t("What This Means For Everyday Life") },
      { id: "b2-p110", type: 'paragraph', content: t("Perhaps we've unintentionally created impossible standards for what deserves to be shared.") },
      { id: "b2-p111", type: 'paragraph', content: t("We wait until something becomes big enough.") },
      { id: "b2-p112", type: 'paragraph', content: t("Serious enough.") },
      { id: "b2-p113", type: 'paragraph', content: t("Important enough.") },
      { id: "b2-p114", type: 'paragraph', content: t("Urgent enough.") },
      { id: "b2-p115", type: 'paragraph', content: t("Before we believe it's worth saying out loud.") },
      { id: "b2-p116", type: 'paragraph', content: t("But life doesn't only happen during major events.") },
      { id: "b2-p117", type: 'paragraph', content: t("Life happens while making coffee.") },
      { id: "b2-p118", type: 'paragraph', content: t("Driving home.") },
      { id: "b2-p119", type: 'paragraph', content: t("Walking the dog.") },
      { id: "b2-p120", type: 'paragraph', content: t("Reading a book.") },
      { id: "b2-p121", type: 'paragraph', content: t("Watching the rain.") },
      { id: "b2-p122", type: 'paragraph', content: t("Laughing at something unexpected.") },
      { id: "b2-p123", type: 'paragraph', content: t("Those moments don't interrupt life.") },
      { id: "b2-p124", type: 'paragraph', content: t("They are life.") },
      { id: "b2-p125", type: 'paragraph', content: t("And maybe they deserve conversations too.") },
      { id: "b2-h126", type: 'heading', level: 2, content: t("The Cost of Carrying Everything Alone") },
      { id: "b2-p127", type: 'paragraph', content: t("There is something interesting about the way many of us carry our thoughts.") },
      { id: "b2-p128", type: 'paragraph', content: t("We rarely notice the weight all at once.") },
      { id: "b2-p129", type: 'paragraph', content: t("Instead, it builds quietly.") },
      { id: "b2-p130", type: 'paragraph', content: t("One unfinished conversation.") },
      { id: "b2-p131", type: 'paragraph', content: t("One thought we never shared.") },
      { id: "b2-p132", type: 'paragraph', content: t("One question we decided wasn't worth asking.") },
      { id: "b2-p133", type: 'paragraph', content: t("One achievement we celebrated alone.") },
      { id: "b2-p134", type: 'paragraph', content: t("None of those moments feels significant by itself.") },
      { id: "b2-p135", type: 'paragraph', content: t("But over weeks, months and years, they begin to create distance.") },
      { id: "b2-p136", type: 'paragraph', content: t("Not necessarily from other people.") },
      { id: "b2-p137", type: 'paragraph', content: t("Often, from ourselves.") },
      { id: "b2-p138", type: 'paragraph', content: t("When we constantly tell ourselves that our thoughts are too small to matter, we slowly stop giving them our attention.") },
      { id: "b2-p139", type: 'paragraph', content: t("We stop becoming curious about our own experiences.") },
      { id: "b2-p140", type: 'paragraph', content: t("We stop exploring ideas out loud.") },
      { id: "b2-p141", type: 'paragraph', content: t("We stop celebrating progress.") },
      { id: "b2-p142", type: 'paragraph', content: t("We stop sharing moments that once would have naturally become conversations.") },
      { id: "b2-p143", type: 'paragraph', content: t("Eventually, silence becomes familiar.") },
      { id: "b2-p144", type: 'paragraph', content: t("Not because silence is wrong.") },
      { id: "b2-p145", type: 'paragraph', content: t("Because it becomes our default response.") },
      { id: "b2-h146", type: 'heading', level: 2, content: t("Silence Isn't Always Peace") },
      { id: "b2-p147", type: 'paragraph', content: t("Being quiet and choosing solitude can be healthy.") },
      { id: "b2-p148", type: 'paragraph', content: t("Many people genuinely enjoy time alone.") },
      { id: "b2-p149", type: 'paragraph', content: t("Reflection.") },
      { id: "b2-p150", type: 'paragraph', content: t("Reading.") },
      { id: "b2-p151", type: 'paragraph', content: t("Walking.") },
      { id: "b2-p152", type: 'paragraph', content: t("Creating.") },
      { id: "b2-p153", type: 'paragraph', content: t("Thinking.") },
      { id: "b2-p154", type: 'paragraph', content: t("Those moments are valuable.") },
      { id: "b2-p155", type: 'paragraph', content: t("Silence becomes different when it isn't a choice anymore.") },
      { id: "b2-p156", type: 'paragraph', content: t("When we automatically assume:") },
      { id: "b2-p157", type: 'paragraph', content: t("\"No one would understand.\"") },
      { id: "b2-p158", type: 'paragraph', content: t("\"I'll keep it to myself.\"") },
      { id: "b2-p159", type: 'paragraph', content: t("\"It isn't worth mentioning.\"") },
      { id: "b2-p160", type: 'paragraph', content: t("Over time, silence can become a habit rather than a preference.") },
      { id: "b2-p161", type: 'paragraph', content: t("That's an important difference.") },
      { id: "b2-p162", type: 'paragraph', content: t("The goal isn't to fill every quiet moment with conversation.") },
      { id: "b2-p163", type: 'paragraph', content: t("The goal is to recognise when we're staying silent simply because we've forgotten our experiences deserve space.") },
      { id: "b2-h164", type: 'heading', level: 2, content: t("Why Being Understood Matters") },
      { id: "b2-p165", type: 'paragraph', content: t("One of the most meaningful parts of any conversation isn't receiving advice.") },
      { id: "b2-p166", type: 'paragraph', content: t("It's feeling understood.") },
      { id: "b2-p167", type: 'paragraph', content: t("Think about the conversations you remember most.") },
      { id: "b2-p168", type: 'paragraph', content: t("They probably weren't the ones where someone gave you the perfect answer.") },
      { id: "b2-p169", type: 'paragraph', content: t("More often, they were the moments where someone simply listened.") },
      { id: "b2-p170", type: 'paragraph', content: t("Where you didn't have to explain every detail.") },
      { id: "b2-p171", type: 'paragraph', content: t("Where you didn't feel judged.") },
      { id: "b2-p172", type: 'paragraph', content: t("Where you could finish a sentence without worrying whether it sounded important enough.") },
      { id: "b2-p173", type: 'paragraph', content: t("Understanding creates something advice often cannot.") },
      { id: "b2-p174", type: 'paragraph', content: t("It creates safety.") },
      { id: "b2-p175", type: 'paragraph', content: t("And when people feel safe, they naturally become more open.") },
      { id: "b2-p176", type: 'paragraph', content: t("Not only about difficult moments.") },
      { id: "b2-p177", type: 'paragraph', content: t("About everyday life.") },
      { id: "b2-h178", type: 'heading', level: 2, content: t("Conversations Shape More Than We Realise") },
      { id: "b2-p179", type: 'paragraph', content: t("Conversations don't simply communicate information.") },
      { id: "b2-p180", type: 'paragraph', content: t("They shape relationships.") },
      { id: "b2-p181", type: 'paragraph', content: t("Identity.") },
      { id: "b2-p182", type: 'paragraph', content: t("Memory.") },
      { id: "b2-p183", type: 'paragraph', content: t("Perspective.") },
      { id: "b2-p184", type: 'paragraph', content: t("Think about how many memories begin with a conversation.") },
      { id: "b2-p185", type: 'paragraph', content: t("\"Do you remember when...\"") },
      { id: "b2-p186", type: 'paragraph', content: t("\"I was thinking about something you said...\"") },
      { id: "b2-p187", type: 'paragraph', content: t("\"That reminds me of...\"") },
      { id: "b2-p188", type: 'paragraph', content: t("Words become part of how we remember our lives.") },
      { id: "b2-p189", type: 'paragraph', content: t("Some conversations change our direction completely.") },
      { id: "b2-p190", type: 'paragraph', content: t("Others simply become small moments we carry with us for years.") },
      { id: "b2-p191", type: 'paragraph', content: t("Neither is more valuable.") },
      { id: "b2-p192", type: 'paragraph', content: t("Both contribute to who we become.") },
      { id: "b2-p193", type: 'paragraph', content: t("That's why conversations matter even when nothing dramatic is happening.") },
      { id: "b2-p194", type: 'paragraph', content: t("Because they quietly shape the way we experience everyday life.") },
      { id: "b2-h195", type: 'heading', level: 2, content: t("We Were Never Meant To Carry Every Thought Alone") },
      { id: "b2-p196", type: 'paragraph', content: t("Human beings have always shared stories.") },
      { id: "b2-p197", type: 'paragraph', content: t("Long before phones.") },
      { id: "b2-p198", type: 'paragraph', content: t("Before messaging apps.") },
      { id: "b2-p199", type: 'paragraph', content: t("Before social media.") },
      { id: "b2-p200", type: 'paragraph', content: t("People gathered around dinner tables.") },
      { id: "b2-p201", type: 'paragraph', content: t("Walked together.") },
      { id: "b2-p202", type: 'paragraph', content: t("Sat outside.") },
      { id: "b2-p203", type: 'paragraph', content: t("Shared observations.") },
      { id: "b2-p204", type: 'paragraph', content: t("Asked questions.") },
      { id: "b2-p205", type: 'paragraph', content: t("Celebrated harvests.") },
      { id: "b2-p206", type: 'paragraph', content: t("Remembered loved ones.") },
      { id: "b2-p207", type: 'paragraph', content: t("Wondered about tomorrow.") },
      { id: "b2-p208", type: 'paragraph', content: t("Conversation wasn't an emergency response.") },
      { id: "b2-p209", type: 'paragraph', content: t("It was part of daily life.") },
      { id: "b2-p210", type: 'paragraph', content: t("Somewhere along the way, many of us started treating conversation differently.") },
      { id: "b2-p211", type: 'paragraph', content: t("We began asking ourselves whether something was \"important enough\" before saying it out loud.") },
      { id: "b2-p212", type: 'paragraph', content: t("Maybe that's the wrong question.") },
      { id: "b2-p213", type: 'paragraph', content: t("Perhaps the better question is:") },
      { id: "b2-q214", type: 'quote', content: t("\"Why did this moment matter to me?\"") },
      { id: "b2-p215", type: 'paragraph', content: t("Sometimes the answer is enough.") },
      { id: "b2-h216", type: 'heading', level: 2, content: t("What Meaningful Conversations Actually Give Us") },
      { id: "b2-p217", type: 'paragraph', content: t("Meaningful conversations don't always solve problems.") },
      { id: "b2-p218", type: 'paragraph', content: t("Often, they do something quieter.") },
      { id: "b2-p219", type: 'paragraph', content: t("They help us organise our thoughts.") },
      { id: "b2-p220", type: 'paragraph', content: t("Notice patterns.") },
      { id: "b2-p221", type: 'paragraph', content: t("Celebrate progress.") },
      { id: "b2-p222", type: 'paragraph', content: t("Feel recognised.") },
      { id: "b2-p223", type: 'paragraph', content: t("Discover perspectives we hadn't considered.") },
      { id: "b2-p224", type: 'paragraph', content: t("Sometimes they simply remind us that another human being has witnessed a small part of our day.") },
      { id: "b2-p225", type: 'paragraph', content: t("That matters more than we often realise.") },
      { id: "b2-p226", type: 'paragraph', content: t("Not because every conversation needs to change our lives.") },
      { id: "b2-p227", type: 'paragraph', content: t("Because every conversation has the potential to strengthen connection.") },
      { id: "b2-p228", type: 'paragraph', content: t("And connection isn't built in one extraordinary moment.") },
      { id: "b2-p229", type: 'paragraph', content: t("It's built through ordinary moments repeated over time.") },
      { id: "b2-p230", type: 'paragraph', content: t("A laugh shared over coffee.") },
      { id: "b2-p231", type: 'paragraph', content: t("A message that says,") },
      { id: "b2-p232", type: 'paragraph', content: t("\"This reminded me of you.\"") },
      { id: "b2-p233", type: 'paragraph', content: t("A quiet conversation on the drive home.") },
      { id: "b2-p234", type: 'paragraph', content: t("The excitement of telling someone about a new idea.") },
      { id: "b2-p235", type: 'paragraph', content: t("The relief of saying something you've been thinking about all week.") },
      { id: "b2-p236", type: 'paragraph', content: t("Those moments rarely make headlines.") },
      { id: "b2-p237", type: 'paragraph', content: t("But together, they build relationships that last.") },
      { id: "b2-h238", type: 'heading', level: 2, content: t("Conversations Don't Have To Earn Their Place") },
      { id: "b2-p239", type: 'paragraph', content: t("Perhaps one of the kindest things we can do for ourselves is stop asking whether a conversation is \"important enough.\"") },
      { id: "b2-p240", type: 'paragraph', content: t("Instead, we can simply ask:") },
      { id: "b2-p241", type: 'paragraph', content: t("\"Would sharing this help me feel a little more connected?\"") },
      { id: "b2-p242", type: 'paragraph', content: t("Sometimes the answer will be no.") },
      { id: "b2-p243", type: 'paragraph', content: t("Sometimes it will be yes.") },
      { id: "b2-p244", type: 'paragraph', content: t("The point isn't to share everything.") },
      { id: "b2-p245", type: 'paragraph', content: t("The point is to stop believing that only life's biggest moments deserve to be spoken aloud.") },
      { id: "b2-p246", type: 'paragraph', content: t("Because if we only talk when something is wrong, we miss hundreds of opportunities to build connection while life is quietly unfolding.") },
      { id: "b2-h247", type: 'heading', level: 2, content: t("Why Conversations Shouldn't Begin Only During Difficult Moments") },
      { id: "b2-p248", type: 'paragraph', content: t("Imagine if we approached physical health the same way many of us approach conversations.") },
      { id: "b2-p249", type: 'paragraph', content: t("We wouldn't exercise only after becoming unwell.") },
      { id: "b2-p250", type: 'paragraph', content: t("We wouldn't drink water only when we were severely dehydrated.") },
      { id: "b2-p251", type: 'paragraph', content: t("We wouldn't think about sleep only after complete exhaustion.") },
      { id: "b2-p252", type: 'paragraph', content: t("Most healthy habits work because we practice them consistently, not because we wait for a crisis.") },
      { id: "b2-p253", type: 'paragraph', content: t("Perhaps conversations deserve the same perspective.") },
      { id: "b2-p254", type: 'paragraph', content: t("What if talking wasn't something reserved for life's hardest days?") },
      { id: "b2-p255", type: 'paragraph', content: t("What if it became part of everyday wellbeing?") },
      { id: "b2-p256", type: 'paragraph', content: t("Not because something was wrong.") },
      { id: "b2-p257", type: 'paragraph', content: t("Because something mattered.") },
      { id: "b2-p258", type: 'paragraph', content: t("Maybe you had an exciting idea.") },
      { id: "b2-p259", type: 'paragraph', content: t("Maybe you wanted to celebrate a small achievement.") },
      { id: "b2-p260", type: 'paragraph', content: t("Maybe you had a question that stayed with you all afternoon.") },
      { id: "b2-p261", type: 'paragraph', content: t("Maybe you simply wanted another person to witness a small piece of your day.") },
      { id: "b2-p262", type: 'paragraph', content: t("Those moments don't compete with difficult conversations.") },
      { id: "b2-p263", type: 'paragraph', content: t("They prepare us for them.") },
      { id: "b2-p264", type: 'paragraph', content: t("Relationships built through everyday conversations become the relationships we naturally turn to when life becomes difficult.") },
      { id: "b2-p265", type: 'paragraph', content: t("Trust rarely appears overnight.") },
      { id: "b2-p266", type: 'paragraph', content: t("It grows one conversation at a time.") },
      { id: "b2-h267", type: 'heading', level: 2, content: t("A Different Way To Think About Emotional Wellbeing") },
      { id: "b2-p268", type: 'paragraph', content: t("For many years, conversations around emotional wellbeing have focused on helping people respond to difficult experiences.") },
      { id: "b2-p269", type: 'paragraph', content: t("That work is incredibly important.") },
      { id: "b2-p270", type: 'paragraph', content: t("But perhaps emotional wellbeing can be something more.") },
      { id: "b2-p271", type: 'paragraph', content: t("Perhaps it can also be about building habits that help us stay connected before life becomes overwhelming.") },
      { id: "b2-p272", type: 'paragraph', content: t("Sharing gratitude.") },
      { id: "b2-p273", type: 'paragraph', content: t("Talking through ideas.") },
      { id: "b2-p274", type: 'paragraph', content: t("Celebrating progress.") },
      { id: "b2-p275", type: 'paragraph', content: t("Reflecting on experiences.") },
      { id: "b2-p276", type: 'paragraph', content: t("Wondering out loud.") },
      { id: "b2-p277", type: 'paragraph', content: t("Laughing together.") },
      { id: "b2-p278", type: 'paragraph', content: t("Remembering.") },
      { id: "b2-p279", type: 'paragraph', content: t("Dreaming.") },
      { id: "b2-p280", type: 'paragraph', content: t("These aren't replacements for support during difficult times.") },
      { id: "b2-p281", type: 'paragraph', content: t("They're part of creating a healthier relationship with ourselves and the people around us.") },
      { id: "b2-p282", type: 'paragraph', content: t("When conversations become ordinary, asking for one during a difficult moment no longer feels unusual.") },
      { id: "b2-p283", type: 'paragraph', content: t("It feels natural.") },
      { id: "b2-h284", type: 'heading', level: 2, content: t("The Future Of Human Connection") },
      { id: "b2-p285", type: 'paragraph', content: t("Technology has made it easier than ever to communicate.") },
      { id: "b2-p286", type: 'paragraph', content: t("We can send messages across the world in seconds.") },
      { id: "b2-p287", type: 'paragraph', content: t("Share photographs instantly.") },
      { id: "b2-p288", type: 'paragraph', content: t("Join conversations from almost anywhere.") },
      { id: "b2-p289", type: 'paragraph', content: t("Yet many people still describe feeling unheard.") },
      { id: "b2-p290", type: 'paragraph', content: t("Perhaps the challenge isn't communication.") },
      { id: "b2-p291", type: 'paragraph', content: t("Perhaps it's connection.") },
      { id: "b2-p292", type: 'paragraph', content: t("Real connection isn't measured by how many conversations we have.") },
      { id: "b2-p293", type: 'paragraph', content: t("It's shaped by whether we feel safe bringing our genuine thoughts into those conversations.") },
      { id: "b2-p294", type: 'paragraph', content: t("Sometimes those thoughts are profound.") },
      { id: "b2-p295", type: 'paragraph', content: t("Sometimes they're wonderfully ordinary.") },
      { id: "b2-p296", type: 'paragraph', content: t("Both deserve space.") },
      { id: "b2-p297", type: 'paragraph', content: t("As our lives become busier and more digitally connected, creating intentional moments for meaningful conversation may become one of the most valuable wellbeing habits we can develop.") },
      { id: "b2-p298", type: 'paragraph', content: t("Not because we're trying to solve every problem.") },
      { id: "b2-p299", type: 'paragraph', content: t("Because we're trying to stay connected to ourselves and to one another.") },
      { id: "b2-h300", type: 'heading', level: 2, content: t("A Small Reflection Before You Go") },
      { id: "b2-p301", type: 'paragraph', content: t("Before you leave this page, pause for a moment.") },
      { id: "b2-p302", type: 'paragraph', content: t("Think about today.") },
      { id: "b2-p303", type: 'paragraph', content: t("Not your biggest challenge.") },
      { id: "b2-p304", type: 'paragraph', content: t("Not your longest to-do list.") },
      { id: "b2-p305", type: 'paragraph', content: t("Just today.") },
      { id: "b2-p306", type: 'paragraph', content: t("Was there a moment that made you smile?") },
      { id: "b2-p307", type: 'paragraph', content: t("A thought you almost shared?") },
      { id: "b2-p308", type: 'paragraph', content: t("A question that stayed with you?") },
      { id: "b2-p309", type: 'paragraph', content: t("A memory that appeared unexpectedly?") },
      { id: "b2-p310", type: 'paragraph', content: t("A quiet achievement?") },
      { id: "b2-p311", type: 'paragraph', content: t("A simple observation?") },
      { id: "b2-p312", type: 'paragraph', content: t("If there was...") },
      { id: "b2-p313", type: 'paragraph', content: t("That moment mattered.") },
      { id: "b2-p314", type: 'paragraph', content: t("Not because it changed the world.") },
      { id: "b2-p315", type: 'paragraph', content: t("Because it became part of your experience.") },
      { id: "b2-p316", type: 'paragraph', content: t("And experiences become stories.") },
      { id: "b2-p317", type: 'paragraph', content: t("Stories become conversations.") },
      { id: "b2-p318", type: 'paragraph', content: t("Conversations become connection.") },
      { id: "b2-p319", type: 'paragraph', content: t("Sometimes all it takes is giving one ordinary moment the space to exist outside your own mind.") },
      { id: "b2-h320", type: 'heading', level: 2, content: t("Conclusion") },
      { id: "b2-p321", type: 'paragraph', content: t("Most of us don't keep things to ourselves because we want to.") },
      { id: "b2-p322", type: 'paragraph', content: t("We do it because we've quietly learned to measure our thoughts before we ever share them.") },
      { id: "b2-p323", type: 'paragraph', content: t("We decide whether they're important enough.") },
      { id: "b2-p324", type: 'paragraph', content: t("Interesting enough.") },
      { id: "b2-p325", type: 'paragraph', content: t("Serious enough.") },
      { id: "b2-p326", type: 'paragraph', content: t("Worth someone else's time.") },
      { id: "b2-p327", type: 'paragraph', content: t("But perhaps that's the wrong measurement.") },
      { id: "b2-p328", type: 'paragraph', content: t("Maybe conversations don't need to earn their place.") },
      { id: "b2-p329", type: 'paragraph', content: t("Maybe they simply need honesty.") },
      { id: "b2-p330", type: 'paragraph', content: t("Because life isn't only made of extraordinary moments.") },
      { id: "b2-p331", type: 'paragraph', content: t("It's made of ordinary Tuesdays.") },
      { id: "b2-p332", type: 'paragraph', content: t("Morning coffee.") },
      { id: "b2-p333", type: 'paragraph', content: t("Unexpected laughter.") },
      { id: "b2-p334", type: 'paragraph', content: t("Ideas.") },
      { id: "b2-p335", type: 'paragraph', content: t("Questions.") },
      { id: "b2-p336", type: 'paragraph', content: t("Small victories.") },
      { id: "b2-p337", type: 'paragraph', content: t("Quiet gratitude.") },
      { id: "b2-p338", type: 'paragraph', content: t("Beautiful sunsets.") },
      { id: "b2-p339", type: 'paragraph', content: t("And thousands of moments in between.") },
      { id: "b2-p340", type: 'paragraph', content: t("Those moments deserve to be part of our conversations too.") },
      { id: "b2-p341", type: 'paragraph', content: t("Because conversations aren't only about solving problems.") },
      { id: "b2-p342", type: 'paragraph', content: t("They're about sharing life while we're living it.") },
      { id: "b2-h343", type: 'heading', level: 2, content: t("About SOLACE") },
      { id: "b2-p344", type: 'paragraph', content: t("At SOLACE, we believe people don't only carry pain.") },
      { id: "b2-p345", type: 'paragraph', content: t("They carry joy.") },
      { id: "b2-p346", type: 'paragraph', content: t("Hope.") },
      { id: "b2-p347", type: 'paragraph', content: t("Questions.") },
      { id: "b2-p348", type: 'paragraph', content: t("Dreams.") },
      { id: "b2-p349", type: 'paragraph', content: t("Reflection.") },
      { id: "b2-p350", type: 'paragraph', content: t("Curiosity.") },
      { id: "b2-p351", type: 'paragraph', content: t("Memories.") },
      { id: "b2-p352", type: 'paragraph', content: t("Gratitude.") },
      { id: "b2-p353", type: 'paragraph', content: t("Everyday thoughts.") },
      { id: "b2-p354", type: 'paragraph', content: t("Our mission is simple:") },
      { id: "b2-q355", type: 'quote', content: t("To create a space where people can talk through what they're carrying, whether it's something difficult, something exciting, or simply something that matters to them.") },
      { id: "b2-p356", type: 'paragraph', content: t("Because every meaningful conversation deserves space.") },
      { id: "b2-faq", type: 'faq', heading: "Frequently Asked Questions", items: [{ id: "b2-faq-1", question: "Why do people keep things to themselves?", answer: t("Many people keep thoughts, feelings or experiences to themselves because they don't want to burden others, believe their thoughts aren't important enough, assume they won't be understood, or simply become used to handling things internally. These patterns are common and often develop gradually over time.") }, { id: "b2-faq-2", question: "Is it normal to want someone to talk to even when nothing is wrong?", answer: t("Yes. Conversations aren't only valuable during difficult moments. Many people naturally want to share exciting news, everyday experiences, ideas or reflections because doing so helps create connection and a sense of being understood.") }, { id: "b2-faq-3", question: "Why do everyday conversations matter?", answer: t("Everyday conversations strengthen trust, deepen relationships and help people feel connected. Rather than waiting for major life events, regular conversations allow people to share experiences, celebrate small moments and build stronger relationships over time.") }, { id: "b2-faq-4", question: "How can I become more comfortable sharing my thoughts?", answer: t("Start with the moments that already matter to you. You don't have to wait for something significant to happen. Sharing a small win, an interesting idea or a meaningful moment can be a natural way to build more open and authentic conversations.") }] },
      { id: 'b2-cta', type: 'cta', label: 'Talk It Out', target: { kind: 'route', value: 'product.talk_it_out' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'W2-G001', anchorText: null, relation: 'related_content' },
    { targetKind: 'content', targetRef: 'W2-A001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'product.talk_it_out', anchorText: 'Talk It Out', relation: 'product' },
  ],

  authoredOutsideWorkbook: ['cta block (target and label taken from the workbook Internal Linking Plan)'],
  missingFields: ['safety_notice (workbook supplies none)'],
};

// ─────────────────────────────────────────────────────────────────────────────
// W2-G001
// ─────────────────────────────────────────────────────────────────────────────

const W2_G001: Week2Asset = {
  editorialRef: "W2-G001",
  contentType: 'geo_article',
  publicLabel: 'Insight',
  title: "Why Do People Keep Things To Themselves?",
  slug: "why-do-people-keep-things-to-themselves",
  metaDescription: "Learn why people keep thoughts, feelings, achievements and everyday experiences to themselves, and how meaningful conversations can strengthen connection and emotional wellbeing.",
  week: 2,
  pillar: 'Someone To Talk To',
  tags: ['someone-to-talk-to', 'week-2'],

  typeFields: {
    core_concept: 'Why people keep things to themselves',
    supporting_concepts: [
      'Human Connection',
      'Meaningful Conversations',
      'Emotional Wellbeing',
      'Everyday Conversations',
      'Reflection',
      'Communication',
      'Self-awareness',
      'Belonging',
      'Personal Growth',
    ],
    citation_summary:
      "People keep things to themselves for many reasons, including not wanting to burden others, believing their thoughts are not important enough, assuming they won't be understood, or becoming accustomed to handling experiences privately. This behaviour is common and applies not only to difficult emotions but also to everyday thoughts, achievements, memories and moments. Meaningful conversations help strengthen connection, trust and emotional wellbeing by giving those experiences space to be shared.",
    key_statements: [
      "Keeping thoughts to yourself is a common human behaviour.",
      "People stay quiet for many different reasons, not just because something is wrong.",
      "Privacy and silence are not the same thing.",
      "Meaningful conversations can begin with ordinary moments, not only difficult ones.",
      "Strong relationships are often built through many small conversations over time.",
      "Feeling understood is often more valuable than receiving advice.",
      "Everyday conversations contribute to emotional wellbeing and human connection."
],
    topics: {
      primary: 'Why Do People Keep Things To Themselves?',
      secondary: ['Human Behaviour', 'Communication', 'Wellbeing'],
    },
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'Create the most structured and trustworthy explanation of why people keep things to themselves.',
    strategy: 'Structured for retrieval: every section answers one clear concept, avoids long storytelling and prioritises clarity.',
    goal: 'AI Search Visibility',
    target_engines: ['ChatGPT', 'Gemini', 'Claude', 'Perplexity', 'Copilot'],
    business_goal: 'Establish SOLACE as a trusted authority that AI assistants can confidently reference when explaining why people keep thoughts, emotions and experiences to themselves.',
    primary_kpi: 'AI citations',
    secondary_kpi: 'Organic impressions',
    geo_focus: 'AI Retrieval',
    citation_friendly: 'Yes',
  },

  body: {
    version: 1,
    blocks: [
      { id: "g2-h1", type: 'heading', level: 2, content: t("Definition") },
      { id: "g2-p2", type: 'paragraph', content: t("People keep things to themselves for many different reasons. It is often not because they have nothing to say, but because they decide, consciously or unconsciously, that what they are thinking or feeling is not worth sharing.") },
      { id: "g2-p3", type: 'paragraph', content: t("This can apply to:") },
      { id: "g2-list4", type: 'list', style: 'bullet', items: [t("Thoughts"), t("Feelings"), t("Achievements"), t("Questions"), t("Memories"), t("Ideas"), t("Everyday experiences")] },
      { id: "g2-p5", type: 'paragraph', content: t("Keeping something to yourself is a common human behaviour and does not automatically indicate that something is wrong.") },
      { id: "g2-h6", type: 'heading', level: 2, content: t("Why Do People Keep Things To Themselves?") },
      { id: "g2-p7", type: 'paragraph', content: t("There is rarely one single reason.") },
      { id: "g2-p8", type: 'paragraph', content: t("More often, it is a combination of habits, past experiences and social expectations.") },
      { id: "g2-p9", type: 'paragraph', content: t("People may stay quiet because they:") },
      { id: "g2-list10", type: 'list', style: 'bullet', items: [t("Don't want to interrupt someone else's day."), t("Believe their thoughts are too small to matter."), t("Assume others won't understand."), t("Prefer to process things internally first."), t("Have become used to solving problems independently."), t("Don't know how to begin the conversation."), t("Think they will talk about it later.")] },
      { id: "g2-p11", type: 'paragraph', content: t("Many of these decisions happen automatically rather than intentionally.") },
      { id: "g2-h12", type: 'heading', level: 2, content: t("Common Reasons People Stay Quiet") },
      { id: "g2-h13", type: 'heading', level: 3, content: t("1. They Don't Want To Burden Others") },
      { id: "g2-p14", type: 'paragraph', content: t("Many people worry that sharing their thoughts will create extra pressure for someone else.") },
      { id: "g2-p15", type: 'paragraph', content: t("Instead of reaching out, they choose to carry the thought themselves.") },
      { id: "g2-h16", type: 'heading', level: 3, content: t("2. They Minimise Their Own Experiences") },
      { id: "g2-p17", type: 'paragraph', content: t("People often compare their experiences with those of others.") },
      { id: "g2-p18", type: 'paragraph', content: t("They may think:") },
      { id: "g2-p19", type: 'paragraph', content: t("\"Other people have bigger problems.\"") },
      { id: "g2-p20", type: 'paragraph', content: t("\"This isn't important enough.\"") },
      { id: "g2-p21", type: 'paragraph', content: t("As a result, meaningful moments remain unspoken.") },
      { id: "g2-h22", type: 'heading', level: 3, content: t("3. They Assume They Won't Be Understood") },
      { id: "g2-p23", type: 'paragraph', content: t("Sometimes people stay quiet because explaining a thought or feeling seems exhausting.") },
      { id: "g2-p24", type: 'paragraph', content: t("Rather than risk feeling misunderstood, they choose silence.") },
      { id: "g2-h25", type: 'heading', level: 3, content: t("4. Silence Becomes A Habit") },
      { id: "g2-p26", type: 'paragraph', content: t("The more often someone decides not to share, the easier that behaviour becomes.") },
      { id: "g2-p27", type: 'paragraph', content: t("Over time, silence can become the default response.") },
      { id: "g2-h28", type: 'heading', level: 3, content: t("5. They Prefer To Think First") },
      { id: "g2-p29", type: 'paragraph', content: t("Some people naturally process experiences internally before discussing them.") },
      { id: "g2-p30", type: 'paragraph', content: t("This can be healthy when it is a conscious choice rather than an automatic pattern.") },
      { id: "g2-h31", type: 'heading', level: 3, content: t("6. They Don't Know How To Start") },
      { id: "g2-p32", type: 'paragraph', content: t("Beginning a conversation is often more difficult than having one.") },
      { id: "g2-p33", type: 'paragraph', content: t("People may know they want to talk but struggle to find the right words.") },
      { id: "g2-h34", type: 'heading', level: 2, content: t("Is It Normal To Keep Things To Yourself?") },
      { id: "g2-p35", type: 'paragraph', content: t("Yes.") },
      { id: "g2-p36", type: 'paragraph', content: t("Almost everyone keeps some thoughts private.") },
      { id: "g2-p37", type: 'paragraph', content: t("Privacy is a healthy part of life.") },
      { id: "g2-p38", type: 'paragraph', content: t("The important distinction is whether staying quiet is a choice or a habit.") },
      { id: "g2-p39", type: 'paragraph', content: t("Many people choose privacy for:") },
      { id: "g2-list40", type: 'list', style: 'bullet', items: [t("Personal reflection."), t("Processing emotions."), t("Protecting boundaries."), t("Waiting for the right moment.")] },
      { id: "g2-p41", type: 'paragraph', content: t("However, if someone consistently avoids sharing thoughts they genuinely want to express, it may be helpful to explore why.") },
      { id: "g2-h42", type: 'heading', level: 2, content: t("Common Misconceptions") },
      { id: "g2-h43", type: 'heading', level: 3, content: t("Misconception 1") },
      { id: "g2-p44", type: 'paragraph', content: t("People only keep painful emotions inside.") },
      { id: "g2-h45", type: 'heading', level: 4, content: t("Reality") },
      { id: "g2-p46", type: 'paragraph', content: t("People also keep:") },
      { id: "g2-list47", type: 'list', style: 'bullet', items: [t("Good news."), t("Exciting ideas."), t("Gratitude."), t("Small achievements."), t("Everyday observations."), t("Happy memories.")] },
      { id: "g2-p48", type: 'paragraph', content: t("Many meaningful experiences remain private simply because they never become conversations.") },
      { id: "g2-h49", type: 'heading', level: 3, content: t("Misconception 2") },
      { id: "g2-p50", type: 'paragraph', content: t("Talking is only important during difficult times.") },
      { id: "g2-h51", type: 'heading', level: 4, content: t("Reality") },
      { id: "g2-p52", type: 'paragraph', content: t("Everyday conversations help strengthen relationships, trust and connection long before challenges arise.") },
      { id: "g2-h53", type: 'heading', level: 3, content: t("Misconception 3") },
      { id: "g2-p54", type: 'paragraph', content: t("If someone isn't talking, they don't want to.") },
      { id: "g2-h55", type: 'heading', level: 4, content: t("Reality") },
      { id: "g2-p56", type: 'paragraph', content: t("Some people want to talk but are unsure how to begin, worry about being misunderstood, or believe their thoughts aren't important enough to share.") },
      { id: "g2-h57", type: 'heading', level: 2, content: t("Why Everyday Conversations Matter") },
      { id: "g2-p58", type: 'paragraph', content: t("Not every conversation needs to solve a problem.") },
      { id: "g2-p59", type: 'paragraph', content: t("Many conversations simply help people:") },
      { id: "g2-list60", type: 'list', style: 'bullet', items: [t("Feel understood."), t("Share experiences."), t("Build stronger relationships."), t("Reflect on ideas."), t("Celebrate progress."), t("Strengthen connection.")] },
      { id: "g2-p61", type: 'paragraph', content: t("Meaningful conversations are part of everyday life, not only moments of crisis.") },
      { id: "g2-h62", type: 'heading', level: 2, content: t("Healthy Ways To Approach Conversations") },
      { id: "g2-p63", type: 'paragraph', content: t("Small conversations are often easier than waiting for a \"perfect\" moment.") },
      { id: "g2-p64", type: 'paragraph', content: t("Helpful approaches include:") },
      { id: "g2-list65", type: 'list', style: 'bullet', items: [t("Sharing one thought instead of everything at once."), t("Talking about everyday experiences."), t("Celebrating small achievements."), t("Asking simple questions."), t("Choosing someone who listens without judgment."), t("Allowing conversations to develop naturally.")] },
      { id: "g2-p66", type: 'paragraph', content: t("The goal is not to share everything.") },
      { id: "g2-p67", type: 'paragraph', content: t("The goal is to create opportunities for genuine connection.") },
      { id: "g2-h68", type: 'heading', level: 2, content: t("The SOLACE Perspective") },
      { id: "g2-p69", type: 'paragraph', content: t("At SOLACE, we believe people don't only carry difficult emotions.") },
      { id: "g2-p70", type: 'paragraph', content: t("They carry their entire human experience.") },
      { id: "g2-p71", type: 'paragraph', content: t("That includes:") },
      { id: "g2-list72", type: 'list', style: 'bullet', items: [t("Joy."), t("Hope."), t("Curiosity."), t("Gratitude."), t("Questions."), t("Memories."), t("Achievements."), t("Everyday thoughts.")] },
      { id: "g2-p73", type: 'paragraph', content: t("Meaningful conversations don't have to begin with a crisis.") },
      { id: "g2-p74", type: 'paragraph', content: t("Sometimes they begin with something as simple as:") },
      { id: "g2-p75", type: 'paragraph', content: t("\"Something happened today, and I'd like to tell someone about it.\"") },
      { id: "g2-p76", type: 'paragraph', content: t("Creating space for those everyday conversations can help people feel more connected to themselves and to others.") },
      { id: "g2-take77", type: 'key_takeaway', title: "Key Takeaways", points: [t("Keeping thoughts to yourself is a common human behaviour."), t("People stay quiet for many different reasons, not just because something is wrong."), t("Privacy and silence are not the same thing."), t("Meaningful conversations can begin with ordinary moments, not only difficult ones."), t("Strong relationships are often built through many small conversations over time."), t("Feeling understood is often more valuable than receiving advice."), t("Everyday conversations contribute to emotional wellbeing and human connection.")] },
      { id: "g2-faq", type: 'faq', heading: "Related Questions", items: [{ id: "g2-faq-1", question: "Why do people find it difficult to open up?", answer: t("People may worry about burdening others, fear being misunderstood, struggle to find the right words, or simply be accustomed to handling things on their own.") }, { id: "g2-faq-2", question: "Is it healthy to keep everything to yourself?", answer: t("Keeping some thoughts private is a normal part of life. However, consistently avoiding conversations you genuinely want to have can lead to missed opportunities for connection and understanding.") }, { id: "g2-faq-3", question: "Why do conversations matter even when nothing is wrong?", answer: t("Everyday conversations help build trust, strengthen relationships and create connection. They allow people to share experiences, ideas and achievements while supporting overall emotional wellbeing.") }, { id: "g2-faq-4", question: "What makes a conversation meaningful?", answer: t("A meaningful conversation is one where people feel heard, understood and able to share honestly. It doesn't have to involve a major life event. Ordinary moments can be just as meaningful as difficult ones.") }] },
      { id: 'g2-cta', type: 'cta', label: "Talk through what's on your mind", target: { kind: 'route', value: 'product.talk_it_out' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'W2-B001', anchorText: null, relation: 'related_content' },
    { targetKind: 'content', targetRef: 'W2-A001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'product.talk_it_out', anchorText: "Talk through what's on your mind", relation: 'product' },
  ],

  authoredOutsideWorkbook: ['cta block (target and label taken from the workbook Internal Linking Strategy)'],
  missingFields: ['safety_notice (workbook supplies none)'],
};

// ─────────────────────────────────────────────────────────────────────────────
// W2-A001
// ─────────────────────────────────────────────────────────────────────────────

const W2_A001: Week2Asset = {
  editorialRef: "W2-A001",
  contentType: 'aeo_answer',
  publicLabel: 'Answer',
  title: "Why Do People Keep Things to Themselves? Questions Answered",
  slug: "questions-about-everyday-conversations",
  metaDescription: "Find clear answers to common questions about meaningful conversations, emotional wellbeing, and why people often keep thoughts and experiences to themselves.",
  week: 2,
  pillar: 'Someone To Talk To',
  tags: ['someone-to-talk-to', 'week-2'],

  typeFields: {
    primary_question: 'Why do people keep things to themselves?',
    supporting_queries: [
      'Is it normal to want someone to talk to?',
      'Why are everyday conversations important?',
      "Why don't people open up?",
      'What makes a conversation meaningful?',
      'Is it healthy to keep everything inside?',
      'Why do people feel unheard?',
      'Why do people overthink conversations?',
      'How can I become more comfortable talking?',
      'Why do small conversations matter?',
      'Can talking support emotional wellbeing?',
      "What's the difference between privacy and isolation?",
    ],
    snippet_answer:
      "People often keep things to themselves because they don't want to burden others, believe their thoughts aren't important enough, or simply become used to handling experiences privately. This is common and doesn't only apply to difficult emotions.",
  },

  // Internal only. Never serialised to a public response.
  editorial: {
    purpose: 'Answer the questions people actually ask about everyday conversations, immediately and independently of any other section.',
    strategy: 'Answer-first: short answer, expanded answer, key takeaways, related questions.',
    goal: 'AI Answer Visibility',
    target_engines: [
      'Google AI Overviews',
      'ChatGPT',
      'Gemini',
      'Claude',
      'Perplexity',
      'Voice Assistants',
    ],
    business_goal: 'Position SOLACE as a trusted answer source for everyday conversation and emotional wellbeing questions.',
    primary_kpi: 'AI Answer Citations',
    secondary_kpi: 'Featured Snippets',
    aeo_signal: 'direct answer in first block',
  },

  body: {
    version: 1,
    blocks: [
      { id: 'a2-direct-answer', type: 'direct_answer', content: t("People keep things to themselves for many reasons. They may not want to burden others, believe their thoughts are too small to matter, worry they won't be understood, or simply become accustomed to processing experiences privately. This applies to everyday thoughts, achievements, questions and emotions, not just difficult experiences.") },
      { id: "a2-h1", type: 'heading', level: 2, content: t("Why do people keep things to themselves?") },
      { id: "a2-p2", type: 'paragraph', content: t("Keeping things to yourself is a common human behaviour rather than an unusual one. Many people automatically filter what they share without consciously realizing it.") },
      { id: "a2-p3", type: 'paragraph', content: t("For example, someone may decide not to mention a personal achievement because they think it isn't important enough, or they may avoid sharing a thought because they assume others are too busy.") },
      { id: "a2-p4", type: 'paragraph', content: t("Over time, these small decisions can become habits. While privacy is healthy, consistently avoiding conversations you genuinely want to have can reduce opportunities for connection and understanding.") },
      { id: "a2-p5", type: 'paragraph', content: t("Meaningful conversations aren't only valuable during difficult moments. Sharing everyday experiences can strengthen relationships and emotional wellbeing over time.") },
      { id: "a2-take6", type: 'key_takeaway', title: "Key Takeaways", points: [t("Keeping thoughts private is common."), t("People often stay quiet without intending to."), t("Everyday experiences deserve conversations too."), t("Privacy and isolation are not the same thing.")] },
      { id: "a2-h7", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list8", type: 'list', style: 'bullet', items: [t("Why don't people open up?"), t("Is it normal to keep things to yourself?"), t("Why do conversations matter?")] },
      { id: "a2-h9", type: 'heading', level: 2, content: t("Is it normal to want someone to talk to even when nothing is wrong?") },
      { id: "a2-p10", type: 'paragraph', content: t("Yes. Wanting someone to talk to during ordinary moments is completely normal. Conversations aren't only for solving problems. They also help people share experiences, celebrate achievements, explore ideas and strengthen relationships.") },
      { id: "a2-p11", type: 'paragraph', content: t("Many people assume conversations are only necessary when they need advice or support. In reality, human connection is built through everyday interactions.") },
      { id: "a2-p12", type: 'paragraph', content: t("Sharing a funny story, celebrating a personal achievement, discussing an interesting idea or reflecting on your day all contribute to stronger relationships.") },
      { id: "a2-p13", type: 'paragraph', content: t("These ordinary conversations create familiarity, trust and belonging. They also make it easier to reach out during genuinely difficult times because the relationship already exists.") },
      { id: "a2-p14", type: 'paragraph', content: t("Talking when nothing is wrong isn't a sign that something is missing. It's often a healthy part of staying connected.") },
      { id: "a2-take15", type: 'key_takeaway', title: "Key Takeaways", points: [t("Conversations don't require a crisis."), t("Everyday communication builds stronger relationships."), t("Sharing positive experiences strengthens connection."), t("Feeling heard supports emotional wellbeing.")] },
      { id: "a2-h16", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list17", type: 'list', style: 'bullet', items: [t("Why are conversations important?"), t("What makes a conversation meaningful?"), t("Why do people seek connection?")] },
      { id: "a2-h18", type: 'heading', level: 2, content: t("Why are everyday conversations important?") },
      { id: "a2-p19", type: 'paragraph', content: t("Everyday conversations help build trust, strengthen relationships and create a sense of connection. They allow people to share ordinary experiences that gradually deepen understanding over time.") },
      { id: "a2-p20", type: 'paragraph', content: t("Relationships are usually built through many small conversations rather than a few major ones.") },
      { id: "a2-p21", type: 'paragraph', content: t("Talking about your day, sharing exciting news, discussing ideas or remembering meaningful moments creates familiarity and emotional closeness.") },
      { id: "a2-p22", type: 'paragraph', content: t("These conversations also help people process experiences, feel understood and maintain healthy communication habits.") },
      { id: "a2-p23", type: 'paragraph', content: t("Rather than waiting until something becomes overwhelming, everyday conversations encourage connection while life is unfolding.") },
      { id: "a2-take24", type: 'key_takeaway', title: "Key Takeaways", points: [t("Everyday conversations strengthen trust."), t("Small conversations often create lasting relationships."), t("Connection grows through consistency."), t("Ordinary moments are worth sharing.")] },
      { id: "a2-h25", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list26", type: 'list', style: 'bullet', items: [t("Why does communication matter?"), t("How do conversations build relationships?"), t("What creates human connection?")] },
      { id: "a2-h27", type: 'heading', level: 2, content: t("Why don't people open up?") },
      { id: "a2-p28", type: 'paragraph', content: t("People may find it difficult to open up because they worry about burdening others, fear being misunderstood, struggle to find the right words or have become accustomed to handling things privately.") },
      { id: "a2-p29", type: 'paragraph', content: t("Opening up is rarely about having nothing to say.") },
      { id: "a2-p30", type: 'paragraph', content: t("More often, it's about uncertainty.") },
      { id: "a2-p31", type: 'paragraph', content: t("Someone may wonder whether their experience is important enough, whether another person will understand, or whether it's the right time to begin the conversation.") },
      { id: "a2-p32", type: 'paragraph', content: t("Past experiences, communication habits and personal preferences can also influence how comfortable someone feels sharing thoughts.") },
      { id: "a2-p33", type: 'paragraph', content: t("Recognising these patterns is often the first step toward building more open and meaningful conversations.") },
      { id: "a2-take34", type: 'key_takeaway', title: "Key Takeaways", points: [t("Most people have reasons for staying quiet."), t("Opening up often feels more difficult than continuing a conversation."), t("Understanding creates safety."), t("Strong relationships make conversations easier.")] },
      { id: "a2-h35", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list36", type: 'list', style: 'bullet', items: [t("Why do people stay quiet?"), t("Is it difficult to talk about feelings?"), t("How can I start a conversation?")] },
      { id: "a2-h37", type: 'heading', level: 2, content: t("What makes a conversation meaningful?") },
      { id: "a2-p38", type: 'paragraph', content: t("A meaningful conversation is one where people feel heard, understood and able to share honestly. It doesn't have to involve a major life event. Everyday experiences can create meaningful conversations too.") },
      { id: "a2-p39", type: 'paragraph', content: t("Meaningful conversations are less about the topic and more about the quality of the interaction.") },
      { id: "a2-p40", type: 'paragraph', content: t("Feeling listened to without judgment, having the space to express thoughts openly and knowing someone is genuinely present often matter more than receiving advice.") },
      { id: "a2-p41", type: 'paragraph', content: t("Many meaningful conversations begin with ordinary moments such as sharing an achievement, asking a question or reflecting on something that happened during the day.") },
      { id: "a2-p42", type: 'paragraph', content: t("Connection grows when people feel their experiences matter, regardless of how big or small they seem.") },
      { id: "a2-take43", type: 'key_takeaway', title: "Key Takeaways", points: [t("Feeling understood matters more than receiving advice."), t("Meaningful conversations can be simple."), t("Trust develops through genuine listening."), t("Ordinary moments can create lasting memories.")] },
      { id: "a2-h44", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list45", type: 'list', style: 'bullet', items: [t("How do conversations build trust?"), t("Why do people need connection?"), t("What helps people feel understood?")] },
      { id: "a2-h46", type: 'heading', level: 2, content: t("Is it healthy to keep everything inside?") },
      { id: "a2-p47", type: 'paragraph', content: t("Keeping some thoughts private is a normal part of life, but consistently keeping everything inside can reduce opportunities for connection, reflection and support. Healthy communication usually involves choosing when and with whom to share meaningful experiences.") },
      { id: "a2-p48", type: 'paragraph', content: t("Privacy is an important part of healthy relationships and personal wellbeing. Everyone has thoughts and experiences they choose not to share.") },
      { id: "a2-p49", type: 'paragraph', content: t("However, if someone repeatedly avoids conversations they genuinely want to have, they may gradually become more disconnected from others. This doesn't necessarily happen because they lack people around them, but because sharing becomes less familiar over time.") },
      { id: "a2-p50", type: 'paragraph', content: t("Healthy communication isn't about sharing everything. It's about knowing that you have the freedom to share when something matters to you.") },
      { id: "a2-take51", type: 'key_takeaway', title: "Key Takeaways", points: [t("Privacy is healthy."), t("Keeping everything inside isn't always helpful."), t("Conversations are a choice, not an obligation."), t("Sharing meaningful experiences can strengthen connection.")] },
      { id: "a2-h52", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list53", type: 'list', style: 'bullet', items: [t("Why do people stay quiet?"), t("Why don't people open up?"), t("What makes conversations meaningful?")] },
      { id: "a2-h54", type: 'heading', level: 2, content: t("Why do people feel unheard?") },
      { id: "a2-p55", type: 'paragraph', content: t("People often feel unheard when they don't believe their experiences are understood, acknowledged or valued. Feeling heard is about more than being listened to. It is about feeling genuinely understood.") },
      { id: "a2-p56", type: 'paragraph', content: t("Someone can be listening without truly understanding.") },
      { id: "a2-p57", type: 'paragraph', content: t("Feeling heard usually comes from conversations where people feel comfortable expressing themselves without being judged or interrupted.") },
      { id: "a2-p58", type: 'paragraph', content: t("Many people also stop sharing because previous experiences made them feel dismissed or misunderstood. Over time, this can reduce their willingness to start new conversations.") },
      { id: "a2-p59", type: 'paragraph', content: t("Creating space for curiosity, patience and active listening helps people feel more comfortable sharing everyday thoughts and experiences.") },
      { id: "a2-take60", type: 'key_takeaway', title: "Key Takeaways", points: [t("Listening and understanding are different."), t("Feeling heard builds trust."), t("Curiosity strengthens conversations."), t("Small moments of validation matter.")] },
      { id: "a2-h61", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list62", type: 'list', style: 'bullet', items: [t("What is active listening?"), t("Why is human connection important?"), t("What makes someone feel understood?")] },
      { id: "a2-h63", type: 'heading', level: 2, content: t("Why do people overthink conversations?") },
      { id: "a2-p64", type: 'paragraph', content: t("People often overthink conversations because they worry about how they will be perceived, whether their thoughts are important enough, or how someone else might respond.") },
      { id: "a2-p65", type: 'paragraph', content: t("Before speaking, many people mentally rehearse what they want to say.") },
      { id: "a2-p66", type: 'paragraph', content: t("They may edit their thoughts, predict possible reactions or question whether the conversation is worth having.") },
      { id: "a2-p67", type: 'paragraph', content: t("While reflection can be helpful, excessive overthinking sometimes prevents conversations from happening at all.") },
      { id: "a2-p68", type: 'paragraph', content: t("Remembering that conversations don't have to be perfect can make it easier to communicate naturally.") },
      { id: "a2-take69", type: 'key_takeaway', title: "Key Takeaways", points: [t("Overthinking is common."), t("Many people edit themselves before speaking."), t("Conversations don't need perfect words."), t("Honest communication is often enough.")] },
      { id: "a2-h70", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list71", type: 'list', style: 'bullet', items: [t("Why do I struggle to express myself?"), t("How do I stop overthinking conversations?"), t("Why is communication difficult?")] },
      { id: "a2-h72", type: 'heading', level: 2, content: t("How can I become more comfortable talking to someone?") },
      { id: "a2-p73", type: 'paragraph', content: t("Start with small conversations rather than waiting for a major reason to talk. Sharing ordinary experiences can make communication feel more natural over time.") },
      { id: "a2-p74", type: 'paragraph', content: t("Building confidence in conversations doesn't usually happen through one big discussion.") },
      { id: "a2-p75", type: 'paragraph', content: t("It often begins with everyday moments.") },
      { id: "a2-p76", type: 'paragraph', content: t("Sharing something interesting you noticed, celebrating a small success or asking a thoughtful question can gradually make conversations feel easier.") },
      { id: "a2-p77", type: 'paragraph', content: t("The goal isn't to become someone who shares everything.") },
      { id: "a2-p78", type: 'paragraph', content: t("The goal is to become comfortable sharing the things that genuinely matter to you.") },
      { id: "a2-take79", type: 'key_takeaway', title: "Key Takeaways", points: [t("Start small."), t("Practice through everyday conversations."), t("Authenticity matters more than perfection."), t("Confidence grows with repetition.")] },
      { id: "a2-h80", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list81", type: 'list', style: 'bullet', items: [t("How do I start a conversation?"), t("Why do conversations matter?"), t("How can I improve communication?")] },
      { id: "a2-h82", type: 'heading', level: 2, content: t("Why do small conversations matter?") },
      { id: "a2-p83", type: 'paragraph', content: t("Small conversations help build trust, familiarity and stronger relationships. They create everyday moments of connection that often become the foundation for deeper conversations later.") },
      { id: "a2-p84", type: 'paragraph', content: t("Many lasting relationships aren't built through dramatic moments.") },
      { id: "a2-p85", type: 'paragraph', content: t("They're built through consistent, ordinary conversations.") },
      { id: "a2-p86", type: 'paragraph', content: t("Talking about your day, sharing a funny story, celebrating a small achievement or asking how someone is doing all contribute to stronger relationships over time.") },
      { id: "a2-p87", type: 'paragraph', content: t("These conversations help people feel seen, remembered and connected.") },
      { id: "a2-take88", type: 'key_takeaway', title: "Key Takeaways", points: [t("Small conversations create trust."), t("Everyday moments strengthen relationships."), t("Consistency builds connection."), t("Meaning isn't measured by the size of the conversation.")] },
      { id: "a2-h89", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list90", type: 'list', style: 'bullet', items: [t("Why is communication important?"), t("How are relationships built?"), t("What creates human connection?")] },
      { id: "a2-h91", type: 'heading', level: 2, content: t("Can talking improve emotional wellbeing?") },
      { id: "a2-p92", type: 'paragraph', content: t("Meaningful conversations can support emotional wellbeing by helping people feel understood, reflect on experiences and strengthen their relationships. Talking isn't a solution to every challenge, but connection is an important part of overall wellbeing.") },
      { id: "a2-p93", type: 'paragraph', content: t("Conversations allow people to organise thoughts, celebrate achievements, ask questions and explore experiences with others.") },
      { id: "a2-p94", type: 'paragraph', content: t("Feeling understood can reduce the sense of carrying everything alone, even when the conversation doesn't solve a specific problem.") },
      { id: "a2-p95", type: 'paragraph', content: t("Regular communication also helps maintain relationships that provide support throughout everyday life.") },
      { id: "a2-take96", type: 'key_takeaway', title: "Key Takeaways", points: [t("Conversations support connection."), t("Feeling understood matters."), t("Talking can encourage reflection."), t("Everyday communication contributes to wellbeing.")] },
      { id: "a2-h97", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list98", type: 'list', style: 'bullet', items: [t("Why do conversations matter?"), t("Why do people need connection?"), t("What is emotional wellbeing?")] },
      { id: "a2-h99", type: 'heading', level: 2, content: t("What's the difference between privacy and isolation?") },
      { id: "a2-p100", type: 'paragraph', content: t("Privacy is choosing what you keep to yourself. Isolation is feeling disconnected from meaningful relationships or opportunities to share. One is a healthy boundary, while the other may leave people feeling alone.") },
      { id: "a2-p101", type: 'paragraph', content: t("Everyone needs privacy.") },
      { id: "a2-p102", type: 'paragraph', content: t("Choosing not to share every thought or experience is a normal part of healthy relationships.") },
      { id: "a2-p103", type: 'paragraph', content: t("Isolation is different.") },
      { id: "a2-p104", type: 'paragraph', content: t("It occurs when someone consistently lacks meaningful connection or feels unable to share experiences they genuinely want to express.") },
      { id: "a2-p105", type: 'paragraph', content: t("Recognising this difference helps people make intentional choices about communication rather than remaining silent out of habit.") },
      { id: "a2-take106", type: 'key_takeaway', title: "Key Takeaways", points: [t("Privacy is healthy."), t("Isolation is different from privacy."), t("Choice is an important distinction."), t("Meaningful conversations support connection.")] },
      { id: "a2-h107", type: 'heading', level: 3, content: t("Related Questions") },
      { id: "a2-list108", type: 'list', style: 'bullet', items: [t("Why do people feel alone?"), t("Why do conversations matter?")] },
      { id: 'a2-cta', type: 'cta', label: "Talk through what's on your mind", target: { kind: 'route', value: 'product.talk_it_out' } },
    ],
  } as ContentBody,

  links: [
    { targetKind: 'content', targetRef: 'W2-B001', anchorText: null, relation: 'related_content' },
    { targetKind: 'content', targetRef: 'W2-G001', anchorText: null, relation: 'related_content' },
    { targetKind: 'route', targetRoute: 'product.talk_it_out', anchorText: "Talk through what's on your mind", relation: 'product' },
  ],

  authoredOutsideWorkbook: ['title (derived from the workbook SEO Title; the workbook gives this page no H1)', 'cta block (target and label taken from the workbook Internal Linking Strategy)'],
  missingFields: ['safety_notice (workbook supplies none)'],
};

/** The three Week 2 assets, in workbook order. */
export const WEEK2_ASSETS: Week2Asset[] = [W2_B001, W2_G001, W2_A001];

/**
 * Content-to-content edges the workbook's ecosystem section describes, as [source, target] pairs.
 *
 * The workbook states that the Week 2 assets "create a layered authority strategy where the same
 * core idea is expressed in different formats without duplication", and that the GEO page
 * "complements, rather than replaces, the Week 2 blog". Those are the relationships recorded here;
 * no link to Week 1 is created, because the workbook names none.
 */
export const EXPECTED_CONTENT_EDGES: Array<[string, string]> = [
  ['W2-B001', 'W2-G001'],
  ['W2-B001', 'W2-A001'],
  ['W2-G001', 'W2-B001'],
  ['W2-G001', 'W2-A001'],
  ['W2-A001', 'W2-B001'],
  ['W2-A001', 'W2-G001'],
];
